namespace FoodDiary.Application.Abstractions.Fasting.Common;

public interface IFastingCheckInRepository : IFastingCheckInReadRepository, IFastingCheckInReadModelRepository, IFastingCheckInWriteRepository;
