namespace FoodDiary.Application.Abstractions.Fasting.Common;

public interface IFastingOccurrenceRepository : IFastingOccurrenceReadRepository, IFastingOccurrenceReadModelRepository, IFastingOccurrenceWriteRepository;
