import type { AppConfig } from '../app/types/app.data';

const apiBasePath = '/api/v1';

export const environment: AppConfig = {
    apiUrls: {
        auth: `${apiBasePath}/auth`,
        billing: `${apiBasePath}/billing`,
        products: `${apiBasePath}/products`,
        consumptions: `${apiBasePath}/consumptions`,
        statistics: `${apiBasePath}/statistics`,
        users: `${apiBasePath}/users`,
        recipes: `${apiBasePath}/recipes`,
        logs: `${apiBasePath}/logs`,
        weights: `${apiBasePath}/weight-entries`,
        waists: `${apiBasePath}/waist-entries`,
        cycles: `${apiBasePath}/cycles`,
        dashboard: `${apiBasePath}/dashboard`,
        images: `${apiBasePath}/images`,
        hydration: `${apiBasePath}/hydrations`,
        goals: `${apiBasePath}/goals`,
        ai: `${apiBasePath}/ai`,
        shoppingLists: `${apiBasePath}/shopping-lists`,
        dietologist: `${apiBasePath}/dietologist`,
        fasting: `${apiBasePath}/fasting`,
        favoriteMeals: `${apiBasePath}/favorite-meals`,
        favoriteProducts: `${apiBasePath}/favorite-products`,
        favoriteRecipes: `${apiBasePath}/favorite-recipes`,
        gamification: `${apiBasePath}/gamification`,
        weeklyCheckIn: `${apiBasePath}/weekly-check-in`,
        tdee: `${apiBasePath}/tdee`,
        mealPlans: `${apiBasePath}/meal-plans`,
        exercises: `${apiBasePath}/exercises`,
        lessons: `${apiBasePath}/lessons`,
        usda: `${apiBasePath}/usda`,
        wearables: `${apiBasePath}/wearables`,
        reports: `${apiBasePath}/reports`,
        openFoodFacts: `${apiBasePath}/open-food-facts`,
        export: `${apiBasePath}/export`,
    },
    paddleClientToken: '',
    googleClientId: '958507321562-8btd704hjhgsl7niklereh81utg5p780.apps.googleusercontent.com',
    telegramBotUsername: 'fooddiaryclub_bot',
    buildVersion: '__BUILD_VERSION__',
    adminAppUrl: 'https://admin.fooddiary.club',
    supportEmail: 'admin@fooddiary.club',
    enableGlobalErrorHandler: true,
    enableClientObservability: true,
};
