import { AppConfig } from '../app/types/app.data';

const serverUrl = 'http://localhost:3000';

export const environment: AppConfig = {
    apiUrls: {
        auth: `${serverUrl}/api/v1/auth`,
        products: `${serverUrl}/api/v1/products`,
        consumptions: `${serverUrl}/api/v1/consumptions`,
        statistics: `${serverUrl}/api/v1/statistics`,
        users: `${serverUrl}/api/v1/users`,
        recipes: `${serverUrl}/api/v1/recipes`,
        logs: `${serverUrl}/api/v1/logs`,
        weights: `${serverUrl}/api/v1/weight-entries`,
        waists: `${serverUrl}/api/v1/waist-entries`,
        cycles: `${serverUrl}/api/v1/cycles`,
        dashboard: `${serverUrl}/api/v1/dashboard`,
        images: `${serverUrl}/api/v1/images`,
        hydration: `${serverUrl}/api/v1/hydrations`,
        goals: `${serverUrl}/api/v1/goals`,
        ai: `${serverUrl}/api/v1/ai`,
        shoppingLists: `${serverUrl}/api/v1/shopping-lists`,
        dietologist: `${serverUrl}/api/v1/dietologist`,
        fasting: `${serverUrl}/api/v1/fasting`,
        favoriteMeals: `${serverUrl}/api/v1/favorite-meals`,
        gamification: `${serverUrl}/api/v1/gamification`,
        weeklyCheckIn: `${serverUrl}/api/v1/weekly-check-in`,
        tdee: `${serverUrl}/api/v1/tdee`,
        mealPlans: `${serverUrl}/api/v1/meal-plans`,
        exercises: `${serverUrl}/api/v1/exercises`,
        lessons: `${serverUrl}/api/v1/lessons`,
        usda: `${serverUrl}/api/v1/usda`,
        wearables: `${serverUrl}/api/v1/wearables`,
        reports: `${serverUrl}/api/v1/reports`,
        openFoodFacts: `${serverUrl}/api/v1/open-food-facts`,
        export: `${serverUrl}/api/v1/export`,
    },
    googleClientId: '958507321562-8btd704hjhgsl7niklereh81utg5p780.apps.googleusercontent.com',
    buildVersion: '__BUILD_VERSION__',
    adminAppUrl: 'https://admin.fooddiary.club',
    enableGlobalErrorHandler: true,
    enableClientObservability: true,
};
