<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.ContentReports.Application.Abstractions</AssemblyName>
    <RootNamespace>FoodDiary.Application.Abstractions.ContentReports</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Contracts/FoodDiary.Modules.ContentReports.Contracts.csproj" />
    <ProjectReference Include="../../Domain.Contracts/FoodDiary.Modules.ContentReports.Domain.Contracts.csproj" />
    <ProjectReference Include="../../Domain/FoodDiary.Modules.ContentReports.Domain.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>
</Project>
