<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../FoodDiary.Audit.Contracts/FoodDiary.Audit.Contracts.csproj" />
    <ProjectReference Include="../../FoodDiary.Audit.Infrastructure/FoodDiary.Audit.Infrastructure.csproj" />
    <ProjectReference Include="../../FoodDiary.Email.Contracts/FoodDiary.Email.Contracts.csproj" />
    <ProjectReference Include="../../FoodDiary.Email.Infrastructure/FoodDiary.Email.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../../FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
    <ProjectReference Include="../../FoodDiary.Persistence.Runtime/FoodDiary.Persistence.Runtime.csproj" />
  </ItemGroup>
</Project>
