<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../FoodDiary.Persistence.Runtime/FoodDiary.Persistence.Runtime.csproj" />
    <ProjectReference Include="../../FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
