<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Application.Abstractions.Images</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Service.Contracts/FoodDiary.Modules.Images.Service.Contracts.csproj" />
    <ProjectReference Include="..\..\Domain\FoodDiary.Modules.Images.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Results\FoodDiary.Results.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>
</Project>
