<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Application/Abstractions/FoodDiary.Modules.Cycles.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Infrastructure/FoodDiary.Modules.Cycles.Infrastructure.csproj" />
  </ItemGroup>
</Project>
