<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.WeeklyGoals.Infrastructure</AssemblyName>
    <RootNamespace>FoodDiary.Modules.WeeklyGoals.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Model/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\FoodDiary.Modules.WeeklyGoals.Application.csproj" />
    <ProjectReference Include="..\..\..\FoodDiary.Infrastructure\FoodDiary.Infrastructure.csproj" />
    <ProjectReference Include="Model\FoodDiary.Modules.WeeklyGoals.PersistenceModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
