namespace FoodDiary.Modules.Marketing.Application.Abstractions.Common;

public interface IMarketingAttributionEventRepository : IMarketingAttributionEventReadRepository, IMarketingAttributionEventWriteRepository;
