<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Application.Abstractions/FoodDiary.Modules.DailyAdvices.Application.Abstractions.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.DailyAdvices.Application.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.DailyAdvices.Domain.csproj" />
    <ProjectReference Include="../PersistenceModel/FoodDiary.Modules.DailyAdvices.PersistenceModel.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
