namespace FoodDiary.Application.Abstractions.Billing.Models;

public sealed record BillingWebhookEventModel(
    string EventId,
    string EventType,
    string ExternalCustomerId,
    string? ExternalSubscriptionId,
    string? ExternalPaymentMethodId,
    string? ExternalPriceId,
    string? Plan,
    string Status,
    DateTime? CurrentPeriodStartUtc,
    DateTime? CurrentPeriodEndUtc,
    bool CancelAtPeriodEnd,
    DateTime? CanceledAtUtc,
    DateTime? TrialStartUtc,
    DateTime? TrialEndUtc,
    decimal? Amount,
    string? Currency,
    string? ProviderMetadataJson,
    Guid? UserId,
    DateTime? OccurredAtUtc = null,
    string? ExternalPaymentId = null,
    string? RelatedTransactionId = null,
    string? FinancialAction = null,
    int? Quantity = null,
    bool UpdatesSubscription = true,
    decimal? Tax = null,
    decimal? Fee = null,
    decimal? Earnings = null,
    string? PayoutCurrency = null,
    decimal? PayoutEarnings = null,
    bool IsAuthoritativeSnapshot = false);
