namespace FoodDiary.Modules.Notifications.Application.Abstractions.Common;

public interface IWebPushSubscriptionRepository : IWebPushSubscriptionReadRepository, IWebPushSubscriptionReadModelRepository, IWebPushSubscriptionWriteRepository;
