<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FoodDiary.Presentation.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Dietologist/Presentation.Contracts/FoodDiary.Modules.Dietologist.Presentation.Contracts.csproj" />
    <ProjectReference Include="../../Notifications/Presentation/FoodDiary.Modules.Notifications.Presentation.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Asp.Versioning.Mvc" />
    <ProjectReference Include="../../../FoodDiary.Presentation.Api/FoodDiary.Presentation.Api.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.Users.Application.csproj" />
    <ProjectReference Include="../Application/Abstractions/FoodDiary.Modules.Users.Application.Abstractions.csproj" />
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>

</Project>
