namespace FoodDiary.Application.Abstractions.Dietologist.Common;

public interface IRecommendationBulkDispatchRepository
    : IRecommendationBulkDispatchLookupRepository, IRecommendationBulkDispatchWriteRepository;
