export const MEAL_API_DEFAULT_FAVORITE_LIMIT = 10;
export const MEAL_API_NUTRITION_CLOSE_TOLERANCE = 0.000001;
export const MEAL_API_DEFAULT_ITEM_AMOUNT = 1;
export const MEAL_API_EMPTY_NUTRITION_VALUE = 0;
