namespace FoodDiary.Modules.Identity.Application.Abstractions.Admin.Common;

public interface IEmailTemplateRepository : IEmailTemplateReadRepository, IEmailTemplateReadModelRepository, IEmailTemplateWriteRepository;
