<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NSubstitute" />
    <Using Include="FoodDiary.Testing" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Shared/FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Application.Runtime/FoodDiary.Application.Runtime.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Audit.Contracts/FoodDiary.Audit.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Audit.Infrastructure/FoodDiary.Audit.Infrastructure.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Domain.Primitives/FoodDiary.Domain.Primitives.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Email.Contracts/FoodDiary.Email.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Email.Infrastructure/FoodDiary.Email.Infrastructure.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Email.PersistenceModel/FoodDiary.Email.PersistenceModel.csproj" />
    <ProjectReference Include="../../../FoodDiary.Infrastructure/FoodDiary.Infrastructure.csproj" />
    <ProjectReference Include="../../../FoodDiary.Initializer/FoodDiary.Initializer.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Mediator/FoodDiary.Mediator.csproj" />
    <ProjectReference Include="../../../Modules/Admin/Application.Abstractions/FoodDiary.Modules.Admin.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Admin/Domain/FoodDiary.Modules.Admin.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Admin/Infrastructure/FoodDiary.Modules.Admin.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Admin/PersistenceModel/FoodDiary.Modules.Admin.PersistenceModel.csproj" />
    <ProjectReference Include="../../../Modules/Ai/Application.Abstractions/FoodDiary.Modules.Ai.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Ai/Application/FoodDiary.Modules.Ai.Application.csproj" />
    <ProjectReference Include="../../../Modules/Ai/Contracts/FoodDiary.Modules.Ai.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Ai/Domain/FoodDiary.Modules.Ai.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Ai/Infrastructure/FoodDiary.Modules.Ai.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Ai/PersistenceModel/FoodDiary.Modules.Ai.PersistenceModel.csproj" />
    <ProjectReference Include="../../../Modules/Billing/Application.Abstractions/FoodDiary.Modules.Billing.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Billing/Application/FoodDiary.Modules.Billing.Application.csproj" />
    <ProjectReference Include="../../../Modules/Billing/Contracts/FoodDiary.Modules.Billing.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Billing/Domain.Contracts/FoodDiary.Modules.Billing.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Billing/Domain/FoodDiary.Modules.Billing.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Billing/Infrastructure/FoodDiary.Modules.Billing.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/BodyMetrics/Application.Abstractions/FoodDiary.Modules.BodyMetrics.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/BodyMetrics/Domain/FoodDiary.Modules.BodyMetrics.Domain.csproj" />
    <ProjectReference Include="../../../Modules/BodyMetrics/Infrastructure/FoodDiary.Modules.BodyMetrics.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/ContentReports/Application.Abstractions/FoodDiary.Modules.ContentReports.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/ContentReports/Contracts/FoodDiary.Modules.ContentReports.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/ContentReports/Domain.Contracts/FoodDiary.Modules.ContentReports.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/ContentReports/Domain/FoodDiary.Modules.ContentReports.Domain.csproj" />
    <ProjectReference Include="../../../Modules/ContentReports/Infrastructure/FoodDiary.Modules.ContentReports.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Cycles/Application.Abstractions/FoodDiary.Modules.Cycles.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Cycles/Domain/FoodDiary.Modules.Cycles.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Cycles/Infrastructure/FoodDiary.Modules.Cycles.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/DailyAdvices/Application.Abstractions/FoodDiary.Modules.DailyAdvices.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/DailyAdvices/Domain/FoodDiary.Modules.DailyAdvices.Domain.csproj" />
    <ProjectReference Include="../../../Modules/DailyAdvices/Infrastructure/FoodDiary.Modules.DailyAdvices.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Dashboard/Infrastructure/FoodDiary.Modules.Dashboard.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Dietologist/Application.Abstractions/FoodDiary.Modules.Dietologist.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Dietologist/Domain/FoodDiary.Modules.Dietologist.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Dietologist/Infrastructure/FoodDiary.Modules.Dietologist.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Exercises/Application.Abstractions/FoodDiary.Modules.Exercises.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Exercises/Domain/FoodDiary.Modules.Exercises.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Exercises/Infrastructure/FoodDiary.Modules.Exercises.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Fasting/Application.Abstractions/FoodDiary.Modules.Fasting.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Fasting/Domain/FoodDiary.Modules.Fasting.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Fasting/Infrastructure/FoodDiary.Modules.Fasting.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Favorites/Application.Abstractions/FoodDiary.Modules.Favorites.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Favorites/Domain/FoodDiary.Modules.Favorites.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Favorites/Infrastructure/FoodDiary.Modules.Favorites.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Gamification/Application.Abstractions/FoodDiary.Modules.Gamification.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Gamification/Contracts/FoodDiary.Modules.Gamification.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Gamification/Domain.Contracts/FoodDiary.Modules.Gamification.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Gamification/Infrastructure/FoodDiary.Modules.Gamification.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Hydration/Application.Abstractions/FoodDiary.Modules.Hydration.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Hydration/Application/FoodDiary.Modules.Hydration.Application.csproj" />
    <ProjectReference Include="../../../Modules/Hydration/Domain/FoodDiary.Modules.Hydration.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Hydration/Infrastructure/FoodDiary.Modules.Hydration.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Identity/Application.Abstractions/FoodDiary.Modules.Identity.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Identity/Contracts/FoodDiary.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Identity/Infrastructure/FoodDiary.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Identity/PersistenceModel/FoodDiary.Modules.Identity.PersistenceModel.csproj" />
    <ProjectReference Include="../../../Modules/Images/Application.Abstractions/FoodDiary.Modules.Images.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Images/Application/FoodDiary.Modules.Images.Application.csproj" />
    <ProjectReference Include="../../../Modules/Images/Domain/FoodDiary.Modules.Images.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Images/Infrastructure/FoodDiary.Modules.Images.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Images/Service.Contracts/FoodDiary.Modules.Images.Service.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Lessons/Application.Abstractions/FoodDiary.Modules.Lessons.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Lessons/Application/FoodDiary.Modules.Lessons.Application.csproj" />
    <ProjectReference Include="../../../Modules/Lessons/Contracts/FoodDiary.Modules.Lessons.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Lessons/Domain.Contracts/FoodDiary.Modules.Lessons.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Lessons/Domain/FoodDiary.Modules.Lessons.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Lessons/Infrastructure/FoodDiary.Modules.Lessons.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Marketing/Application.Abstractions/FoodDiary.Modules.Marketing.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Marketing/Contracts/FoodDiary.Modules.Marketing.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Marketing/Domain/FoodDiary.Modules.Marketing.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Marketing/Infrastructure/FoodDiary.Modules.Marketing.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/MealPlanning/Application.Abstractions/FoodDiary.Modules.MealPlanning.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/MealPlanning/Domain/FoodDiary.Modules.MealPlanning.Domain.csproj" />
    <ProjectReference Include="../../../Modules/MealPlanning/Infrastructure/FoodDiary.Modules.MealPlanning.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Meals/Contracts/FoodDiary.Modules.Meals.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Meals/Domain.Contracts/FoodDiary.Modules.Meals.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Meals/Domain/FoodDiary.Modules.Meals.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Meals/Infrastructure/FoodDiary.Modules.Meals.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Notifications/Application.Abstractions/FoodDiary.Modules.Notifications.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Notifications/Contracts/FoodDiary.Modules.Notifications.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Notifications/Domain/FoodDiary.Modules.Notifications.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Notifications/Infrastructure/FoodDiary.Modules.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/OpenFoodFacts/Application.Abstractions/FoodDiary.Modules.OpenFoodFacts.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/OpenFoodFacts/Domain/FoodDiary.Modules.OpenFoodFacts.Domain.csproj" />
    <ProjectReference Include="../../../Modules/OpenFoodFacts/Infrastructure/FoodDiary.Modules.OpenFoodFacts.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Products/Contracts/FoodDiary.Modules.Products.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Products/Domain.Contracts/FoodDiary.Modules.Products.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Products/Infrastructure/FoodDiary.Modules.Products.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/RecentItems/Application.Abstractions/FoodDiary.Modules.RecentItems.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/RecentItems/Contracts/FoodDiary.Modules.RecentItems.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/RecentItems/Domain/FoodDiary.Modules.RecentItems.Domain.csproj" />
    <ProjectReference Include="../../../Modules/RecentItems/Infrastructure/FoodDiary.Modules.RecentItems.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/RecipeCommunity/Application.Abstractions/FoodDiary.Modules.RecipeCommunity.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/RecipeCommunity/Domain/FoodDiary.Modules.RecipeCommunity.Domain.csproj" />
    <ProjectReference Include="../../../Modules/RecipeCommunity/Infrastructure/FoodDiary.Modules.RecipeCommunity.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Recipes/Contracts/FoodDiary.Modules.Recipes.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Recipes/Domain/FoodDiary.Modules.Recipes.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Recipes/Infrastructure/FoodDiary.Modules.Recipes.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Usda/Application.Abstractions/FoodDiary.Modules.Usda.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Usda/Domain/FoodDiary.Modules.Usda.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Usda/Infrastructure/FoodDiary.Modules.Usda.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Users/Application.Abstractions/FoodDiary.Modules.Users.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Modules/Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../../../Modules/Users/Infrastructure/FoodDiary.Modules.Users.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/Wearables/Application.Abstractions/FoodDiary.Modules.Wearables.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Modules/Wearables/Infrastructure/FoodDiary.Modules.Wearables.Infrastructure.csproj" />
    <ProjectReference Include="../../../Modules/WeeklyGoals/Domain/FoodDiary.Modules.WeeklyGoals.Domain.csproj" />
    <ProjectReference Include="../../../Modules/WeeklyGoals/Infrastructure/FoodDiary.Modules.WeeklyGoals.Infrastructure.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Outbox.Abstractions/FoodDiary.Outbox.Abstractions.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Outbox.Infrastructure/FoodDiary.Outbox.Infrastructure.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Outbox.Management.Contracts/FoodDiary.Outbox.Management.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Persistence.Runtime/FoodDiary.Persistence.Runtime.csproj" />
    <ProjectReference Include="../../../FoodDiary.ReadModel.Composition/FoodDiary.ReadModel.Composition.csproj" />
    <ProjectReference Include="../../../Tooling/FoodDiary.Testing/FoodDiary.Testing.csproj" />
  </ItemGroup>
</Project>