<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FoodDiary.Application.Tests.Support" />
    <Using Include="NSubstitute" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\tests\FoodDiary.Application.Tests\Support\ResultAssert.cs" Link="Support\ResultAssert.cs" />
    <ProjectReference Include="../../Application.Abstractions/FoodDiary.Modules.Marketing.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Application/FoodDiary.Modules.Marketing.Application.csproj" />
    <ProjectReference Include="../../Contracts/FoodDiary.Modules.Marketing.Contracts.csproj" />
    <ProjectReference Include="../../../Billing/Application.Abstractions/FoodDiary.Modules.Billing.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Billing/Contracts/FoodDiary.Modules.Billing.Contracts.csproj" />
    <ProjectReference Include="../../../../Shared/FoodDiary.Mediator/FoodDiary.Mediator.csproj" />
    <ProjectReference Include="../../../../Tooling/FoodDiary.Testing/FoodDiary.Testing.csproj" />
  </ItemGroup>

</Project>
