<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Infrastructure.Persistence</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\FoodDiary.Modules.Images.Domain.csproj" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore" /></ItemGroup>
</Project>
