namespace FoodDiary.Modules.Ai.Application.Abstractions.Common;

public interface IAiPromptTemplateRepository : IAiPromptTemplateReadRepository, IAiPromptTemplateReadModelRepository, IAiPromptTemplateWriteRepository;
