<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FoodDiary.Application.Lessons</AssemblyName>
    <RootNamespace>FoodDiary.Application.Lessons</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Abstractions/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Abstractions\FoodDiary.Modules.Lessons.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Contracts\FoodDiary.Modules.Lessons.Contracts.csproj" />
    <ProjectReference Include="..\Domain\FoodDiary.Modules.Lessons.Domain.csproj" />
    <ProjectReference Include="..\..\..\FoodDiary.Application.Abstractions\FoodDiary.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Mediator\FoodDiary.Mediator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
