<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.WeeklyGoals.Application.Abstractions</AssemblyName>
    <RootNamespace>FoodDiary.Modules.WeeklyGoals.Application.Abstractions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\FoodDiary.Domain\FoodDiary.Domain.csproj" />
  </ItemGroup>

</Project>
