<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.WeeklyGoals.Application.Abstractions</AssemblyName>
    <RootNamespace>FoodDiary.Modules.WeeklyGoals.Application.Abstractions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Domain/FoodDiary.Modules.WeeklyGoals.Domain.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>

</Project>
