using FoodDiary.Application.Abstractions.Users.Common;
using FoodDiary.ReadModel.Composition.Users;
using FoodDiary.Modules.Ai.Application.Abstractions.Common;
using FoodDiary.ReadModel.Composition.Ai;
using FoodDiary.Application.Abstractions.Authentication.Common;
using FoodDiary.ReadModel.Composition.Identity;
using FoodDiary.ReadModel.Composition.Recipes;
using FoodDiary.Application.Abstractions.Products.Common;
using FoodDiary.ReadModel.Composition.Products;
using FoodDiary.ReadModel.Composition.Meals;
using FoodDiary.ReadModel.Composition.Dietologist;
using FoodDiary.Application.Abstractions.Dietologist.Common;
using FoodDiary.ReadModel.Composition.Favorites;
using FoodDiary.Application.Abstractions.FavoriteProducts.Common;
using FoodDiary.Application.Abstractions.FavoriteRecipes.Common;
using FoodDiary.Application.Abstractions.Achievements.Common;
using FoodDiary.Application.Abstractions.Images.Common;
using FoodDiary.ReadModel.Composition.Images;
using FoodDiary.ReadModel.Composition.Gamification;
using FoodDiary.Modules.ContentReports.Application.Abstractions.Common;
using FoodDiary.ReadModel.Composition.ContentReports;
using FoodDiary.Application.Abstractions.MealPlans.Common;
using FoodDiary.ReadModel.Composition.MealPlanning;
using FoodDiary.Modules.Admin.Application.Abstractions.Common;
using FoodDiary.Application.Abstractions.Dashboard.Common;
using FoodDiary.Application.Abstractions.FavoriteMeals.Common;
using FoodDiary.Application.Abstractions.Meals.Common;
using FoodDiary.Application.Abstractions.Recipes.Common;
using FoodDiary.Infrastructure.Persistence.Admin;
using FoodDiary.Infrastructure.Persistence.Meals;
using FoodDiary.Infrastructure.Persistence.Recipes;
using FoodDiary.Modules.Dashboard.Infrastructure.Persistence.Dashboard;
using FoodDiary.Modules.Favorites.Infrastructure.Persistence.FavoriteMeals;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace FoodDiary.ReadModel.Composition;

public static class ReadModelCompositionRegistration {
    public static IServiceCollection AddReadModelComposition(this IServiceCollection services) {
        services.AddScoped<IUserCurrentWeightProvider, UserCurrentWeightProvider>();
        services.AddScoped<IUserCurrentWaistProvider, UserCurrentWaistProvider>();
        services.AddScoped<IAiUsageQuery, AiUsageQuery>();
        services.AddScoped<IUserLoginEventQuery, UserLoginEventQuery>();
        services.AddScoped<IImageAssetUsageQuery, ImageAssetUsageQuery>();
        services.AddScoped<IAchievementMetricReader, AchievementMetricReader>();
        services.AddScoped<ContentReportReadService>();
        services.AddScoped<IContentReportReadModelRepository>(static provider => provider.GetRequiredService<ContentReportReadService>());
        services.AddScoped<IContentReportTargetReadService>(static provider => provider.GetRequiredService<ContentReportReadService>());
        services.AddScoped<IMealPlanCompositionReader, MealPlanCompositionReader>();
        services.AddScoped<IAdminDashboardMetricsReader, AdminDashboardMetricsReader>();
        services.AddScoped<IAdminRetentionReader, AdminRetentionReader>();
        services.AddScoped<IAdminUserRoleAuditRepository, AdminUserRoleAuditRepository>();
        services.AddScoped<IAdminUserRoleAuditQuery>(static provider => provider.GetRequiredService<IAdminUserRoleAuditRepository>());
        services.AddScoped<IAdminBillingRepository, AdminBillingRepository>();
        services.AddScoped<IAdminBillingQuery>(static provider => provider.GetRequiredService<IAdminBillingRepository>());
        services.AddScoped<IAdminImpersonationSessionQuery, AdminImpersonationSessionQuery>();
        services.AddScoped<IFavoriteMealQuery, FavoriteMealQuery>();
        services.AddScoped<IMealProductNutritionQuery, MealProductNutritionQuery>();
        services.AddScoped<IMealItemDisplayReadService, MealItemDisplayReadService>();
        services.AddScoped<IProductUsageQuery, ProductUsageQuery>();
        services.AddScoped<IProductOverviewReadService, ProductOverviewReadService>();
        services.AddScoped<IRecipeUsageQuery, RecipeUsageQuery>();
        services.AddScoped<IRecipeOverviewReadService, RecipeOverviewReadService>();
        services.RemoveAll<IDashboardBodyReadService>();
        services.AddScoped<DashboardBodyReadService>();
        services.AddScoped<IDashboardBodyReadService>(static provider => provider.GetRequiredService<DashboardBodyReadService>());
        services.RemoveAll<IDashboardMealsReadService>();
        services.AddScoped<DashboardMealsReadService>();
        services.AddScoped<IDashboardMealsReadService>(static provider => provider.GetRequiredService<DashboardMealsReadService>());
        services.AddScoped<IFavoriteProductQuery, FavoriteProductQuery>();
        services.AddScoped<IFavoriteRecipeQuery, FavoriteRecipeQuery>();
        services.AddScoped<IAttentionSignalMetricsReadService, AttentionSignalMetricsReadService>();
        services.AddScoped<IDietologistInvitationReadModelRepository, DietologistInvitationReadService>();
        services.AddScoped<IRecommendationReadModelRepository, RecommendationReadService>();
        services.AddScoped<IRecommendationCommentReadModelRepository, RecommendationCommentReadService>();
        services.AddScoped<IMealSourceSnapshotQuery, MealSourceSnapshotQuery>();
        return services;
    }
}
