global using FoodDiary.MailRelay.Application.Abstractions;
global using FoodDiary.MailRelay.Application.Common.Result;
global using FoodDiary.MailRelay.Application.DeliveryEvents.Services;
global using FoodDiary.MailRelay.Application.Emails.Models;
global using FoodDiary.MailRelay.Application.Emails.Services;
global using FoodDiary.MailRelay.Application.Queue.Models;
global using FoodDiary.MailRelay.Application.Telemetry;
global using FoodDiary.MailRelay.Domain.DeliveryEvents;
global using FoodDiary.MailRelay.Domain.Emails;
