namespace FoodDiary.Development.Mcp.Diagnostics;

public sealed record ServerStatus(
    string Version,
    ServerRuntimeIdentity RuntimeIdentity,
    string RepositoryRoot,
    string GitHead,
    bool RunningCodeMatchesRepositoryHead,
    bool WorktreeDirty,
    string WorktreeFingerprint,
    bool IndexesMatchWorktree,
    bool RunningCodeIncludesWorktreeChanges,
    IReadOnlyList<string> SourceChangedPaths,
    IReadOnlyList<string> DerivedWikiPaths,
    IReadOnlyList<string> ReviewMetadataPaths,
    bool WikiAvailable,
    bool IndexFilesPresent,
    string DeepFreshness,
    string? LastVerifiedCommit,
    string? IndexFingerprint,
    string IndexStatusCode,
    string IndexCheckSummary,
    IReadOnlyList<WikiIndexStatus> Indexes,
    DateTimeOffset CheckedAtUtc,
    bool ReadOnly = true);
