<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Domain.Tests</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Domain.Primitives\FoodDiary.Domain.Primitives.csproj" />
    <ProjectReference Include="../../Domain/FoodDiary.Modules.Recipes.Domain.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Products/Domain.Contracts/FoodDiary.Modules.Products.Domain.Contracts.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
  </ItemGroup>
</Project>
