namespace FoodDiary.Modules.Fasting.Application.Abstractions.Common;

public interface IFastingCheckInRepository : IFastingCheckInReadRepository, IFastingCheckInReadModelRepository, IFastingCheckInWriteRepository;
