namespace FoodDiary.Modules.Fasting.Application.Abstractions.Common;

public interface IFastingOccurrenceRepository : IFastingOccurrenceReadRepository, IFastingOccurrenceReadModelRepository, IFastingOccurrenceWriteRepository;
