<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Modules.Images.Infrastructure</RootNamespace><NoWarn>$(NoWarn);IDE0130</NoWarn></PropertyGroup>
  <ItemGroup><Compile Remove="Model/**/*.cs" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Integrations.Http/FoodDiary.Integrations.Http.csproj" />
    <ProjectReference Include="..\Application\FoodDiary.Application.Images.csproj" />
    <ProjectReference Include="..\..\..\FoodDiary.Infrastructure\FoodDiary.Infrastructure.csproj" />
    <ProjectReference Include="Model\FoodDiary.Modules.Images.PersistenceModel.csproj" />
    <ProjectReference Include="../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../Application/Abstractions/FoodDiary.Modules.Images.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Outbox.Abstractions\FoodDiary.Outbox.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Outbox.Management.Contracts\FoodDiary.Outbox.Management.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore" /><PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" /><PackageReference Include="Microsoft.Extensions.Logging.Abstractions" /></ItemGroup>
</Project>
