<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FoodDiary.Persistence.Runtime/FoodDiary.Persistence.Runtime.csproj" />
    <ProjectReference Include="../FoodDiary.Audit.Contracts/FoodDiary.Audit.Contracts.csproj" />
    <ProjectReference Include="../FoodDiary.Audit.PersistenceModel/FoodDiary.Audit.PersistenceModel.csproj" />
    <ProjectReference Include="../../Modules/Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>

</Project>
