export const AUTH_PASSWORD_MIN_LENGTH = 6;
export const AUTH_PASSWORD_RESET_COOLDOWN_SECONDS_DEFAULT = 60;
export const AUTH_EMAIL_RESEND_COOLDOWN_SECONDS_DEFAULT = 60;
export const AUTH_LOGIN_AUTOFILL_FIELD_COUNT = 2;
const AUTH_LOGIN_AUTOFILL_CHECK_DELAY_SHORT_MS = 100;
const AUTH_LOGIN_AUTOFILL_CHECK_DELAY_MEDIUM_MS = 300;
const AUTH_LOGIN_AUTOFILL_CHECK_DELAY_LONG_MS = 700;
const AUTH_LOGIN_AUTOFILL_CHECK_DELAY_EXTENDED_MS = 1_500;
const AUTH_LOGIN_AUTOFILL_CHECK_DELAY_SLOW_MS = 3_000;
const AUTH_LOGIN_AUTOFILL_CHECK_DELAY_FINAL_MS = 5_000;

export const AUTH_LOGIN_AUTOFILL_CHECK_DELAYS_MS_DEFAULT = [
    AUTH_LOGIN_AUTOFILL_CHECK_DELAY_SHORT_MS,
    AUTH_LOGIN_AUTOFILL_CHECK_DELAY_MEDIUM_MS,
    AUTH_LOGIN_AUTOFILL_CHECK_DELAY_LONG_MS,
    AUTH_LOGIN_AUTOFILL_CHECK_DELAY_EXTENDED_MS,
    AUTH_LOGIN_AUTOFILL_CHECK_DELAY_SLOW_MS,
    AUTH_LOGIN_AUTOFILL_CHECK_DELAY_FINAL_MS,
] as const;
