namespace FoodDiary.Application.Abstractions.ContentReports.Common;

public interface IContentReportRepository : IContentReportReadRepository, IContentReportReadModelRepository, IContentReportWriteRepository;