namespace FoodDiary.Application.Abstractions.Export.Common;

public interface IDiaryPdfReportTextProvider {
    DiaryPdfReportTexts GetTexts(string? locale);
}

public sealed record DiaryPdfReportTexts(
    string CultureName,
    string ReportTitle,
    string PeriodLabel,
    string MealsCountLabel,
    string PeriodSummaryTitle,
    string TotalCaloriesTitle,
    string KcalUnit,
    string AveragePerDayTitle,
    string TotalForPeriodTitle,
    string ProteinsTitle,
    string FatsTitle,
    string CarbsTitle,
    string FiberTitle,
    string GramsUnit,
    string GramsProteinsLabel,
    string GramsFatsLabel,
    string GramsCarbsLabel,
    string GramsFiberLabel,
    string CaloriesByDayTitle,
    string NutrientsByDayTitle,
    string MealsTitle,
    string NoMealsMessage,
    string DateColumn,
    string TypeColumn,
    string ItemsColumn,
    string AmountColumn,
    string KcalColumn,
    string ProteinsColumnShort,
    string FatsColumnShort,
    string CarbsColumnShort,
    string FiberColumnShort,
    string SatietyColumn,
    string CommentColumn,
    string BeforeLabel,
    string AfterLabel,
    string OtherMealType,
    string BreakfastMealType,
    string LunchMealType,
    string DinnerMealType,
    string SnackMealType,
    string ItemsPrefix,
    string ItemsNotSpecified,
    string MoreItemsSuffix,
    string RecipeFallback,
    string ProductFallback,
    string ServingUnit,
    string GeneratedByPrefix);
