export const PROTEIN_CALORIES_PER_GRAM = 4;
export const FAT_CALORIES_PER_GRAM = 9;
export const CARB_CALORIES_PER_GRAM = 4;
export const ALCOHOL_CALORIES_PER_GRAM = 7;
export const DEFAULT_CALORIE_MISMATCH_THRESHOLD = 0.2;
export const DEFAULT_NUTRITION_BASE_AMOUNT = 100;
export const PERCENT_MULTIPLIER = 100;
export const NUTRIENT_ROUNDING_FACTOR = 100;
