const HYDRATION_CARD_SMALL_ADD_AMOUNT_ML = 150;
const HYDRATION_CARD_MEDIUM_ADD_AMOUNT_ML = 250;
const HYDRATION_CARD_LARGE_ADD_AMOUNT_ML = 350;

export const HYDRATION_CARD_ADD_AMOUNTS_ML = [
    HYDRATION_CARD_SMALL_ADD_AMOUNT_ML,
    HYDRATION_CARD_MEDIUM_ADD_AMOUNT_ML,
    HYDRATION_CARD_LARGE_ADD_AMOUNT_ML,
] as const;
export const HYDRATION_CARD_PRIMARY_ADD_AMOUNT_ML = HYDRATION_CARD_MEDIUM_ADD_AMOUNT_ML;
export const HYDRATION_CARD_MAX_PERCENT = 200;
