<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>FoodDiary.Infrastructure.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\Infrastructure\FoodDiary.Modules.Gamification.Infrastructure.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Outbox.Abstractions\FoodDiary.Outbox.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Outbox.Management.Contracts\FoodDiary.Outbox.Management.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NSubstitute" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
