type PublicSeoLandingRouteDefinition = {
    path: string;
    titleKey: string;
    descriptionKey: string;
    baseKey: string;
    featureKeys: readonly string[];
    stepKeys: readonly string[];
    faqKeys: readonly string[];
    relatedPaths: readonly string[];
};

export const PUBLIC_SEO_LANDING_ROUTES = [
    {
        path: 'food-diary',
        titleKey: 'SEO.FOOD_DIARY_PAGE',
        descriptionKey: 'SEO.FOOD_DIARY_PAGE_DESCRIPTION',
        baseKey: 'NUTRITION_DIARY_PAGE',
        featureKeys: ['MEAL_LOGGING', 'CALORIES', 'PLANNING', 'PROGRESS', 'DIETOLOGIST', 'FASTING'],
        stepKeys: ['ACCOUNT', 'LOG', 'REVIEW'],
        faqKeys: ['APP_SCOPE', 'CALORIES', 'PLANNING', 'DIETOLOGIST'],
        relatedPaths: [
            'calorie-counter',
            'meal-tracker',
            'macro-tracker',
            'meal-planner',
            'nutrition-planner',
            'weight-loss-app',
            'weight-tracker',
            'body-progress-tracker',
            'intermittent-fasting',
            'dietologist-collaboration',
            'shopping-list-for-meal-planning',
            'nutrition-tracker',
            'food-log',
            'protein-tracker',
            'meal-prep-planner',
        ],
    },
    {
        path: 'calorie-counter',
        titleKey: 'SEO.CALORIE_COUNTER_PAGE',
        descriptionKey: 'SEO.CALORIE_COUNTER_PAGE_DESCRIPTION',
        baseKey: 'CALORIE_COUNTER_PAGE',
        featureKeys: ['DAILY_LOG', 'MACROS', 'GOALS', 'RECIPES', 'PROGRESS', 'COACHING'],
        stepKeys: ['TARGETS', 'LOG', 'REVIEW'],
        faqKeys: ['SCOPE', 'MACROS', 'WEIGHT_LOSS', 'GOALS'],
        relatedPaths: ['macro-tracker', 'weight-loss-app', 'meal-tracker', 'food-diary', 'meal-planner', 'weight-tracker'],
    },
    {
        path: 'meal-planner',
        titleKey: 'SEO.MEAL_PLANNER_PAGE',
        descriptionKey: 'SEO.MEAL_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'MEAL_PLANNER_PAGE',
        featureKeys: ['WEEKLY_PLAN', 'RECIPES', 'SHOPPING', 'ROUTINE', 'ADJUSTMENTS', 'COACHING'],
        stepKeys: ['GOALS', 'BUILD', 'FOLLOW'],
        faqKeys: ['WEEK', 'SHOPPING', 'RECIPES', 'FLEXIBLE'],
        relatedPaths: [
            'nutrition-planner',
            'shopping-list-for-meal-planning',
            'food-diary',
            'calorie-counter',
            'macro-tracker',
            'meal-tracker',
        ],
    },
    {
        path: 'macro-tracker',
        titleKey: 'SEO.MACRO_TRACKER_PAGE',
        descriptionKey: 'SEO.MACRO_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'MACRO_TRACKER_PAGE',
        featureKeys: ['BALANCE', 'MEALS', 'GOALS', 'PATTERNS', 'RECIPES', 'COACHING'],
        stepKeys: ['TARGETS', 'TRACK', 'OPTIMIZE'],
        faqKeys: ['TRACKING', 'CALORIES', 'GOALS', 'BODY_COMPOSITION'],
        relatedPaths: ['calorie-counter', 'weight-loss-app', 'meal-tracker', 'food-diary', 'meal-planner', 'weight-tracker'],
    },
    {
        path: 'intermittent-fasting',
        titleKey: 'SEO.INTERMITTENT_FASTING_PAGE',
        descriptionKey: 'SEO.INTERMITTENT_FASTING_PAGE_DESCRIPTION',
        baseKey: 'INTERMITTENT_FASTING_PAGE',
        featureKeys: ['WINDOWS', 'MEALS', 'CONSISTENCY', 'PROGRESS', 'FLEXIBILITY', 'COACHING'],
        stepKeys: ['SCHEDULE', 'TRACK', 'REVIEW'],
        faqKeys: ['TRACKER', 'CALORIES', 'SCHEDULE', 'RESULTS'],
        relatedPaths: ['weight-tracker', 'body-progress-tracker', 'calorie-counter', 'food-diary', 'weight-loss-app', 'macro-tracker'],
    },
    {
        path: 'meal-tracker',
        titleKey: 'SEO.MEAL_TRACKER_PAGE',
        descriptionKey: 'SEO.MEAL_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'MEAL_TRACKER_PAGE',
        featureKeys: ['QUICK_LOGGING', 'MEAL_HISTORY', 'RECIPES', 'NUTRITION_TOTALS', 'ROUTINE', 'PROGRESS'],
        stepKeys: ['START', 'LOG', 'REVIEW'],
        faqKeys: ['QUICK', 'CALORIES', 'HISTORY', 'RECIPES'],
        relatedPaths: ['food-diary', 'calorie-counter', 'macro-tracker', 'meal-planner', 'nutrition-planner', 'dietologist-collaboration'],
    },
    {
        path: 'weight-loss-app',
        titleKey: 'SEO.WEIGHT_LOSS_APP_PAGE',
        descriptionKey: 'SEO.WEIGHT_LOSS_APP_PAGE_DESCRIPTION',
        baseKey: 'WEIGHT_LOSS_APP_PAGE',
        featureKeys: ['GOALS', 'CALORIES', 'MEALS', 'BODY_METRICS', 'WEEKLY_REVIEW', 'COACHING'],
        stepKeys: ['SETUP', 'FOLLOW', 'ADJUST'],
        faqKeys: ['WEIGHT_LOSS', 'GOALS', 'BODY', 'COACHING'],
        relatedPaths: [
            'calorie-counter',
            'macro-tracker',
            'meal-tracker',
            'weight-tracker',
            'body-progress-tracker',
            'dietologist-collaboration',
        ],
    },
    {
        path: 'dietologist-collaboration',
        titleKey: 'SEO.DIETOLOGIST_COLLABORATION_PAGE',
        descriptionKey: 'SEO.DIETOLOGIST_COLLABORATION_PAGE_DESCRIPTION',
        baseKey: 'DIETOLOGIST_COLLABORATION_PAGE',
        featureKeys: ['INVITES', 'VISIBILITY', 'MEALS', 'PROGRESS', 'PLANS', 'WORKFLOW'],
        stepKeys: ['INVITE', 'SHARE', 'REVIEW'],
        faqKeys: ['INVITE', 'PRIVACY', 'SHARING', 'PLANS'],
        relatedPaths: ['food-diary', 'nutrition-planner', 'weight-loss-app', 'meal-planner', 'calorie-counter', 'meal-tracker'],
    },
    {
        path: 'nutrition-planner',
        titleKey: 'SEO.NUTRITION_PLANNER_PAGE',
        descriptionKey: 'SEO.NUTRITION_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'NUTRITION_PLANNER_PAGE',
        featureKeys: ['GOALS', 'MEAL_PLANS', 'SHOPPING', 'RECIPES', 'REVIEW', 'COACHING'],
        stepKeys: ['DEFINE', 'PLAN', 'REFINE'],
        faqKeys: ['PLANNER', 'GOALS', 'SHOPPING', 'ROUTINE'],
        relatedPaths: [
            'meal-planner',
            'shopping-list-for-meal-planning',
            'food-diary',
            'calorie-counter',
            'macro-tracker',
            'dietologist-collaboration',
        ],
    },
    {
        path: 'weight-tracker',
        titleKey: 'SEO.WEIGHT_TRACKER_PAGE',
        descriptionKey: 'SEO.WEIGHT_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'WEIGHT_TRACKER_PAGE',
        featureKeys: ['WEIGHT_HISTORY', 'PATTERNS', 'MEALS', 'GOALS', 'CHECK_INS', 'COACHING'],
        stepKeys: ['BASELINE', 'TRACK', 'REVIEW'],
        faqKeys: ['TRACKER', 'PROGRESS', 'MEALS', 'GOALS'],
        relatedPaths: ['weight-loss-app', 'body-progress-tracker', 'food-diary', 'calorie-counter', 'meal-tracker', 'intermittent-fasting'],
    },
    {
        path: 'body-progress-tracker',
        titleKey: 'SEO.BODY_PROGRESS_TRACKER_PAGE',
        descriptionKey: 'SEO.BODY_PROGRESS_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'BODY_PROGRESS_TRACKER_PAGE',
        featureKeys: ['METRICS', 'WAIST', 'WEIGHT', 'TRENDS', 'CHECK_INS', 'ROUTINE'],
        stepKeys: ['STARTING_POINT', 'LOG', 'COMPARE'],
        faqKeys: ['METRICS', 'WAIST', 'WEIGHT', 'TRENDS'],
        relatedPaths: ['weight-tracker', 'weight-loss-app', 'food-diary', 'macro-tracker', 'intermittent-fasting', 'calorie-counter'],
    },
    {
        path: 'shopping-list-for-meal-planning',
        titleKey: 'SEO.SHOPPING_LIST_MEAL_PLANNER_PAGE',
        descriptionKey: 'SEO.SHOPPING_LIST_MEAL_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'SHOPPING_LIST_MEAL_PLANNER_PAGE',
        featureKeys: ['PLANS', 'GROCERIES', 'RECIPES', 'REPEATABLE', 'ORGANIZED', 'WEEKLY_FLOW'],
        stepKeys: ['BUILD', 'EXPORT', 'FOLLOW'],
        faqKeys: ['SHOPPING', 'RECIPES', 'WEEK', 'FLOW'],
        relatedPaths: ['meal-planner', 'nutrition-planner', 'food-diary', 'meal-tracker', 'calorie-counter', 'dietologist-collaboration'],
    },
    {
        path: 'nutrition-tracker',
        titleKey: 'SEO.NUTRITION_TRACKER_PAGE',
        descriptionKey: 'SEO.NUTRITION_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'NUTRITION_TRACKER_PAGE',
        featureKeys: ['MEALS', 'CALORIES', 'MACROS', 'GOALS', 'PROGRESS', 'PLANNING'],
        stepKeys: ['START', 'TRACK', 'REVIEW'],
        faqKeys: ['TRACKER', 'CALORIES', 'MACROS', 'PLANNING'],
        relatedPaths: ['food-diary', 'calorie-counter', 'macro-tracker', 'nutrition-planner', 'meal-tracker', 'weight-tracker'],
    },
    {
        path: 'food-log',
        titleKey: 'SEO.FOOD_LOG_PAGE',
        descriptionKey: 'SEO.FOOD_LOG_PAGE_DESCRIPTION',
        baseKey: 'FOOD_LOG_PAGE',
        featureKeys: ['QUICK_ENTRIES', 'MEAL_HISTORY', 'NOTES', 'RECIPES', 'TOTALS', 'PROGRESS'],
        stepKeys: ['WRITE', 'REUSE', 'UNDERSTAND'],
        faqKeys: ['LOG', 'DIARY', 'CALORIES', 'HISTORY'],
        relatedPaths: ['food-diary', 'meal-tracker', 'calorie-counter', 'nutrition-tracker', 'macro-tracker', 'dietologist-collaboration'],
    },
    {
        path: 'protein-tracker',
        titleKey: 'SEO.PROTEIN_TRACKER_PAGE',
        descriptionKey: 'SEO.PROTEIN_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'PROTEIN_TRACKER_PAGE',
        featureKeys: ['PROTEIN_TOTALS', 'MEALS', 'GOALS', 'RECIPES', 'TRENDS', 'MACROS'],
        stepKeys: ['SET_TARGET', 'LOG_MEALS', 'REVIEW'],
        faqKeys: ['PROTEIN', 'MACROS', 'CALORIES', 'RECIPES'],
        relatedPaths: ['macro-tracker', 'calorie-counter', 'meal-tracker', 'food-diary', 'nutrition-tracker', 'weight-loss-app'],
    },
    {
        path: 'meal-prep-planner',
        titleKey: 'SEO.MEAL_PREP_PLANNER_PAGE',
        descriptionKey: 'SEO.MEAL_PREP_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'MEAL_PREP_PLANNER_PAGE',
        featureKeys: ['WEEKLY_PREP', 'RECIPES', 'SHOPPING', 'REPEAT_MEALS', 'GOALS', 'ADJUSTMENTS'],
        stepKeys: ['CHOOSE', 'PREPARE', 'FOLLOW'],
        faqKeys: ['PREP', 'SHOPPING', 'RECIPES', 'FLEXIBLE'],
        relatedPaths: [
            'meal-planner',
            'shopping-list-for-meal-planning',
            'nutrition-planner',
            'food-diary',
            'meal-tracker',
            'calorie-counter',
        ],
    },
] as const satisfies readonly PublicSeoLandingRouteDefinition[];

export type PublicSeoLandingRouteConfig = (typeof PUBLIC_SEO_LANDING_ROUTES)[number];
export type SeoPageSlug = PublicSeoLandingRouteConfig['path'];

export const PUBLIC_SEO_PATHS = new Set<string>(PUBLIC_SEO_LANDING_ROUTES.map(route => `/${route.path}`));

export const SEO_PAGE_LABEL_KEYS: Readonly<Record<string, string>> = Object.fromEntries(
    PUBLIC_SEO_LANDING_ROUTES.map(route => [route.path, route.titleKey]),
);
