namespace FoodDiary.Modules.Favorites.Application.Abstractions.FavoriteRecipes.Common;

public interface IFavoriteRecipeRepository : IFavoriteRecipeReadRepository, IFavoriteRecipeReadModelRepository, IFavoriteRecipeWriteRepository;
