<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>FoodDiary.Application.Admin</AssemblyName><RootNamespace>FoodDiary.Application.Admin</RootNamespace></PropertyGroup>
  <ItemGroup><Compile Remove="Abstractions/**/*.cs" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Abstractions/FoodDiary.Modules.Admin.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../FoodDiary.Application.Abstractions/FoodDiary.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Ai/Application/FoodDiary.Modules.Ai.Application.csproj" />
    <ProjectReference Include="../../ContentReports/Contracts/FoodDiary.Modules.ContentReports.Contracts.csproj" />
    <ProjectReference Include="../../Gamification/Application/FoodDiary.Modules.Gamification.Application.csproj" />
    <ProjectReference Include="../../Lessons/Contracts/FoodDiary.Modules.Lessons.Contracts.csproj" />
    <ProjectReference Include="../../../FoodDiary.Domain/FoodDiary.Domain.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Mediator/FoodDiary.Mediator.csproj" />
    <ProjectReference Include="../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
