<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.Billing.Application.Abstractions</AssemblyName>
    <RootNamespace>FoodDiary.Application.Abstractions.Billing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\FoodDiary.Modules.Billing.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Results\FoodDiary.Results.csproj" />
  </ItemGroup>
</Project>
