namespace FoodDiary.Modules.RecipeCommunity.Application.Abstractions.RecipeComments.Common;

public interface IRecipeCommentRepository : IRecipeCommentReadRepository, IRecipeCommentReadModelRepository, IRecipeCommentWriteRepository;
