<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FoodDiary.Application.Tests</RootNamespace>
    <AssemblyName>FoodDiary.Application.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="FoodDiary.Application.Tests.Support" />
    <Using Include="NSubstitute" />
    <Using Include="Xunit" />
    <ProjectReference Include="../../../Favorites/Domain.Contracts/FoodDiary.Modules.Favorites.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Meals/Service.Contracts/FoodDiary.Modules.Meals.Service.Contracts.csproj" />
    <ProjectReference Include="../../Application/FoodDiary.Modules.Dashboard.Application.csproj" />
    <ProjectReference Include="../../../Statistics/Application/FoodDiary.Modules.Statistics.Application.csproj" />
    <ProjectReference Include="../../../BodyMetrics/Application/FoodDiary.Application.BodyMetrics.csproj" />
    <ProjectReference Include="../../../Hydration/Application/FoodDiary.Modules.Hydration.Application.csproj" />
    <ProjectReference Include="../../../Exercises/Application/FoodDiary.Application.Exercises.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../../Contracts/FoodDiary.Modules.Dashboard.Contracts.csproj" />
    <ProjectReference Include="../../../Identity/Application/Abstractions/FoodDiary.Modules.Identity.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Hydration/Application/Abstractions/FoodDiary.Modules.Hydration.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../BodyMetrics/Application/Abstractions/FoodDiary.Modules.BodyMetrics.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Exercises/Application/Abstractions/FoodDiary.Modules.Exercises.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
