<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.Hydration.Infrastructure</AssemblyName>
    <RootNamespace>FoodDiary.Modules.Hydration.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Model/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoodDiary.Modules.Hydration.csproj" />
    <ProjectReference Include="..\..\..\FoodDiary.Infrastructure\FoodDiary.Infrastructure.csproj" />
    <ProjectReference Include="Model\FoodDiary.Modules.Hydration.PersistenceModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
