<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/FoodDiary.Modules.Marketing.Application.csproj" />
    <ProjectReference Include="../Application.Abstractions/FoodDiary.Modules.Marketing.Application.Abstractions.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Marketing.Domain.csproj" />
    <ProjectReference Include="../../../FoodDiary.Presentation.Api/FoodDiary.Presentation.Api.csproj" />
  </ItemGroup>

</Project>
