namespace FoodDiary.Application.Abstractions.Admin.Common;

public interface IAdminImpersonationSessionRepository : IAdminImpersonationSessionReadRepository, IAdminImpersonationSessionWriteRepository;
