namespace FoodDiary.Modules.Admin.Application.Abstractions.Common;

public interface IAdminImpersonationSessionRepository : IAdminImpersonationSessionReadRepository, IAdminImpersonationSessionWriteRepository;
