<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FoodDiary.Application.Abstractions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../FoodDiary.Domain/FoodDiary.Domain.csproj" />
    <ProjectReference Include="../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="..\Domain.Contracts\FoodDiary.Modules.Recipes.Domain.Contracts.csproj" />
    <ProjectReference Include="..\..\Images\Contracts\FoodDiary.Modules.Images.Contracts.csproj" />
  </ItemGroup>
</Project>
