export const USDA_NUTRIENT_IDS = {
    vitaminA: 1106,
    thiamin: 1165,
    riboflavin: 1166,
    niacin: 1167,
    pantothenicAcid: 1170,
    vitaminB6: 1175,
    folate: 1177,
    vitaminB12: 1178,
    vitaminC: 1162,
    vitaminD: 1110,
    vitaminE: 1109,
    vitaminK: 1185,
    calcium: 1087,
    iron: 1089,
    magnesium: 1090,
    phosphorus: 1091,
    potassium: 1092,
    sodium: 1093,
    zinc: 1095,
    copper: 1098,
    manganese: 1101,
    selenium: 1103,
} as const;

export const DAILY_MICRONUTRIENT_IDS = [
    USDA_NUTRIENT_IDS.vitaminA,
    USDA_NUTRIENT_IDS.vitaminC,
    USDA_NUTRIENT_IDS.vitaminD,
    USDA_NUTRIENT_IDS.vitaminE,
    USDA_NUTRIENT_IDS.vitaminB6,
    USDA_NUTRIENT_IDS.vitaminB12,
    USDA_NUTRIENT_IDS.calcium,
    USDA_NUTRIENT_IDS.iron,
    USDA_NUTRIENT_IDS.magnesium,
    USDA_NUTRIENT_IDS.potassium,
    USDA_NUTRIENT_IDS.zinc,
    USDA_NUTRIENT_IDS.selenium,
] as const;

export const VITAMIN_NUTRIENT_IDS = [
    USDA_NUTRIENT_IDS.vitaminA,
    USDA_NUTRIENT_IDS.thiamin,
    USDA_NUTRIENT_IDS.riboflavin,
    USDA_NUTRIENT_IDS.niacin,
    USDA_NUTRIENT_IDS.pantothenicAcid,
    USDA_NUTRIENT_IDS.vitaminB6,
    USDA_NUTRIENT_IDS.folate,
    USDA_NUTRIENT_IDS.vitaminB12,
    USDA_NUTRIENT_IDS.vitaminC,
    USDA_NUTRIENT_IDS.vitaminD,
    USDA_NUTRIENT_IDS.vitaminE,
    USDA_NUTRIENT_IDS.vitaminK,
] as const;

export const MINERAL_NUTRIENT_IDS = [
    USDA_NUTRIENT_IDS.calcium,
    USDA_NUTRIENT_IDS.iron,
    USDA_NUTRIENT_IDS.magnesium,
    USDA_NUTRIENT_IDS.phosphorus,
    USDA_NUTRIENT_IDS.potassium,
    USDA_NUTRIENT_IDS.sodium,
    USDA_NUTRIENT_IDS.zinc,
    USDA_NUTRIENT_IDS.copper,
    USDA_NUTRIENT_IDS.manganese,
    USDA_NUTRIENT_IDS.selenium,
] as const;
