[nginx-fooddiary-scanners]
enabled = true
filter = nginx-fooddiary-scanners
logpath = /var/log/nginx/fooddiary.access.log
          /var/log/nginx/fooddiary.admin.access.log
maxretry = 5
findtime = 10m
bantime = 1h
action = iptables-multiport[name=nginx-fooddiary-scanners, port="http,https", protocol=tcp]
