namespace FoodDiary.Application.Abstractions.Notifications.Common;

public interface INotificationRepository : INotificationReadRepository, INotificationReadModelRepository, INotificationWriteRepository;