namespace FoodDiary.Application.Abstractions.Notifications.Common;

public interface IWebPushSubscriptionRepository : IWebPushSubscriptionReadRepository, IWebPushSubscriptionReadModelRepository, IWebPushSubscriptionWriteRepository;