namespace FoodDiary.Modules.Dietologist.Application.Abstractions.Common;

public interface IRecommendationBulkDispatchRepository
    : IRecommendationBulkDispatchLookupRepository, IRecommendationBulkDispatchWriteRepository;
