namespace FoodDiary.Application.Abstractions.FavoriteRecipes.Common;

public interface IFavoriteRecipeRepository : IFavoriteRecipeReadRepository, IFavoriteRecipeReadModelRepository, IFavoriteRecipeWriteRepository;
