<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FoodDiary.Application.Tests.Support" />
    <Using Include="NSubstitute" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\tests\FoodDiary.Application.Tests\Support\ResultAssert.cs" Link="Support\ResultAssert.cs" />
    <ProjectReference Include="../../Application.Abstractions/FoodDiary.Modules.Billing.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Application/FoodDiary.Modules.Billing.Application.csproj" />
    <ProjectReference Include="../../Contracts/FoodDiary.Modules.Billing.Contracts.csproj" />
    <ProjectReference Include="../../Domain.Contracts/FoodDiary.Modules.Billing.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Marketing/Application.Abstractions/FoodDiary.Modules.Marketing.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Marketing/Contracts/FoodDiary.Modules.Marketing.Contracts.csproj" />
    <ProjectReference Include="../../../Users/Application.Abstractions/FoodDiary.Modules.Users.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Users/Application/FoodDiary.Modules.Users.Application.csproj" />
    <ProjectReference Include="../../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../../../../Shared/FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../../../Shared/FoodDiary.Authentication.Contracts/FoodDiary.Authentication.Contracts.csproj" />
    <ProjectReference Include="../../../../Shared/FoodDiary.Mediator/FoodDiary.Mediator.csproj" />
    <ProjectReference Include="../../../../Tooling/FoodDiary.Testing/FoodDiary.Testing.csproj" />
  </ItemGroup>

</Project>
