FROM postgres:17-alpine@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73

RUN apk add --no-cache openssl=3.5.7-r0

COPY scripts/initialize-mail-inbox-postgres-tls.sh /scripts/initialize-mail-inbox-postgres-tls.sh

ENTRYPOINT ["/bin/sh", "/scripts/initialize-mail-inbox-postgres-tls.sh"]
