<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FoodDiary.Application.Gamification</AssemblyName>
    <RootNamespace>FoodDiary.Application.Gamification</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Abstractions/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Gamification.Contracts.csproj" />
    <ProjectReference Include="Abstractions\FoodDiary.Modules.Gamification.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../Meals/Contracts/FoodDiary.Modules.Meals.Contracts.csproj" />
    <ProjectReference Include="..\Domain\FoodDiary.Modules.Gamification.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Mediator\FoodDiary.Mediator.csproj" />
    <ProjectReference Include="../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
