using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FoodDiary.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class UseStronglyTypedMealIds : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_MealItems_Meals_MealId",
                table: "MealItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_MealItems",
                table: "MealItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Meals",
                table: "Meals");

            migrationBuilder.DropIndex(
                name: "IX_MealItems_MealId",
                table: "MealItems");

            migrationBuilder.Sql("""
ALTER TABLE "Meals" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE "Meals" ALTER COLUMN "Id" TYPE uuid USING (md5("Id"::text || 'Meal')::uuid);
""");

            migrationBuilder.Sql("""
ALTER TABLE "MealItems" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
ALTER TABLE "MealItems" ALTER COLUMN "Id" TYPE uuid USING (md5("Id"::text || 'MealItem')::uuid);
ALTER TABLE "MealItems" ALTER COLUMN "MealId" TYPE uuid USING (md5("MealId"::text || 'Meal')::uuid);
""");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Meals",
                table: "Meals",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_MealItems",
                table: "MealItems",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_MealItems_MealId",
                table: "MealItems",
                column: "MealId");

            migrationBuilder.AddForeignKey(
                name: "FK_MealItems_Meals_MealId",
                table: "MealItems",
                column: "MealId",
                principalTable: "Meals",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_MealItems_Meals_MealId",
                table: "MealItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_MealItems",
                table: "MealItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Meals",
                table: "Meals");

            migrationBuilder.DropIndex(
                name: "IX_MealItems_MealId",
                table: "MealItems");

            migrationBuilder.AddColumn<int>(
                name: "IdInt",
                table: "Meals",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "IdInt",
                table: "MealItems",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "MealIdInt",
                table: "MealItems",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.Sql("""
WITH ordered_meals AS (
    SELECT "Id", row_number() OVER (ORDER BY "CreatedOnUtc", "Id") AS rn
    FROM "Meals"
)
UPDATE "Meals" m
SET "IdInt" = om.rn
FROM ordered_meals om
WHERE m."Id" = om."Id";
""");

            migrationBuilder.Sql("""
WITH ordered_items AS (
    SELECT "Id", row_number() OVER (ORDER BY "CreatedOnUtc", "Id") AS rn
    FROM "MealItems"
)
UPDATE "MealItems" mi
SET "IdInt" = oi.rn
FROM ordered_items oi
WHERE mi."Id" = oi."Id";
""");

            migrationBuilder.Sql("""
UPDATE "MealItems" mi
SET "MealIdInt" = m."IdInt"
FROM "Meals" m
WHERE mi."MealId" = m."Id";
""");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "Meals");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "MealItems");

            migrationBuilder.DropColumn(
                name: "MealId",
                table: "MealItems");

            migrationBuilder.RenameColumn(
                name: "IdInt",
                table: "Meals",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "IdInt",
                table: "MealItems",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "MealIdInt",
                table: "MealItems",
                newName: "MealId");

            migrationBuilder.Sql("""
ALTER TABLE "Meals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "MealItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
""");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Meals",
                table: "Meals",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_MealItems",
                table: "MealItems",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_MealItems_MealId",
                table: "MealItems",
                column: "MealId");

            migrationBuilder.AddForeignKey(
                name: "FK_MealItems_Meals_MealId",
                table: "MealItems",
                column: "MealId",
                principalTable: "Meals",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
