// <auto-generated />
using FoodDiary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FoodDiary.Infrastructure.Migrations
{
    [DbContext(typeof(FoodDiaryDbContext))]
    [Migration("20251201120100_AddProductDefaultPortionAmount")]
    partial class AddProductDefaultPortionAmount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Delegate to the current snapshot to keep the model in sync
            var accessor = new SnapshotAccessor();
            accessor.Build(modelBuilder);
        }

        private sealed class SnapshotAccessor : FoodDiaryDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);
        }
    }
}
