// <auto-generated />
using System;
using FoodDiary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDiary.Infrastructure.Migrations
{
    [DbContext(typeof(FoodDiaryDbContext))]
    [Migration("20251117172742_AddDesiredWaistToUsers")]
    partial class AddDesiredWaistToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodDiary.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsNutritionAutoCalculated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("ManualCalories")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualCarbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualFats")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualFiber")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualProteins")
                        .HasColumnType("double precision");

                    b.Property<int?>("MealType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostMealSatietyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PreMealSatietyLevel")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalCarbs")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalFats")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalFiber")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalProteins")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.MealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<double>("BaseAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("BaseUnit")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<double>("CaloriesPerBase")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsPerBase")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("FatsPerBase")
                        .HasColumnType("double precision");

                    b.Property<double>("FiberPerBase")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double>("ProteinsPerBase")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<int?>("CookTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsNutritionAutoCalculated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("ManualCalories")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualCarbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualFats")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualFiber")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManualProteins")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PrepTime")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalCarbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalFats")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalFiber")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalProteins")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NestedRecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NestedRecipeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeStepId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Moderate");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CarbTarget")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DailyCalorieTarget")
                        .HasColumnType("double precision");

                    b.Property<double?>("DesiredWaist")
                        .HasColumnType("double precision");

                    b.Property<double?>("DesiredWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("FatTarget")
                        .HasColumnType("double precision");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<double?>("ProteinTarget")
                        .HasColumnType("double precision");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<int?>("StepGoal")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<double?>("WaterGoal")
                        .HasColumnType("double precision");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.WaistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Circumference")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("WaistEntries");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.WeightEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Meal", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.Meal", "Meal")
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDiary.Domain.Entities.Product", "Product")
                        .WithMany("MealItems")
                        .HasForeignKey("ProductId");

                    b.HasOne("FoodDiary.Domain.Entities.Recipe", "Recipe")
                        .WithMany("MealItems")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Meal");

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Product", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.Recipe", "NestedRecipe")
                        .WithMany("NestedRecipeUsages")
                        .HasForeignKey("NestedRecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodDiary.Domain.Entities.Product", "Product")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("ProductId");

                    b.HasOne("FoodDiary.Domain.Entities.RecipeStep", "RecipeStep")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NestedRecipe");

                    b.Navigation("Product");

                    b.Navigation("RecipeStep");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.RecipeStep", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.WaistEntry", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.User", "User")
                        .WithMany("WaistEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.WeightEntry", b =>
                {
                    b.HasOne("FoodDiary.Domain.Entities.User", "User")
                        .WithMany("WeightEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Product", b =>
                {
                    b.Navigation("MealItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("MealItems");

                    b.Navigation("NestedRecipeUsages");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.RecipeStep", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FoodDiary.Domain.Entities.User", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Products");

                    b.Navigation("Recipes");

                    b.Navigation("WaistEntries");

                    b.Navigation("WeightEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
