// <auto-generated />
using System;
using FoodDiary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDiary.Infrastructure.Migrations
{
    [DbContext(typeof(FoodDiaryDbContext))]
    [Migration("20251201120000_AddFiberTargetToUsers")]
    partial class AddFiberTargetToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot is maintained in FoodDiaryDbContextModelSnapshot.
        }
    }
}
