// <auto-generated />
using FoodDiary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FoodDiary.Infrastructure.Migrations;

[DbContext(typeof(FoodDiaryDbContext))]
[Migration("20260524153000_ConfirmSeededAdminEmail")]
partial class ConfirmSeededAdminEmail;
