<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.Favorites.PersistenceModel</AssemblyName>
    <RootNamespace>FoodDiary.Modules.Favorites.Infrastructure.Persistence</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\FoodDiary.Modules.Favorites.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

</Project>
