namespace FoodDiary.Modules.Favorites.Application.Abstractions.FavoriteProducts.Common;

public interface IFavoriteProductRepository : IFavoriteProductReadRepository, IFavoriteProductReadModelRepository, IFavoriteProductWriteRepository;
