<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FoodDiary.Presentation.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/Abstractions/FoodDiary.Modules.WeeklyGoals.Application.Abstractions.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.WeeklyGoals.Application.csproj" />
    <ProjectReference Include="../Contracts/FoodDiary.Modules.WeeklyGoals.Contracts.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.WeeklyGoals.Domain.csproj" />
    <ProjectReference Include="../../../FoodDiary.Presentation.Api/FoodDiary.Presentation.Api.csproj" />
  </ItemGroup>

</Project>
