<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Application/Abstractions/FoodDiary.Modules.Export.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Meals/Contracts/FoodDiary.Modules.Meals.Contracts.csproj" />
    <ProjectReference Include="../../Meals/Domain/FoodDiary.Modules.Meals.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>
</Project>
