<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Application.Abstractions</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Domain/FoodDiary.Modules.Meals.Domain.csproj" />
    <ProjectReference Include="../../Contracts/FoodDiary.Modules.Meals.Contracts.csproj" />
  </ItemGroup>
</Project>
