<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Application.Abstractions</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Shared/FoodDiary.Results/FoodDiary.Results.csproj" />
    <ProjectReference Include="../../Domain/FoodDiary.Modules.Meals.Domain.csproj" />
    <ProjectReference Include="../../Contracts/FoodDiary.Modules.Meals.Contracts.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>
</Project>
