FROM postgres:18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873

RUN apk add --no-cache openssl=3.5.8-r0

COPY scripts/initialize-mail-inbox-postgres-tls.sh /scripts/initialize-mail-inbox-postgres-tls.sh

ENTRYPOINT ["/bin/sh", "/scripts/initialize-mail-inbox-postgres-tls.sh"]
