namespace FoodDiary.Modules.Wearables.Application.Abstractions.Common;

public interface IWearableSyncRepository : IWearableSyncReadRepository, IWearableSyncReadModelRepository, IWearableSyncWriteRepository;
