import type { Type } from '@angular/core';
import type { Route, Routes } from '@angular/router';

import { authRoutes } from './features/auth/auth.routes';
import { authGuard } from './guards/auth.guard';
import { dietologistGuard } from './guards/dietologist.guard';
import { loggedInGuard } from './guards/logged-in.guard';
import { unsavedChangesGuard } from './guards/unsaved-changes.guard';

type PublicSeoLandingRouteConfig = {
    path: string;
    titleKey: string;
    descriptionKey: string;
    baseKey: string;
    featureKeys: readonly string[];
    stepKeys: readonly string[];
    faqKeys: readonly string[];
    relatedPaths: readonly string[];
};

const publicSeoLanding = ({
    path,
    titleKey,
    descriptionKey,
    baseKey,
    featureKeys,
    stepKeys,
    faqKeys,
    relatedPaths,
}: PublicSeoLandingRouteConfig): Route => ({
    path,
    loadComponent: async (): Promise<Type<unknown>> =>
        import('./features/public/pages/seo-landing/seo-landing-page.component').then(m => m.SeoLandingPageComponent),
    data: {
        seo: {
            titleKey,
            descriptionKey,
            structuredDataBaseKey: baseKey,
            structuredDataFeatureKeys: featureKeys,
            structuredDataFaqKeys: faqKeys,
        },
        seoPage: {
            baseKey,
            featureKeys,
            stepKeys,
            faqKeys,
            relatedPaths,
        },
    },
});

export const routes: Routes = [
    {
        path: '',
        loadComponent: async () => import('./features/public/pages/landing/main.component').then(m => m.MainComponent),
        canActivate: [loggedInGuard],
        canDeactivate: [unsavedChangesGuard],
        data: { seo: { titleKey: 'SEO.LANDING_TITLE', descriptionKey: 'SEO.LANDING_DESCRIPTION' } },
    },
    publicSeoLanding({
        path: 'food-diary',
        titleKey: 'SEO.FOOD_DIARY_PAGE',
        descriptionKey: 'SEO.FOOD_DIARY_PAGE_DESCRIPTION',
        baseKey: 'NUTRITION_DIARY_PAGE',
        featureKeys: ['MEAL_LOGGING', 'CALORIES', 'PLANNING', 'PROGRESS', 'DIETOLOGIST', 'FASTING'],
        stepKeys: ['ACCOUNT', 'LOG', 'REVIEW'],
        faqKeys: ['APP_SCOPE', 'CALORIES', 'PLANNING', 'DIETOLOGIST'],
        relatedPaths: [
            'calorie-counter',
            'meal-tracker',
            'macro-tracker',
            'meal-planner',
            'nutrition-planner',
            'weight-loss-app',
            'weight-tracker',
            'body-progress-tracker',
            'intermittent-fasting',
            'dietologist-collaboration',
            'shopping-list-for-meal-planning',
            'nutrition-tracker',
            'food-log',
            'protein-tracker',
            'meal-prep-planner',
        ],
    }),
    publicSeoLanding({
        path: 'calorie-counter',
        titleKey: 'SEO.CALORIE_COUNTER_PAGE',
        descriptionKey: 'SEO.CALORIE_COUNTER_PAGE_DESCRIPTION',
        baseKey: 'CALORIE_COUNTER_PAGE',
        featureKeys: ['DAILY_LOG', 'MACROS', 'GOALS', 'RECIPES', 'PROGRESS', 'COACHING'],
        stepKeys: ['TARGETS', 'LOG', 'REVIEW'],
        faqKeys: ['SCOPE', 'MACROS', 'WEIGHT_LOSS', 'GOALS'],
        relatedPaths: ['macro-tracker', 'weight-loss-app', 'meal-tracker', 'food-diary', 'meal-planner', 'weight-tracker'],
    }),
    publicSeoLanding({
        path: 'meal-planner',
        titleKey: 'SEO.MEAL_PLANNER_PAGE',
        descriptionKey: 'SEO.MEAL_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'MEAL_PLANNER_PAGE',
        featureKeys: ['WEEKLY_PLAN', 'RECIPES', 'SHOPPING', 'ROUTINE', 'ADJUSTMENTS', 'COACHING'],
        stepKeys: ['GOALS', 'BUILD', 'FOLLOW'],
        faqKeys: ['WEEK', 'SHOPPING', 'RECIPES', 'FLEXIBLE'],
        relatedPaths: [
            'nutrition-planner',
            'shopping-list-for-meal-planning',
            'food-diary',
            'calorie-counter',
            'macro-tracker',
            'meal-tracker',
        ],
    }),
    publicSeoLanding({
        path: 'macro-tracker',
        titleKey: 'SEO.MACRO_TRACKER_PAGE',
        descriptionKey: 'SEO.MACRO_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'MACRO_TRACKER_PAGE',
        featureKeys: ['BALANCE', 'MEALS', 'GOALS', 'PATTERNS', 'RECIPES', 'COACHING'],
        stepKeys: ['TARGETS', 'TRACK', 'OPTIMIZE'],
        faqKeys: ['TRACKING', 'CALORIES', 'GOALS', 'BODY_COMPOSITION'],
        relatedPaths: ['calorie-counter', 'weight-loss-app', 'meal-tracker', 'food-diary', 'meal-planner', 'weight-tracker'],
    }),
    publicSeoLanding({
        path: 'intermittent-fasting',
        titleKey: 'SEO.INTERMITTENT_FASTING_PAGE',
        descriptionKey: 'SEO.INTERMITTENT_FASTING_PAGE_DESCRIPTION',
        baseKey: 'INTERMITTENT_FASTING_PAGE',
        featureKeys: ['WINDOWS', 'MEALS', 'CONSISTENCY', 'PROGRESS', 'FLEXIBILITY', 'COACHING'],
        stepKeys: ['SCHEDULE', 'TRACK', 'REVIEW'],
        faqKeys: ['TRACKER', 'CALORIES', 'SCHEDULE', 'RESULTS'],
        relatedPaths: ['weight-tracker', 'body-progress-tracker', 'calorie-counter', 'food-diary', 'weight-loss-app', 'macro-tracker'],
    }),
    publicSeoLanding({
        path: 'meal-tracker',
        titleKey: 'SEO.MEAL_TRACKER_PAGE',
        descriptionKey: 'SEO.MEAL_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'MEAL_TRACKER_PAGE',
        featureKeys: ['QUICK_LOGGING', 'MEAL_HISTORY', 'RECIPES', 'NUTRITION_TOTALS', 'ROUTINE', 'PROGRESS'],
        stepKeys: ['START', 'LOG', 'REVIEW'],
        faqKeys: ['QUICK', 'CALORIES', 'HISTORY', 'RECIPES'],
        relatedPaths: ['food-diary', 'calorie-counter', 'macro-tracker', 'meal-planner', 'nutrition-planner', 'dietologist-collaboration'],
    }),
    publicSeoLanding({
        path: 'weight-loss-app',
        titleKey: 'SEO.WEIGHT_LOSS_APP_PAGE',
        descriptionKey: 'SEO.WEIGHT_LOSS_APP_PAGE_DESCRIPTION',
        baseKey: 'WEIGHT_LOSS_APP_PAGE',
        featureKeys: ['GOALS', 'CALORIES', 'MEALS', 'BODY_METRICS', 'WEEKLY_REVIEW', 'COACHING'],
        stepKeys: ['SETUP', 'FOLLOW', 'ADJUST'],
        faqKeys: ['WEIGHT_LOSS', 'GOALS', 'BODY', 'COACHING'],
        relatedPaths: [
            'calorie-counter',
            'macro-tracker',
            'meal-tracker',
            'weight-tracker',
            'body-progress-tracker',
            'dietologist-collaboration',
        ],
    }),
    publicSeoLanding({
        path: 'dietologist-collaboration',
        titleKey: 'SEO.DIETOLOGIST_COLLABORATION_PAGE',
        descriptionKey: 'SEO.DIETOLOGIST_COLLABORATION_PAGE_DESCRIPTION',
        baseKey: 'DIETOLOGIST_COLLABORATION_PAGE',
        featureKeys: ['INVITES', 'VISIBILITY', 'MEALS', 'PROGRESS', 'PLANS', 'WORKFLOW'],
        stepKeys: ['INVITE', 'SHARE', 'REVIEW'],
        faqKeys: ['INVITE', 'PRIVACY', 'SHARING', 'PLANS'],
        relatedPaths: ['food-diary', 'nutrition-planner', 'weight-loss-app', 'meal-planner', 'calorie-counter', 'meal-tracker'],
    }),
    publicSeoLanding({
        path: 'nutrition-planner',
        titleKey: 'SEO.NUTRITION_PLANNER_PAGE',
        descriptionKey: 'SEO.NUTRITION_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'NUTRITION_PLANNER_PAGE',
        featureKeys: ['GOALS', 'MEAL_PLANS', 'SHOPPING', 'RECIPES', 'REVIEW', 'COACHING'],
        stepKeys: ['DEFINE', 'PLAN', 'REFINE'],
        faqKeys: ['PLANNER', 'GOALS', 'SHOPPING', 'ROUTINE'],
        relatedPaths: [
            'meal-planner',
            'shopping-list-for-meal-planning',
            'food-diary',
            'calorie-counter',
            'macro-tracker',
            'dietologist-collaboration',
        ],
    }),
    publicSeoLanding({
        path: 'weight-tracker',
        titleKey: 'SEO.WEIGHT_TRACKER_PAGE',
        descriptionKey: 'SEO.WEIGHT_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'WEIGHT_TRACKER_PAGE',
        featureKeys: ['WEIGHT_HISTORY', 'PATTERNS', 'MEALS', 'GOALS', 'CHECK_INS', 'COACHING'],
        stepKeys: ['BASELINE', 'TRACK', 'REVIEW'],
        faqKeys: ['TRACKER', 'PROGRESS', 'MEALS', 'GOALS'],
        relatedPaths: ['weight-loss-app', 'body-progress-tracker', 'food-diary', 'calorie-counter', 'meal-tracker', 'intermittent-fasting'],
    }),
    publicSeoLanding({
        path: 'body-progress-tracker',
        titleKey: 'SEO.BODY_PROGRESS_TRACKER_PAGE',
        descriptionKey: 'SEO.BODY_PROGRESS_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'BODY_PROGRESS_TRACKER_PAGE',
        featureKeys: ['METRICS', 'WAIST', 'WEIGHT', 'TRENDS', 'CHECK_INS', 'ROUTINE'],
        stepKeys: ['STARTING_POINT', 'LOG', 'COMPARE'],
        faqKeys: ['METRICS', 'WAIST', 'WEIGHT', 'TRENDS'],
        relatedPaths: ['weight-tracker', 'weight-loss-app', 'food-diary', 'macro-tracker', 'intermittent-fasting', 'calorie-counter'],
    }),
    publicSeoLanding({
        path: 'shopping-list-for-meal-planning',
        titleKey: 'SEO.SHOPPING_LIST_MEAL_PLANNER_PAGE',
        descriptionKey: 'SEO.SHOPPING_LIST_MEAL_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'SHOPPING_LIST_MEAL_PLANNER_PAGE',
        featureKeys: ['PLANS', 'GROCERIES', 'RECIPES', 'REPEATABLE', 'ORGANIZED', 'WEEKLY_FLOW'],
        stepKeys: ['BUILD', 'EXPORT', 'FOLLOW'],
        faqKeys: ['SHOPPING', 'RECIPES', 'WEEK', 'FLOW'],
        relatedPaths: ['meal-planner', 'nutrition-planner', 'food-diary', 'meal-tracker', 'calorie-counter', 'dietologist-collaboration'],
    }),
    publicSeoLanding({
        path: 'nutrition-tracker',
        titleKey: 'SEO.NUTRITION_TRACKER_PAGE',
        descriptionKey: 'SEO.NUTRITION_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'NUTRITION_TRACKER_PAGE',
        featureKeys: ['MEALS', 'CALORIES', 'MACROS', 'GOALS', 'PROGRESS', 'PLANNING'],
        stepKeys: ['START', 'TRACK', 'REVIEW'],
        faqKeys: ['TRACKER', 'CALORIES', 'MACROS', 'PLANNING'],
        relatedPaths: ['food-diary', 'calorie-counter', 'macro-tracker', 'nutrition-planner', 'meal-tracker', 'weight-tracker'],
    }),
    publicSeoLanding({
        path: 'food-log',
        titleKey: 'SEO.FOOD_LOG_PAGE',
        descriptionKey: 'SEO.FOOD_LOG_PAGE_DESCRIPTION',
        baseKey: 'FOOD_LOG_PAGE',
        featureKeys: ['QUICK_ENTRIES', 'MEAL_HISTORY', 'NOTES', 'RECIPES', 'TOTALS', 'PROGRESS'],
        stepKeys: ['WRITE', 'REUSE', 'UNDERSTAND'],
        faqKeys: ['LOG', 'DIARY', 'CALORIES', 'HISTORY'],
        relatedPaths: ['food-diary', 'meal-tracker', 'calorie-counter', 'nutrition-tracker', 'macro-tracker', 'dietologist-collaboration'],
    }),
    publicSeoLanding({
        path: 'protein-tracker',
        titleKey: 'SEO.PROTEIN_TRACKER_PAGE',
        descriptionKey: 'SEO.PROTEIN_TRACKER_PAGE_DESCRIPTION',
        baseKey: 'PROTEIN_TRACKER_PAGE',
        featureKeys: ['PROTEIN_TOTALS', 'MEALS', 'GOALS', 'RECIPES', 'TRENDS', 'MACROS'],
        stepKeys: ['SET_TARGET', 'LOG_MEALS', 'REVIEW'],
        faqKeys: ['PROTEIN', 'MACROS', 'CALORIES', 'RECIPES'],
        relatedPaths: ['macro-tracker', 'calorie-counter', 'meal-tracker', 'food-diary', 'nutrition-tracker', 'weight-loss-app'],
    }),
    publicSeoLanding({
        path: 'meal-prep-planner',
        titleKey: 'SEO.MEAL_PREP_PLANNER_PAGE',
        descriptionKey: 'SEO.MEAL_PREP_PLANNER_PAGE_DESCRIPTION',
        baseKey: 'MEAL_PREP_PLANNER_PAGE',
        featureKeys: ['WEEKLY_PREP', 'RECIPES', 'SHOPPING', 'REPEAT_MEALS', 'GOALS', 'ADJUSTMENTS'],
        stepKeys: ['CHOOSE', 'PREPARE', 'FOLLOW'],
        faqKeys: ['PREP', 'SHOPPING', 'RECIPES', 'FLEXIBLE'],
        relatedPaths: [
            'meal-planner',
            'shopping-list-for-meal-planning',
            'nutrition-planner',
            'food-diary',
            'meal-tracker',
            'calorie-counter',
        ],
    }),
    ...authRoutes,
    {
        path: 'dashboard',
        canActivate: [authGuard],
        loadComponent: async () => import('./features/dashboard/pages/dashboard.component').then(m => m.DashboardComponent),
        data: { preload: true, seo: { titleKey: 'SEO.DASHBOARD', descriptionKey: 'SEO.DASHBOARD_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'products',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/products/product.routes'),
        data: { preload: true, seo: { titleKey: 'SEO.PRODUCTS', descriptionKey: 'SEO.PRODUCTS_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'meals',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/meals/meals.routes'),
        data: { preload: true, seo: { titleKey: 'SEO.MEALS', descriptionKey: 'SEO.MEALS_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'recipes',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/recipes/recipe.routes'),
        data: { seo: { titleKey: 'SEO.RECIPES', descriptionKey: 'SEO.RECIPES_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'explore',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/explore/explore.routes'),
        data: { seo: { titleKey: 'SEO.EXPLORE', descriptionKey: 'SEO.EXPLORE_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'shopping-lists',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/shopping-lists/shopping-list.routes'),
        data: { seo: { titleKey: 'SEO.SHOPPING_LISTS', descriptionKey: 'SEO.SHOPPING_LISTS_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'goals',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/goals/goals.routes'),
        data: { seo: { titleKey: 'SEO.GOALS', descriptionKey: 'SEO.GOALS_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'statistics',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/statistics/statistics.routes'),
        data: { seo: { titleKey: 'SEO.STATISTICS', descriptionKey: 'SEO.STATISTICS_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'weight-history',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/weight-history/weight-history.routes'),
        data: { seo: { titleKey: 'SEO.WEIGHT_HISTORY', descriptionKey: 'SEO.WEIGHT_HISTORY_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'waist-history',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/waist-history/waist-history.routes'),
        data: { seo: { titleKey: 'SEO.WAIST_HISTORY', descriptionKey: 'SEO.WAIST_HISTORY_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'cycle-tracking',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/cycle-tracking/cycle-tracking.routes'),
        data: { seo: { titleKey: 'SEO.CYCLE_TRACKING', descriptionKey: 'SEO.CYCLE_TRACKING_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'meal-plans',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/meal-plans/meal-plan.routes'),
        data: { seo: { titleKey: 'SEO.MEAL_PLANS', descriptionKey: 'SEO.MEAL_PLANS_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'weekly-check-in',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/weekly-check-in/weekly-check-in.routes'),
        data: { seo: { titleKey: 'SEO.WEEKLY_CHECK_IN', descriptionKey: 'SEO.WEEKLY_CHECK_IN_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'lessons',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/lessons/lesson.routes'),
        data: { seo: { titleKey: 'SEO.LESSONS', descriptionKey: 'SEO.LESSONS_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'gamification',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/gamification/gamification.routes'),
        data: { seo: { titleKey: 'SEO.GAMIFICATION', descriptionKey: 'SEO.GAMIFICATION_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'fasting',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/fasting/fasting.routes'),
        data: { seo: { titleKey: 'SEO.FASTING', descriptionKey: 'SEO.FASTING_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'premium',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/premium/premium.routes'),
        data: { seo: { titleKey: 'SEO.PREMIUM', descriptionKey: 'SEO.PREMIUM_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'profile',
        canActivate: [authGuard],
        loadChildren: async () => import('./features/profile/profile.routes'),
        data: { preload: true, seo: { titleKey: 'SEO.PROFILE', descriptionKey: 'SEO.PROFILE_DESCRIPTION', noIndex: true } },
    },
    {
        path: 'dietologist',
        canActivate: [dietologistGuard],
        loadChildren: async () => import('./features/dietologist/dietologist.routes').then(m => m.dietologistRoutes),
        data: { seo: { titleKey: 'SEO.DIETOLOGIST', noIndex: true } },
    },
    {
        path: 'dietologist-invitations/:invitationId',
        canActivate: [authGuard],
        loadComponent: async () =>
            import('./features/dietologist/pages/invitation/dietologist-invitation-page.component').then(
                m => m.DietologistInvitationPageComponent,
            ),
        data: { seo: { titleKey: 'SEO.DIETOLOGIST', noIndex: true } },
    },
    {
        path: 'privacy-policy',
        loadComponent: async () =>
            import('./features/public/pages/privacy-policy/privacy-policy.component').then(m => m.PrivacyPolicyComponent),
        data: { seo: { titleKey: 'SEO.PRIVACY_POLICY', descriptionKey: 'SEO.PRIVACY_POLICY_DESCRIPTION' } },
    },
    {
        path: '**',
        loadComponent: async () => import('./features/public/pages/not-found/not-found.component').then(m => m.NotFoundComponent),
        data: { seo: { titleKey: 'SEO.NOT_FOUND', noIndex: true } },
    },
];
