<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.Cycles.Application.Abstractions</AssemblyName>
    <RootNamespace>FoodDiary.Application.Abstractions.Cycles</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Domain.Contracts/FoodDiary.Modules.Cycles.Domain.Contracts.csproj" />
    <ProjectReference Include="../../Domain/FoodDiary.Modules.Cycles.Domain.csproj" />
    <ProjectReference Include="../../../../Shared/FoodDiary.Results/FoodDiary.Results.csproj" />
    <ProjectReference Include="../../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>
</Project>
