export const PRODUCT_LIST_PAGE_SIZE = 10;
export const PRODUCT_LIST_RECENT_LIMIT = 10;
export const PRODUCT_LIST_FAVORITE_LIMIT = 10;
export const PRODUCT_LIST_OFF_SEARCH_LIMIT = 5;
export const PRODUCT_LIST_OFF_SEARCH_MIN_LENGTH = 2;
