<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FoodDiary.Presentation.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Asp.Versioning.Mvc" />
    <ProjectReference Include="../../../FoodDiary.Presentation.Api/FoodDiary.Presentation.Api.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.Lessons.Application.csproj" />
    <ProjectReference Include="../Application/Abstractions/FoodDiary.Modules.Lessons.Application.Abstractions.csproj" />
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Lessons.Contracts.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Lessons.Domain.csproj" />
  </ItemGroup>

</Project>
