export const WEIGHT_TREND_EPSILON = 0.01;
export const WEIGHT_TREND_DISPLAY_FRACTION_DIGITS = 1;
export const WEIGHT_TREND_ROUNDING_FACTOR = 10;
export const WEIGHT_TREND_FILL_COLOR_PERCENT = 15;
export const WEIGHT_TREND_ISO_DATE_LENGTH = 10;
