namespace FoodDiary.Modules.OpenFoodFacts.Application.Abstractions.Common;

public interface IOpenFoodFactsProductCacheRepository : IOpenFoodFactsProductCacheReadRepository, IOpenFoodFactsProductCacheWriteRepository;
