@{
    SchemaVersion = 1
    Groups = @(
        @{ Id = 'adaptive-routing'; IncludeInAll = $false; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/(tools/(Get-LlmWikiAdaptiveWorkflow|Start-LlmWikiDevelopment|Get-LlmWikiSolutionComparison|Get-LlmWikiWorkflowMetrics|Write-LlmWikiWorkflowMetric|Test-LlmWikiAdaptiveWorkflow)|policies/experience-policies\.json|workflows/developer-experience\.md)') }
        @{ Id = 'adaptive-evals'; IncludeInAll = $true; ParallelSafe = $true; Priority = 100; GraphDependent = $true; Patterns = @('^\.llm-wiki/(tools/(Invoke-LlmWikiAdaptiveVerification|Get-LlmWikiIntegrationScan|Test-LlmWikiIntegrationScan|Invoke-LlmWikiEvals)|evals/|workflows/(integration-scan|evals|learned-regression-evals)\.md)') }
        @{ Id = 'change-policy'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/(policies/change-policies\.json|tools/(Get-LlmWikiChangePolicy|Test-LlmWikiChangePolicy)\.ps1)$') }
        @{ Id = 'adaptive-experience'; IncludeInAll = $false; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/Get-LlmWikiDesignCheckpoint\.ps1$') }
        @{ Id = 'dependency-analysis'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/(tools/Get-LlmWikiDependencyChanges|workflows/dependency-rollout\.md)') }
        @{ Id = 'read-only-guard'; IncludeInAll = $true; ParallelSafe = $false; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Invoke-LlmWikiReadOnlyTool|Test-LlmWikiReadOnlyGuard)\.ps1$') }
        @{ Id = 'facade-contract'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/(tools/(Invoke-LlmWikiAffectedSmoke|Invoke-LlmWikiParallelSmoke|Invoke-LlmWikiObservedStage|Start-LlmWikiVerifyWorker|Invoke-LlmWikiAdaptiveVerification|LlmWikiSmokeSandbox|Test-LlmWikiAffectedSmokePlanning|Test-LlmWikiObservedStageReceipt|Test-LlmWikiStrictAffected|Test-LlmWikiFacadeCommandCatalog|Test-LlmWikiFormattingReady)|wiki\.ps1|policies/affected-smoke-catalog\.psd1|workflows/(adaptive-development|index-pipeline)\.md)') }
        @{ Id = 'index-selection'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Invoke-LlmWikiIndexPipeline|Invoke-LlmWikiContractReferenceExtractor|LlmWikiIndexCache|LlmWikiIndexTiming|Test-LlmWikiIndexTiming|Test-LlmWikiIndexFingerprint|Test-LlmWikiContractReferenceExtractor|Test-LlmWikiIndexCheckpoint|LlmWikiGeneratedArtifacts|Build-LlmWikiCatalog|Build-LlmWiki(?:Frontend|FrontendContract|BackendContract|Quality|ArchitectureHealth|ModulePages)Index|Build-LlmWikiModulePages|Test-LlmWikiGeneratedArtifacts|Test-LlmWikiIndexSelection|Test-LlmWikiBackendModuleModel)\.ps1$', '^\.llm-wiki/tools/contract-reference-extractor/', '^docs/architecture/backend-modules\.json$') }
        @{ Id = 'trace-output'; IncludeInAll = $true; ParallelSafe = $false; Priority = 65; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Find-LlmWikiFrontendTrace|Find-LlmWikiTrace|Test-LlmWikiTraceOutput|Find-LlmWikiQualityRisk|Test-LlmWikiQualityRisk)\.ps1$') }
        @{ Id = 'code-graph'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(?:Manage-LlmWikiCodeGraph|Measure-LlmWikiCodeGraph|Test-LlmWikiCodeGraph|Test-LlmWikiRoslynExtractor|Test-LlmWikiTypeScriptExtractor|Get-LlmWikiGraphResearch|Get-LlmWikiGraphTestPlan)\.ps1$', '^\.llm-wiki/tools/(?:code-graph|typescript-extractor)\.mjs$', '^\.llm-wiki/tools/roslyn-extractor/') }
        @{ Id = 'api-compatibility'; IncludeInAll = $true; ParallelSafe = $true; Priority = 40; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(?:Test-LlmWikiApiCompatibility|Test-LlmWikiApiCompatibilityRegression)\.ps1$', '^\.llm-wiki/workflows/api-compatibility\.md$') }
        @{ Id = 'backend-contract-query'; IncludeInAll = $true; ParallelSafe = $false; Priority = 50; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Find-LlmWikiBackendContract|Test-LlmWikiBackendContractSqlParity)\.ps1$', '^\.llm-wiki/workflows/backend-contract-review\.md$') }
        @{ Id = 'frontend-contract-query'; IncludeInAll = $true; ParallelSafe = $false; Priority = 50; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Find-LlmWikiFrontendContract|Get-LlmWikiFrontendRuntimeOwner|Test-LlmWikiFrontendContractSqlParity|Test-LlmWikiFrontendRuntimeOwnerSqlParity)\.ps1$', '^\.llm-wiki/workflows/frontend-contract-review\.md$') }
        @{ Id = 'task-baseline'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Manage-LlmWikiTaskBaseline|Get-LlmWikiDiffContext|Test-LlmWikiTaskBaseline|Test-LlmWikiDiffContextSqlParity)\.ps1$') }
        @{ Id = 'git-paths'; IncludeInAll = $true; ParallelSafe = $true; Priority = 35; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(LlmWikiGitPaths|Test-LlmWikiGitPaths)\.ps1$') }
        @{ Id = 'task-scope'; IncludeInAll = $true; ParallelSafe = $true; Priority = 75; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Initialize-LlmWikiTaskWorkspace|Manage-LlmWikiTaskContract|Manage-LlmWikiTaskWorkspace|Manage-LlmWikiPlanConformance|Test-LlmWikiTaskScope|Test-LlmWikiTaskWorkspace|Update-LlmWikiTaskWorkspace|Manage-LlmWikiTaskJournal|Compare-LlmWikiTaskPolicy)\.ps1$') }
        @{ Id = 'ui-continuation'; IncludeInAll = $true; ParallelSafe = $true; Priority = 60; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Get-LlmWikiUiContinuation|Test-LlmWikiUiContinuation|Get-LlmWikiTestPlan|Test-LlmWikiTestPlanPrecision)\.ps1$') }
        @{ Id = 'research-confidence'; IncludeInAll = $true; ParallelSafe = $true; Priority = 80; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Get-LlmWikiAdaptiveWorkflow|Get-LlmWikiResearchPacket|Test-LlmWikiResearchConfidence|Get-LlmWikiCoveragePlan|Test-LlmWikiCoveragePlan|Manage-LlmWikiFailures|Test-LlmWikiFailuresSearch)\.ps1$') }
        @{ Id = 'implementation-plan'; IncludeInAll = $true; ParallelSafe = $true; Priority = 45; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(LlmWikiImplementationBrief|LlmWikiExtractionPlanning|LlmWikiRequirementCriteria|Get-LlmWikiImplementationPlan|Get-LlmWikiChangePacket|Manage-LlmWikiChangeManifest|Get-LlmWikiReleaseReadiness|Get-LlmWikiReviewReport|Manage-LlmWikiRequirementModel|Manage-LlmWikiAcceptanceMatrix|Manage-LlmWikiProofOfChange|Initialize-LlmWikiTaskWorkspace|Start-LlmWikiDevelopment|Test-LlmWikiImplementationPlan|Test-LlmWikiGovernedExtraction|Test-LlmWikiGovernedAuthenticationStart)\.ps1$') }
        @{ Id = 'reporting'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Get-LlmWikiReviewReport|Test-LlmWikiReviewReport)\.ps1$') }
        @{ Id = 'verification-receipts'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(LlmWikiVerificationReceipts|Manage-LlmWikiVerificationReceipts|Import-LlmWikiEvidenceReceipts|Test-LlmWikiVerificationReceipts)\.ps1$') }
        @{ Id = 'verification-cache'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Manage-LlmWikiVerificationCache|Test-LlmWikiVerificationCache|Test-LlmWikiIndexManifest|Get-LlmWikiVerificationStageFingerprint|Invoke-LlmWikiFullVerification|Write-LlmWikiIndexVerificationReceipt)\.ps1$', '^\.llm-wiki/policies/query-indexes\.json$') }
        @{ Id = 'query-cache'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(LlmWikiQueryCache|Test-LlmWikiQueryCache|Get-LlmWikiTaskBrief|Get-LlmWikiResearchPacket|Get-LlmWikiTestPlan|Test-LlmWikiTaskBriefSqlParity)\.ps1$') }
        @{ Id = 'contract-consumers'; IncludeInAll = $true; ParallelSafe = $true; Priority = 55; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Get-LlmWikiContractConsumers|Test-LlmWikiContractConsumers)\.ps1$') }
        @{ Id = 'extraction-readiness'; IncludeInAll = $true; ParallelSafe = $true; Priority = 85; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Get-LlmWikiExtractionReadiness|Test-LlmWikiExtractionReadiness)\.ps1$') }
        @{ Id = 'knowledge-isolation'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/(knowledge/learning-promotions\.json|tools/(Manage-LlmWikiLearningPromotion|Manage-LlmWikiLearningExperiment|Format-LlmWikiLearningExperimentResult|Test-LlmWikiLearningExperimentFormatting|Format-LlmWikiLearningResults|Test-LlmWikiLearningResultFormatting|Test-LlmWikiLearningPromotionMigration|Manage-LlmWikiEvalPromotion|Manage-LlmWikiLearningHealth|Test-LlmWikiKnowledgeIsolation)\.ps1)$') }
        @{ Id = 'memory'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Manage-LlmWikiMemory|Test-LlmWikiMemoryIsolation)\.ps1$') }
        @{ Id = 'context-bundle'; IncludeInAll = $true; ParallelSafe = $false; Priority = 50; GraphDependent = $true; Patterns = @('^\.llm-wiki/tools/(Find-LlmWikiContext|Manage-LlmWikiContextBundle|Manage-LlmWikiContextSecurity|Manage-LlmWikiVerificationPlan|Measure-LlmWikiSqlContextEvaluation|Test-LlmWikiCompiledIndexSqlParity|Test-LlmWikiContextCache|Test-LlmWikiSqlContextEvaluation|Test-LlmWikiSqlContextShadow|Test-LlmWikiWorkflowRecovery)\.ps1$', '^\.llm-wiki/evals/context-search\.json$') }
        @{ Id = 'context-feedback'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Manage-LlmWikiContextFeedback|Test-LlmWikiContextFeedbackMetrics)\.ps1$') }
        @{ Id = 'strict-shapes'; IncludeInAll = $true; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(LlmWikiCollections|Test-LlmWikiCollections)\.ps1$') }
        @{ Id = 'test-only-governance'; IncludeInAll = $true; ParallelSafe = $true; Priority = 70; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(Manage-LlmWikiChangeManifest|Manage-LlmWikiAcceptanceMatrix|Test-LlmWikiTestOnlyGovernance)\.ps1$') }
        @{ Id = 'governed-delivery'; IncludeInAll = $true; ParallelSafe = $true; Priority = 90; GraphDependent = $false; Patterns = @('^\.llm-wiki/tools/(LlmWikiChangePacket|Invoke-LlmWikiDeliveryWorkflow|Invoke-LlmWikiDeliveryFinalization|Complete-LlmWikiTaskWorkspace|Manage-LlmWikiPlanConformance|Manage-LlmWikiTaskWorkspace|Manage-LlmWikiTaskEvidence|Manage-LlmWikiEvidence|Manage-LlmWikiAcceptanceMatrix|Manage-LlmWikiProofOfChange|Manage-LlmWikiContextSecurity|Manage-LlmWikiChangeCritique|Manage-LlmWikiConfidenceLedger|Manage-LlmWikiImpactSimulation|Manage-LlmWikiRiskCalibration|Manage-LlmWikiFailurePrediction|Manage-LlmWikiVerificationCost|Manage-LlmWikiRequirementModel|New-LlmWikiEvidenceLineage|Test-LlmWikiEvidenceLineage|Update-LlmWikiTaskEvidence|Add-LlmWikiSourceReview|Get-LlmWikiReleaseReadiness|Get-LlmWikiReviewReport|Test-LlmWikiChangePacketMetadata|Test-LlmWikiGovernedDeliveryRegression|Test-LlmWikiGovernedAuthenticationStart)\.ps1$') }
        @{ Id = 'tool-contract'; IncludeInAll = $false; ParallelSafe = $true; Priority = 0; GraphDependent = $false; Fallback = $true; Patterns = @('^\.llm-wiki/tools/') }
    )
    Suppressions = @(
        @{ When = 'adaptive-evals'; Remove = @('adaptive-routing', 'adaptive-experience') }
        @{ When = 'code-graph'; Remove = @('trace-output') }
    )
    AdditionalMatches = @(
        @{ Pattern = '^\.llm-wiki/tools/LlmWikiQueryCache\.ps1$'; Groups = @('context-bundle') }
    )
}
