namespace FoodDiary.Application.Abstractions.OpenFoodFacts.Common;

public interface IOpenFoodFactsProductCacheRepository : IOpenFoodFactsProductCacheReadRepository, IOpenFoodFactsProductCacheWriteRepository;
