namespace FoodDiary.Modules.Favorites.Application.Abstractions.FavoriteMeals.Common;

public interface IFavoriteMealRepository : IFavoriteMealReadRepository, IFavoriteMealReadModelRepository, IFavoriteMealWriteRepository;
