namespace FoodDiary.Application.Abstractions.FavoriteMeals.Common;

public interface IFavoriteMealRepository : IFavoriteMealReadRepository, IFavoriteMealReadModelRepository, IFavoriteMealWriteRepository;
