using System.Xml.Linq;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FoodDiary.ArchitectureTests;

[ExcludeFromCodeCoverage]
public sealed class MigratedModuleNamespaceTests {
    [Theory]
    [InlineData("Products", "Application")]
    [InlineData("Products", "Application.Abstractions")]
    [InlineData("Products", "Contracts")]
    [InlineData("Products", "Domain")]
    [InlineData("Products", "Domain.Contracts")]
    [InlineData("Products", "FoodQuality")]
    [InlineData("Products", "Infrastructure")]
    [InlineData("Products", "PersistenceModel")]
    [InlineData("Products", "Presentation")]
    [InlineData("Products", "tests/FoodDiary.Modules.Products.Application.Tests")]
    [InlineData("Products", "tests/FoodDiary.Modules.Products.Domain.Tests")]
    [InlineData("Products", "tests/FoodDiary.Modules.Products.Infrastructure.IntegrationTests")]
    [InlineData("Products", "tests/FoodDiary.Modules.Products.Presentation.Tests")]
    [InlineData("RecentItems", "Application")]
    [InlineData("RecentItems", "Application.Abstractions")]
    [InlineData("RecentItems", "Contracts")]
    [InlineData("RecentItems", "Domain")]
    [InlineData("RecentItems", "Infrastructure")]
    [InlineData("RecentItems", "PersistenceModel")]
    [InlineData("RecentItems", "tests/FoodDiary.Modules.RecentItems.Domain.Tests")]
    [InlineData("RecentItems", "tests/FoodDiary.Modules.RecentItems.Infrastructure.IntegrationTests")]
    [InlineData("RecentItems", "tests/FoodDiary.Modules.RecentItems.Infrastructure.Tests")]
    [InlineData("RecipeCommunity", "Application")]
    [InlineData("RecipeCommunity", "Application.Abstractions")]
    [InlineData("RecipeCommunity", "Domain")]
    [InlineData("RecipeCommunity", "Infrastructure")]
    [InlineData("RecipeCommunity", "PersistenceModel")]
    [InlineData("RecipeCommunity", "Presentation")]
    [InlineData("RecipeCommunity", "tests/FoodDiary.Modules.RecipeCommunity.Application.Tests")]
    [InlineData("RecipeCommunity", "tests/FoodDiary.Modules.RecipeCommunity.Domain.Tests")]
    [InlineData("RecipeCommunity", "tests/FoodDiary.Modules.RecipeCommunity.Presentation.Tests")]
    [InlineData("Recipes", "Application")]
    [InlineData("Recipes", "Application.Abstractions")]
    [InlineData("Recipes", "Contracts")]
    [InlineData("Recipes", "Domain")]
    [InlineData("Recipes", "Domain.Contracts")]
    [InlineData("Recipes", "Infrastructure")]
    [InlineData("Recipes", "PersistenceModel")]
    [InlineData("Recipes", "Presentation")]
    [InlineData("Recipes", "tests/FoodDiary.Modules.Recipes.Application.Tests")]
    [InlineData("Recipes", "tests/FoodDiary.Modules.Recipes.Domain.Tests")]
    [InlineData("Recipes", "tests/FoodDiary.Modules.Recipes.Presentation.Tests")]
    [InlineData("Statistics", "Application")]
    [InlineData("Statistics", "Presentation")]
    [InlineData("Statistics", "tests/FoodDiary.Modules.Statistics.Application.Tests")]
    [InlineData("Statistics", "tests/FoodDiary.Modules.Statistics.Presentation.Tests")]
    [InlineData("Tdee", "Application")]
    [InlineData("Tdee", "Contracts")]
    [InlineData("Tdee", "Presentation")]
    [InlineData("Tdee", "Presentation.Contracts")]
    [InlineData("Tdee", "Presentation.Mappings")]
    [InlineData("Tdee", "tests/FoodDiary.Modules.Tdee.Application.Tests")]
    [InlineData("Tdee", "tests/FoodDiary.Modules.Tdee.Presentation.Tests")]
    [InlineData("Marketing", "Application")]
    [InlineData("Marketing", "Application.Abstractions")]
    [InlineData("Marketing", "Contracts")]
    [InlineData("Marketing", "Domain")]
    [InlineData("Marketing", "Infrastructure")]
    [InlineData("Marketing", "PersistenceModel")]
    [InlineData("Marketing", "Presentation")]
    [InlineData("Marketing", "tests/FoodDiary.Modules.Marketing.Application.Tests")]
    [InlineData("Marketing", "tests/FoodDiary.Modules.Marketing.Domain.Tests")]
    [InlineData("Marketing", "tests/FoodDiary.Modules.Marketing.Infrastructure.IntegrationTests")]
    [InlineData("MealPlanning", "Application")]
    [InlineData("MealPlanning", "Application.Abstractions")]
    [InlineData("MealPlanning", "Domain")]
    [InlineData("MealPlanning", "Infrastructure")]
    [InlineData("MealPlanning", "PersistenceModel")]
    [InlineData("MealPlanning", "Presentation")]
    [InlineData("MealPlanning", "tests/FoodDiary.Modules.MealPlanning.Application.Tests")]
    [InlineData("MealPlanning", "tests/FoodDiary.Modules.MealPlanning.Domain.Tests")]
    [InlineData("MealPlanning", "tests/FoodDiary.Modules.MealPlanning.Infrastructure.IntegrationTests")]
    [InlineData("MealPlanning", "tests/FoodDiary.Modules.MealPlanning.Presentation.Tests")]
    [InlineData("Meals", "Application")]
    [InlineData("Meals", "Application.Abstractions")]
    [InlineData("Meals", "Contracts")]
    [InlineData("Meals", "Domain")]
    [InlineData("Meals", "Domain.Contracts")]
    [InlineData("Meals", "Infrastructure")]
    [InlineData("Meals", "PersistenceModel")]
    [InlineData("Meals", "Presentation")]
    [InlineData("Meals", "Presentation.Contracts")]
    [InlineData("Meals", "Presentation.Mappings")]
    [InlineData("Meals", "Service.Contracts")]
    [InlineData("Meals", "tests/FoodDiary.Modules.Meals.Application.Tests")]
    [InlineData("Meals", "tests/FoodDiary.Modules.Meals.Domain.Tests")]
    [InlineData("Meals", "tests/FoodDiary.Modules.Meals.Infrastructure.IntegrationTests")]
    [InlineData("Meals", "tests/FoodDiary.Modules.Meals.Presentation.Tests")]
    [InlineData("Notifications", "Application")]
    [InlineData("Notifications", "Application.Abstractions")]
    [InlineData("Notifications", "Contracts")]
    [InlineData("Notifications", "Domain")]
    [InlineData("Notifications", "Infrastructure")]
    [InlineData("Notifications", "PersistenceModel")]
    [InlineData("Notifications", "Presentation")]
    [InlineData("Notifications", "Presentation.Contracts")]
    [InlineData("Notifications", "Presentation.Mappings")]
    [InlineData("Notifications", "tests/FoodDiary.Modules.Notifications.Application.Tests")]
    [InlineData("Notifications", "tests/FoodDiary.Modules.Notifications.Domain.Tests")]
    [InlineData("Notifications", "tests/FoodDiary.Modules.Notifications.Infrastructure.Tests")]
    [InlineData("Notifications", "tests/FoodDiary.Modules.Notifications.Presentation.Tests")]
    [InlineData("OpenFoodFacts", "Application")]
    [InlineData("OpenFoodFacts", "Application.Abstractions")]
    [InlineData("OpenFoodFacts", "Contracts")]
    [InlineData("OpenFoodFacts", "Domain")]
    [InlineData("OpenFoodFacts", "Infrastructure")]
    [InlineData("OpenFoodFacts", "PersistenceModel")]
    [InlineData("OpenFoodFacts", "Presentation")]
    [InlineData("OpenFoodFacts", "tests/FoodDiary.Modules.OpenFoodFacts.Application.Tests")]
    [InlineData("OpenFoodFacts", "tests/FoodDiary.Modules.OpenFoodFacts.Domain.Tests")]
    [InlineData("OpenFoodFacts", "tests/FoodDiary.Modules.OpenFoodFacts.Infrastructure.Tests")]
    [InlineData("OpenFoodFacts", "tests/FoodDiary.Modules.OpenFoodFacts.Presentation.Tests")]
    [InlineData("Gamification", "Application")]
    [InlineData("Gamification", "Application.Abstractions")]
    [InlineData("Gamification", "Contracts")]
    [InlineData("Gamification", "Domain")]
    [InlineData("Gamification", "Domain.Contracts")]
    [InlineData("Gamification", "Infrastructure")]
    [InlineData("Gamification", "PersistenceModel")]
    [InlineData("Gamification", "Presentation")]
    [InlineData("Gamification", "tests/FoodDiary.Modules.Gamification.Application.Tests")]
    [InlineData("Gamification", "tests/FoodDiary.Modules.Gamification.Domain.Tests")]
    [InlineData("Gamification", "tests/FoodDiary.Modules.Gamification.Infrastructure.Tests")]
    [InlineData("Gamification", "tests/FoodDiary.Modules.Gamification.Presentation.Tests")]
    [InlineData("Hydration", "Application")]
    [InlineData("Hydration", "Application.Abstractions")]
    [InlineData("Hydration", "Contracts")]
    [InlineData("Hydration", "Domain")]
    [InlineData("Hydration", "Infrastructure")]
    [InlineData("Hydration", "PersistenceModel")]
    [InlineData("Hydration", "Presentation")]
    [InlineData("Hydration", "Presentation.Contracts")]
    [InlineData("Hydration", "Presentation.Mappings")]
    [InlineData("Hydration", "tests/FoodDiary.Modules.Hydration.Application.Tests")]
    [InlineData("Hydration", "tests/FoodDiary.Modules.Hydration.Domain.Tests")]
    [InlineData("Hydration", "tests/FoodDiary.Modules.Hydration.Infrastructure.Tests")]
    [InlineData("Hydration", "tests/FoodDiary.Modules.Hydration.Presentation.Tests")]
    [InlineData("Identity", "Application")]
    [InlineData("Identity", "Application.Abstractions")]
    [InlineData("Identity", "Contracts")]
    [InlineData("Identity", "Domain")]
    [InlineData("Identity", "Infrastructure")]
    [InlineData("Identity", "PersistenceModel")]
    [InlineData("Identity", "Presentation")]
    [InlineData("Identity", "tests/FoodDiary.Modules.Identity.Application.Tests")]
    [InlineData("Identity", "tests/FoodDiary.Modules.Identity.Domain.Tests")]
    [InlineData("Identity", "tests/FoodDiary.Modules.Identity.Infrastructure.IntegrationTests")]
    [InlineData("Identity", "tests/FoodDiary.Modules.Identity.Infrastructure.Tests")]
    [InlineData("Identity", "tests/FoodDiary.Modules.Identity.Presentation.Tests")]
    [InlineData("Images", "Application")]
    [InlineData("Images", "Application.Abstractions")]
    [InlineData("Images", "Contracts")]
    [InlineData("Images", "Domain")]
    [InlineData("Images", "Infrastructure")]
    [InlineData("Images", "PersistenceModel")]
    [InlineData("Images", "Presentation")]
    [InlineData("Images", "Service.Contracts")]
    [InlineData("Images", "tests/FoodDiary.Modules.Images.Application.Tests")]
    [InlineData("Images", "tests/FoodDiary.Modules.Images.Domain.Tests")]
    [InlineData("Images", "tests/FoodDiary.Modules.Images.Infrastructure.IntegrationTests")]
    [InlineData("Images", "tests/FoodDiary.Modules.Images.Infrastructure.Tests")]
    [InlineData("Images", "tests/FoodDiary.Modules.Images.Presentation.Tests")]
    [InlineData("Lessons", "Application")]
    [InlineData("Lessons", "Application.Abstractions")]
    [InlineData("Lessons", "Contracts")]
    [InlineData("Lessons", "Domain")]
    [InlineData("Lessons", "Domain.Contracts")]
    [InlineData("Lessons", "Infrastructure")]
    [InlineData("Lessons", "PersistenceModel")]
    [InlineData("Lessons", "Presentation")]
    [InlineData("Lessons", "tests/FoodDiary.Modules.Lessons.Application.Tests")]
    [InlineData("Lessons", "tests/FoodDiary.Modules.Lessons.Domain.Tests")]
    [InlineData("Lessons", "tests/FoodDiary.Modules.Lessons.Infrastructure.Tests")]
    [InlineData("Lessons", "tests/FoodDiary.Modules.Lessons.Presentation.Tests")]
    [InlineData("Billing", "Application")]
    [InlineData("Billing", "Application.Abstractions")]
    [InlineData("Billing", "Contracts")]
    [InlineData("Billing", "Domain")]
    [InlineData("Billing", "Domain.Contracts")]
    [InlineData("Billing", "Infrastructure")]
    [InlineData("Billing", "PersistenceModel")]
    [InlineData("Billing", "Presentation")]
    [InlineData("Billing", "tests/FoodDiary.Modules.Billing.Application.Tests")]
    [InlineData("Billing", "tests/FoodDiary.Modules.Billing.Domain.Tests")]
    [InlineData("Billing", "tests/FoodDiary.Modules.Billing.Infrastructure.Tests")]
    [InlineData("Billing", "tests/FoodDiary.Modules.Billing.Presentation.Tests")]
    [InlineData("BodyMetrics", "Application")]
    [InlineData("BodyMetrics", "Application.Abstractions")]
    [InlineData("BodyMetrics", "Contracts")]
    [InlineData("BodyMetrics", "Domain")]
    [InlineData("BodyMetrics", "Infrastructure")]
    [InlineData("BodyMetrics", "PersistenceModel")]
    [InlineData("BodyMetrics", "Presentation")]
    [InlineData("BodyMetrics", "Presentation.Contracts")]
    [InlineData("BodyMetrics", "Presentation.Mappings")]
    [InlineData("BodyMetrics", "tests/FoodDiary.Modules.BodyMetrics.Application.Tests")]
    [InlineData("BodyMetrics", "tests/FoodDiary.Modules.BodyMetrics.Domain.Tests")]
    [InlineData("BodyMetrics", "tests/FoodDiary.Modules.BodyMetrics.Presentation.Tests")]
    [InlineData("ContentReports", "Application")]
    [InlineData("ContentReports", "Application.Abstractions")]
    [InlineData("ContentReports", "Contracts")]
    [InlineData("ContentReports", "Domain")]
    [InlineData("ContentReports", "Domain.Contracts")]
    [InlineData("ContentReports", "Infrastructure")]
    [InlineData("ContentReports", "PersistenceModel")]
    [InlineData("ContentReports", "Presentation")]
    [InlineData("ContentReports", "tests/FoodDiary.Modules.ContentReports.Application.Tests")]
    [InlineData("ContentReports", "tests/FoodDiary.Modules.ContentReports.Domain.Tests")]
    [InlineData("ContentReports", "tests/FoodDiary.Modules.ContentReports.Infrastructure.Tests")]
    [InlineData("ContentReports", "tests/FoodDiary.Modules.ContentReports.Presentation.Tests")]
    [InlineData("Cycles", "Application")]
    [InlineData("Cycles", "Application.Abstractions")]
    [InlineData("Cycles", "Contracts")]
    [InlineData("Cycles", "Domain")]
    [InlineData("Cycles", "Domain.Contracts")]
    [InlineData("Cycles", "Infrastructure")]
    [InlineData("Cycles", "PersistenceModel")]
    [InlineData("Cycles", "Presentation")]
    [InlineData("Cycles", "Presentation.Contracts")]
    [InlineData("Cycles", "Presentation.Mappings")]
    [InlineData("Cycles", "tests/FoodDiary.Modules.Cycles.Application.Tests")]
    [InlineData("Cycles", "tests/FoodDiary.Modules.Cycles.Domain.Tests")]
    [InlineData("Cycles", "tests/FoodDiary.Modules.Cycles.Infrastructure.IntegrationTests")]
    [InlineData("Cycles", "tests/FoodDiary.Modules.Cycles.Infrastructure.Tests")]
    [InlineData("Cycles", "tests/FoodDiary.Modules.Cycles.Presentation.Tests")]
    [InlineData("DailyAdvices", "Application")]
    [InlineData("DailyAdvices", "Application.Abstractions")]
    [InlineData("DailyAdvices", "Contracts")]
    [InlineData("DailyAdvices", "Domain")]
    [InlineData("DailyAdvices", "Infrastructure")]
    [InlineData("DailyAdvices", "PersistenceModel")]
    [InlineData("DailyAdvices", "tests/FoodDiary.Modules.DailyAdvices.Application.Tests")]
    [InlineData("DailyAdvices", "tests/FoodDiary.Modules.DailyAdvices.Domain.Tests")]
    [InlineData("DailyAdvices", "tests/FoodDiary.Modules.DailyAdvices.Infrastructure.Tests")]
    [InlineData("Dashboard", "Application")]
    [InlineData("Dashboard", "Application.Abstractions")]
    [InlineData("Dashboard", "Contracts")]
    [InlineData("Dashboard", "Infrastructure")]
    [InlineData("Dashboard", "Presentation")]
    [InlineData("Dashboard", "Presentation.Contracts")]
    [InlineData("Dashboard", "Presentation.Mappings")]
    [InlineData("Dashboard", "tests/FoodDiary.Modules.Dashboard.Application.Tests")]
    [InlineData("Dashboard", "tests/FoodDiary.Modules.Dashboard.Infrastructure.Tests")]
    [InlineData("Dashboard", "tests/FoodDiary.Modules.Dashboard.Presentation.Tests")]
    [InlineData("Dietologist", "Application")]
    [InlineData("Dietologist", "Application.Abstractions")]
    [InlineData("Dietologist", "Contracts")]
    [InlineData("Dietologist", "Domain")]
    [InlineData("Dietologist", "Infrastructure")]
    [InlineData("Dietologist", "PersistenceModel")]
    [InlineData("Dietologist", "Presentation")]
    [InlineData("Dietologist", "Presentation.Contracts")]
    [InlineData("Dietologist", "tests/FoodDiary.Modules.Dietologist.Application.Tests")]
    [InlineData("Dietologist", "tests/FoodDiary.Modules.Dietologist.Domain.Tests")]
    [InlineData("Dietologist", "tests/FoodDiary.Modules.Dietologist.Infrastructure.Tests")]
    [InlineData("Dietologist", "tests/FoodDiary.Modules.Dietologist.Presentation.Tests")]
    [InlineData("Exercises", "Application")]
    [InlineData("Exercises", "Application.Abstractions")]
    [InlineData("Exercises", "Contracts")]
    [InlineData("Exercises", "Domain")]
    [InlineData("Exercises", "Infrastructure")]
    [InlineData("Exercises", "PersistenceModel")]
    [InlineData("Exercises", "Presentation")]
    [InlineData("Exercises", "tests/FoodDiary.Modules.Exercises.Application.Tests")]
    [InlineData("Exercises", "tests/FoodDiary.Modules.Exercises.Domain.Tests")]
    [InlineData("Exercises", "tests/FoodDiary.Modules.Exercises.Presentation.Tests")]
    [InlineData("Export", "Application")]
    [InlineData("Export", "Application.Abstractions")]
    [InlineData("Export", "Infrastructure")]
    [InlineData("Export", "Presentation")]
    [InlineData("Export", "tests/FoodDiary.Modules.Export.Application.Tests")]
    [InlineData("Export", "tests/FoodDiary.Modules.Export.Infrastructure.Tests")]
    [InlineData("Export", "tests/FoodDiary.Modules.Export.Presentation.Tests")]
    [InlineData("Fasting", "Application")]
    [InlineData("Fasting", "Application.Abstractions")]
    [InlineData("Fasting", "Contracts")]
    [InlineData("Fasting", "Domain")]
    [InlineData("Fasting", "Infrastructure")]
    [InlineData("Fasting", "PersistenceModel")]
    [InlineData("Fasting", "Presentation")]
    [InlineData("Fasting", "Presentation.Contracts")]
    [InlineData("Fasting", "Presentation.Mappings")]
    [InlineData("Fasting", "tests/FoodDiary.Modules.Fasting.Application.Tests")]
    [InlineData("Fasting", "tests/FoodDiary.Modules.Fasting.Domain.Tests")]
    [InlineData("Fasting", "tests/FoodDiary.Modules.Fasting.Infrastructure.Tests")]
    [InlineData("Fasting", "tests/FoodDiary.Modules.Fasting.Presentation.Tests")]
    [InlineData("Favorites", "Application")]
    [InlineData("Favorites", "Application.Abstractions")]
    [InlineData("Favorites", "Contracts")]
    [InlineData("Favorites", "Domain")]
    [InlineData("Favorites", "Domain.Contracts")]
    [InlineData("Favorites", "Infrastructure")]
    [InlineData("Favorites", "PersistenceModel")]
    [InlineData("Favorites", "Presentation")]
    [InlineData("Favorites", "Presentation.Contracts")]
    [InlineData("Favorites", "Presentation.Mappings")]
    [InlineData("Favorites", "tests/FoodDiary.Modules.Favorites.Application.Tests")]
    [InlineData("Favorites", "tests/FoodDiary.Modules.Favorites.Domain.Tests")]
    [InlineData("Favorites", "tests/FoodDiary.Modules.Favorites.Presentation.Tests")]
    public void Projects_UseProjectNamesAndFolderNamespaces(string module, string project) {
        string directory = ArchitectureTestPaths.FromRoot("Modules", module, project);
        string projectFile = Assert.Single(Directory.EnumerateFiles(directory, "*.csproj"));
        string expectedRoot = project.StartsWith("tests/", StringComparison.Ordinal)
            ? project[6..] : $"FoodDiary.Modules.{module}." + project;
        Assert.Equal(expectedRoot, Path.GetFileNameWithoutExtension(projectFile));
        var document = XDocument.Load(projectFile);
        Assert.Empty(document.Descendants("RootNamespace"));
        Assert.Empty(document.Descendants("AssemblyName"));
        string[] files = ModuleSourceCatalog.RequiredFiles(directory);
        var violations = new List<string>();
        foreach (string file in files) {
            string relative = Path.GetRelativePath(directory, file).Replace('\\', '/');
            string folder = Path.GetDirectoryName(relative)?.Replace('\\', '.').Replace('/', '.') ?? string.Empty;
            string expected = expectedRoot + (folder.Length == 0 ? string.Empty : "." + folder);
            foreach (string actual in ReadDeclaredNamespaces(File.ReadAllText(file))) {
                if (!string.Equals(actual, expected, StringComparison.Ordinal)) {
                    violations.Add($"{project}/{relative}: '{actual}', expected '{expected}'.");
                }
            }
        }
        Assert.True(violations.Count == 0, string.Join(Environment.NewLine, violations));
    }

    [Theory]
    [InlineData("Weight")]
    [InlineData("Waist")]
    public void BodyMetrics_ExposesOnlyWriteAndProjectionRepositoryPorts(string measurement) {
        string ports = ArchitectureTestPaths.FromRoot("Modules", "BodyMetrics", "Application.Abstractions", measurement + "Entries", "Common");
        string[] actual = [.. Directory.GetFiles(ports, "I*Repository.cs")
            .Select(path => Path.GetFileName(path)).Order(StringComparer.Ordinal)];
        Assert.Equal([$"I{measurement}EntryReadModelRepository.cs", $"I{measurement}EntryWriteRepository.cs"], actual);
        foreach (string feature in new[] { $"Read{measurement}Entries", $"ReadLatest{measurement}Entry", $"Read{measurement}Summaries" }) {
            string handlerPath = ArchitectureTestPaths.FromRoot("Modules", "BodyMetrics", "Application", measurement + "Entries", "Queries", feature, feature + "QueryHandler.cs");
            string handler = File.ReadAllText(handlerPath);
            Assert.Contains($"I{measurement}EntryReadModelRepository", handler, StringComparison.Ordinal);
            Assert.DoesNotContain("FoodDiary.Modules.BodyMetrics.Domain", handler, StringComparison.Ordinal);
        }
    }

    [Theory]
    [InlineData("public class Example { }", false)]
    [InlineData("public record Example;", false)]
    [InlineData("public delegate void Example();", false)]
    [InlineData("namespace Expected; public class Example { }", true)]
    [InlineData("namespace Expected { public class Example { } }", true)]
    [InlineData("namespace Wrong; public class Example { }", false)]
    [InlineData("namespace Expected { public class Example { } } public class Global { }", false)]
    public void NamespaceDetection_RequiresTypesToHaveTheExpectedNamespace(string source, bool expectedValid) {
        string[] actual = [.. ReadDeclaredNamespaces(source)];
        Assert.NotEmpty(actual);
        Assert.Equal(expectedValid, actual.All(value => string.Equals(value, "Expected", StringComparison.Ordinal)));
    }

    private static IEnumerable<string> ReadDeclaredNamespaces(string source) {
        CompilationUnitSyntax root = CSharpSyntaxTree.ParseText(source).GetCompilationUnitRoot();
        foreach (BaseNamespaceDeclarationSyntax declaration in root.DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>()) {
            yield return string.Join('.', declaration.Ancestors().OfType<BaseNamespaceDeclarationSyntax>()
                .Reverse().Select(parent => parent.Name.ToString()).Append(declaration.Name.ToString()));
        }
        foreach (MemberDeclarationSyntax declaration in root.DescendantNodes().OfType<MemberDeclarationSyntax>()
                     .Where(declaration => declaration is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax)) {
            if (!declaration.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().Any()) {
                yield return "<global namespace>";
            }
        }
    }
}
