namespace FoodDiary.ArchitectureTests;

[ExcludeFromCodeCoverage]
public sealed class ProjectDependencyMatrixTests {
    private static readonly IReadOnlyDictionary<string, string[]> AllowedProductionProjectReferences =
        new Dictionary<string, string[]>(StringComparer.Ordinal) {
            ["FoodDiary.Modules.Users.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Images.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Users.Domain.Contracts"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.Modules.Admin.Domain"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Admin.Application.Abstractions"] = ["FoodDiary.Modules.Admin.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Admin.PersistenceModel"] = ["FoodDiary.Modules.Admin.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Admin.Infrastructure"] = ["FoodDiary.Modules.Admin.Application", "FoodDiary.Infrastructure", "FoodDiary.Modules.Admin.PersistenceModel", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Ai.Domain"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Ai.Application.Abstractions"] = ["FoodDiary.Modules.Ai.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Ai.PersistenceModel"] = ["FoodDiary.Modules.Ai.Domain", "FoodDiary.Modules.Ai.Application.Abstractions", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Ai.Infrastructure"] = ["FoodDiary.Modules.Ai.Application", "FoodDiary.Infrastructure", "FoodDiary.Modules.Ai.PersistenceModel", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Dashboard.Contracts"] = ["FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Results"],
            ["FoodDiary.Modules.Dashboard.Application.Abstractions"] = ["FoodDiary.Modules.Dashboard.Contracts", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Results"],
            ["FoodDiary.Modules.Dashboard.Infrastructure"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Infrastructure", "FoodDiary.Modules.Dashboard.Application.Abstractions", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Products.Contracts"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Images.Contracts", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Products.Domain.Contracts"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.Modules.Products.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Images.Contracts", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Usda.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Products.Application.Abstractions"] = ["FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Results"],
            ["FoodDiary.Modules.Products.PersistenceModel"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Products.Infrastructure"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Infrastructure", "FoodDiary.Modules.Products.Application", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Products.PersistenceModel", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.RecentItems.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.RecentItems.Application.Abstractions"] = ["FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Recipes.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.RecentItems.PersistenceModel"] = ["FoodDiary.Modules.RecentItems.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.RecentItems.Infrastructure"] = ["FoodDiary.Infrastructure", "FoodDiary.Modules.RecentItems.Application.Abstractions", "FoodDiary.Modules.RecentItems.PersistenceModel", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Recipes.Contracts"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Images.Contracts", "FoodDiary.Modules.Recipes.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Recipes.Domain.Contracts"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.Modules.Recipes.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Recipes.Domain.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Recipes.Application.Abstractions"] = ["FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Results"],
            ["FoodDiary.Modules.Recipes.PersistenceModel"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Recipes.Infrastructure"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Infrastructure", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Recipes.Application", "FoodDiary.Modules.Recipes.PersistenceModel", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Analyzers"] = [],
            ["FoodDiary.Outbox.Abstractions"] = [],
            ["FoodDiary.Modules.Notifications.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Notifications.Application.Abstractions"] = ["FoodDiary.Modules.Notifications.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Notifications.PersistenceModel"] = ["FoodDiary.Modules.Notifications.Domain", "FoodDiary.Outbox.Abstractions", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Notifications.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Notifications.Application.Abstractions",
                "FoodDiary.Modules.Notifications.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Development.Mcp"] = [],
            ["FoodDiary.Application.Runtime"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator"],
            ["FoodDiary.Modules.Admin.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Admin.Application.Abstractions", "FoodDiary.Modules.Ai.Application", "FoodDiary.Modules.ContentReports.Contracts", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Gamification.Application", "FoodDiary.Modules.Lessons.Contracts", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Application.Billing"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.Billing.Application.Abstractions",
                "FoodDiary.Modules.Billing.Domain",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Billing.Application.Abstractions"] = ["FoodDiary.Modules.Billing.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Billing.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Billing.PersistenceModel"] = ["FoodDiary.Modules.Billing.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Billing.Infrastructure"] = [
                "FoodDiary.Application.Billing",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Billing.Application.Abstractions",
                "FoodDiary.Modules.Billing.Domain",
                "FoodDiary.Modules.Billing.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Ai.Application"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.Ai.Application.Abstractions",
                "FoodDiary.Modules.Ai.Domain",
                "FoodDiary.Modules.Images.Domain",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Application.BodyMetrics"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.BodyMetrics.Application.Abstractions", "FoodDiary.Modules.BodyMetrics.Domain", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.BodyMetrics.Application.Abstractions"] = ["FoodDiary.Modules.BodyMetrics.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.BodyMetrics.Domain"] = ["FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.BodyMetrics.PersistenceModel"] = ["FoodDiary.Modules.BodyMetrics.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.BodyMetrics.Infrastructure"] = [
                "FoodDiary.Application.BodyMetrics",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.BodyMetrics.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Application.Cycles"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Cycles.Application.Abstractions", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Cycles.Application.Abstractions"] = ["FoodDiary.Modules.Cycles.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Cycles.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Cycles.Infrastructure"] = [
                "FoodDiary.Modules.Cycles.Domain",
                "FoodDiary.Application.Cycles",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Cycles.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Cycles.PersistenceModel"] = ["FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Dashboard.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Application.Cycles", "FoodDiary.Mediator", "FoodDiary.Modules.DailyAdvices.Application", "FoodDiary.Modules.Dashboard.Application.Abstractions", "FoodDiary.Modules.Dietologist.Application.Abstractions", "FoodDiary.Modules.Exercises.Contracts", "FoodDiary.Modules.Fasting.Contracts", "FoodDiary.Modules.Hydration.Contracts", "FoodDiary.Modules.Meals.Application", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Statistics.Application", "FoodDiary.Modules.Tdee.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.ContentReports.Application"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.ContentReports.Application.Abstractions",
                "FoodDiary.Modules.ContentReports.Contracts",
                "FoodDiary.Modules.ContentReports.Domain",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.ContentReports.Application.Abstractions"] = ["FoodDiary.Modules.ContentReports.Contracts", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.ContentReports.Contracts"] = ["FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.ContentReports.Domain"] = ["FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.ContentReports.Infrastructure"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Infrastructure", "FoodDiary.Modules.ContentReports.Application", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.ContentReports.PersistenceModel", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.ContentReports.PersistenceModel"] = ["FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.DailyAdvices.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.DailyAdvices.Application.Abstractions", "FoodDiary.Modules.DailyAdvices.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.DailyAdvices.Application.Abstractions"] = [],
            ["FoodDiary.Modules.DailyAdvices.Domain"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.DailyAdvices.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.DailyAdvices.Application",
                "FoodDiary.Modules.DailyAdvices.PersistenceModel",
            ],
            ["FoodDiary.Modules.DailyAdvices.PersistenceModel"] = ["FoodDiary.Modules.DailyAdvices.Domain"],
            ["FoodDiary.Modules.Hydration.Application"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.Hydration.Application.Abstractions",
                "FoodDiary.Modules.Hydration.Contracts",
                "FoodDiary.Modules.Hydration.Domain",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Hydration.Application.Abstractions"] = ["FoodDiary.Modules.Hydration.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Hydration.Contracts"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Hydration.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Hydration.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Hydration.Application",
                "FoodDiary.Modules.Hydration.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Hydration.PersistenceModel"] = ["FoodDiary.Modules.Hydration.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Lessons.Application"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.Gamification.Application.Abstractions",
                "FoodDiary.Modules.Lessons.Application.Abstractions",
                "FoodDiary.Modules.Lessons.Contracts",
                "FoodDiary.Modules.Lessons.Domain",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Lessons.Application.Abstractions"] = ["FoodDiary.Modules.Lessons.Contracts", "FoodDiary.Modules.Lessons.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Lessons.Contracts"] = ["FoodDiary.Modules.Lessons.Domain", "FoodDiary.Results"],
            ["FoodDiary.Modules.Lessons.Domain"] = ["FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Lessons.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Lessons.Application",
                "FoodDiary.Modules.Lessons.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Lessons.PersistenceModel"] = ["FoodDiary.Modules.Lessons.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Dietologist.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Dietologist.Application.Abstractions", "FoodDiary.Modules.Dietologist.Domain", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Dietologist.Application.Abstractions"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Modules.Dietologist.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Dietologist.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Dietologist.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Dietologist.Application",
                "FoodDiary.Modules.Dietologist.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Dietologist.PersistenceModel"] = ["FoodDiary.Modules.Dietologist.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Application.Exercises"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Exercises.Application.Abstractions", "FoodDiary.Modules.Exercises.Contracts", "FoodDiary.Modules.Exercises.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Export.Infrastructure"] = ["FoodDiary.Modules.Export.Application.Abstractions", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Meals.Domain"],
            ["FoodDiary.Modules.Export.Application"] = ["FoodDiary.Application.Cycles", "FoodDiary.Mediator", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.Export.Application.Abstractions", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Export.Application.Abstractions"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Modules.Meals.Contracts",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Fasting.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Fasting.Application.Abstractions", "FoodDiary.Modules.Fasting.Contracts", "FoodDiary.Modules.Fasting.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Fasting.Application.Abstractions"] = ["FoodDiary.Modules.Fasting.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Fasting.Contracts"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Fasting.Domain"] = ["FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Fasting.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Fasting.Application",
                "FoodDiary.Modules.Fasting.PersistenceModel",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Fasting.PersistenceModel"] = ["FoodDiary.Modules.Fasting.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Application.Favorites"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Favorites.Domain", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Favorites.Domain"] = ["FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Favorites.Infrastructure"] = ["FoodDiary.Application.Favorites", "FoodDiary.Domain.Primitives", "FoodDiary.Infrastructure", "FoodDiary.Modules.Favorites.PersistenceModel", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Favorites.PersistenceModel"] = ["FoodDiary.Modules.Favorites.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Gamification.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Gamification.Application.Abstractions", "FoodDiary.Modules.Gamification.Domain", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Gamification.Application.Abstractions"] = ["FoodDiary.Modules.Gamification.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Results"],
            ["FoodDiary.Modules.Gamification.Domain"] = ["FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Gamification.PersistenceModel"] = ["FoodDiary.Modules.Gamification.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Gamification.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Gamification.Application",
                "FoodDiary.Modules.Gamification.Application.Abstractions",
                "FoodDiary.Modules.Gamification.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Application.Wearables"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Modules.Wearables.Application.Abstractions", "FoodDiary.Modules.Wearables.Domain"],
            ["FoodDiary.Modules.Wearables.Application.Abstractions"] = ["FoodDiary.Modules.Wearables.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Wearables.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Wearables.PersistenceModel"] = ["FoodDiary.Modules.Wearables.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Wearables.Infrastructure"] = [
                "FoodDiary.Application.Wearables",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Wearables.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Identity.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Identity.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Identity.Domain"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Identity.PersistenceModel"] = ["FoodDiary.Modules.Identity.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Identity.Infrastructure"] = [
                "FoodDiary.Modules.Identity.Application",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Identity.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Application.Images"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Images.Application.Abstractions", "FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Images.Application.Abstractions"] = ["FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Results"],
            ["FoodDiary.Modules.Images.Contracts"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.Modules.Images.Domain"] = ["FoodDiary.Modules.Images.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Images.PersistenceModel"] = ["FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Images.Infrastructure"] = [
                "FoodDiary.Application.Images",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Images.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Application.MealPlanning"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.MealPlanning.Application.Abstractions", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Meals.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Application.Images", "FoodDiary.Mediator", "FoodDiary.Modules.Gamification.Application.Abstractions", "FoodDiary.Modules.Meals.Application.Abstractions", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.RecentItems.Application.Abstractions", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Meals.Application.Abstractions"] = [
                "FoodDiary.Modules.Meals.Domain",
                "FoodDiary.Modules.Meals.Contracts",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Meals.Contracts"] = [
                "FoodDiary.Modules.Products.Domain.Contracts",
                "FoodDiary.Modules.Meals.Domain",
                "FoodDiary.Modules.Favorites.Domain",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Meals.Infrastructure"] = ["FoodDiary.Infrastructure", "FoodDiary.Modules.Meals.Application", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Meals.PersistenceModel", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Meals.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Recipes.Domain.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Meals.PersistenceModel"] = ["FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.WeeklyGoals.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Modules.WeeklyGoals.Application.Abstractions", "FoodDiary.Modules.WeeklyGoals.Contracts", "FoodDiary.Modules.WeeklyGoals.Domain"],
            ["FoodDiary.Modules.WeeklyGoals.Application.Abstractions"] = ["FoodDiary.Modules.WeeklyGoals.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.WeeklyGoals.Contracts"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.WeeklyGoals.Domain"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.WeeklyGoals.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.WeeklyGoals.Application",
                "FoodDiary.Modules.WeeklyGoals.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.WeeklyGoals.PersistenceModel"] = ["FoodDiary.Modules.WeeklyGoals.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Application.Usda"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Usda.Application.Abstractions", "FoodDiary.Modules.Usda.Contracts", "FoodDiary.Modules.Usda.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Usda.Application.Abstractions"] = ["FoodDiary.Modules.Usda.Contracts", "FoodDiary.Modules.Usda.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Results"],
            ["FoodDiary.Modules.Usda.Contracts"] = [],
            ["FoodDiary.Modules.Usda.Infrastructure"] = [
                "FoodDiary.Application.Usda",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Usda.PersistenceModel",
            ],
            ["FoodDiary.Modules.Usda.Domain"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.Modules.Usda.PersistenceModel"] = ["FoodDiary.Modules.Usda.Domain"],
            ["FoodDiary.Modules.WeeklyCheckIn.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Hydration.Contracts", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Application.RecipeCommunity"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.RecipeCommunity.Application.Abstractions",
                "FoodDiary.Modules.RecipeCommunity.Domain",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Tdee.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Exercises.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Statistics.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Application.Marketing"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.Marketing.Application.Abstractions",
            ],
            ["FoodDiary.Modules.Marketing.Application.Abstractions"] = [],
            ["FoodDiary.Modules.Marketing.Domain"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Marketing.PersistenceModel"] = ["FoodDiary.Modules.Marketing.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Marketing.Infrastructure"] = [
                "FoodDiary.Application.Marketing",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Marketing.Application.Abstractions",
                "FoodDiary.Modules.Marketing.Domain",
                "FoodDiary.Modules.Marketing.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Application.Notifications"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Notifications.Application.Abstractions", "FoodDiary.Modules.Notifications.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.OpenFoodFacts.Application"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Mediator",
                "FoodDiary.Modules.OpenFoodFacts.Application.Abstractions",
                "FoodDiary.Modules.OpenFoodFacts.Contracts",
            ],
            ["FoodDiary.Modules.OpenFoodFacts.Application.Abstractions"] = ["FoodDiary.Modules.OpenFoodFacts.Contracts"],
            ["FoodDiary.Modules.OpenFoodFacts.Contracts"] = [],
            ["FoodDiary.Modules.OpenFoodFacts.Domain"] = [],
            ["FoodDiary.Modules.OpenFoodFacts.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.OpenFoodFacts.Application",
                "FoodDiary.Modules.OpenFoodFacts.PersistenceModel",
            ],
            ["FoodDiary.Modules.OpenFoodFacts.PersistenceModel"] = ["FoodDiary.Modules.OpenFoodFacts.Domain"],
            ["FoodDiary.Modules.Products.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Application.Images", "FoodDiary.Application.Usda", "FoodDiary.Domain.Primitives", "FoodDiary.Mediator", "FoodDiary.Modules.OpenFoodFacts.Contracts", "FoodDiary.Modules.Products.Application.Abstractions", "FoodDiary.Modules.Products.Contracts", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.RecentItems.Application.Abstractions", "FoodDiary.Modules.Usda.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Recipes.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Application.Images", "FoodDiary.Domain.Primitives", "FoodDiary.Mediator", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.RecentItems.Application.Abstractions", "FoodDiary.Modules.Recipes.Application.Abstractions", "FoodDiary.Modules.Recipes.Contracts", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Users.Application"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Users.Infrastructure"] = [
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.RecentItems.Domain",
                "FoodDiary.Modules.Users.Application",
                "FoodDiary.Modules.Users.PersistenceModel",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Users.PersistenceModel"] = ["FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Application.Abstractions"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Mediator", "FoodDiary.Modules.Admin.Application.Abstractions", "FoodDiary.Modules.Ai.Application.Abstractions", "FoodDiary.Modules.Billing.Application.Abstractions", "FoodDiary.Modules.BodyMetrics.Application.Abstractions", "FoodDiary.Modules.Cycles.Application.Abstractions", "FoodDiary.Modules.Dashboard.Contracts", "FoodDiary.Modules.Exercises.Application.Abstractions", "FoodDiary.Modules.Favorites.Domain", "FoodDiary.Modules.Identity.Domain", "FoodDiary.Modules.Images.Application.Abstractions", "FoodDiary.Modules.Marketing.Application.Abstractions", "FoodDiary.Modules.MealPlanning.Application.Abstractions", "FoodDiary.Modules.Notifications.Application.Abstractions", "FoodDiary.Modules.Products.Application.Abstractions", "FoodDiary.Modules.Products.Contracts", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.RecipeCommunity.Application.Abstractions", "FoodDiary.Modules.Recipes.Application.Abstractions", "FoodDiary.Modules.Recipes.Contracts", "FoodDiary.Modules.Usda.Application.Abstractions", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Wearables.Application.Abstractions", "FoodDiary.Results"],
            ["FoodDiary.Infrastructure"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Mediator", "FoodDiary.Modules.Admin.PersistenceModel", "FoodDiary.Modules.Ai.PersistenceModel", "FoodDiary.Modules.Billing.Domain", "FoodDiary.Modules.Billing.PersistenceModel", "FoodDiary.Modules.BodyMetrics.Domain", "FoodDiary.Modules.BodyMetrics.PersistenceModel", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.ContentReports.PersistenceModel", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.Cycles.PersistenceModel", "FoodDiary.Modules.DailyAdvices.Domain", "FoodDiary.Modules.DailyAdvices.PersistenceModel", "FoodDiary.Modules.Dietologist.Domain", "FoodDiary.Modules.Dietologist.PersistenceModel", "FoodDiary.Modules.Exercises.Domain", "FoodDiary.Modules.Exercises.PersistenceModel", "FoodDiary.Modules.Fasting.Domain", "FoodDiary.Modules.Fasting.PersistenceModel", "FoodDiary.Modules.Favorites.Domain", "FoodDiary.Modules.Favorites.PersistenceModel", "FoodDiary.Modules.Gamification.Application.Abstractions", "FoodDiary.Modules.Gamification.Domain", "FoodDiary.Modules.Gamification.PersistenceModel", "FoodDiary.Modules.Hydration.Domain", "FoodDiary.Modules.Hydration.PersistenceModel", "FoodDiary.Modules.Identity.Domain", "FoodDiary.Modules.Identity.PersistenceModel", "FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Images.PersistenceModel", "FoodDiary.Modules.Lessons.Domain", "FoodDiary.Modules.Lessons.PersistenceModel", "FoodDiary.Modules.Marketing.Domain", "FoodDiary.Modules.Marketing.PersistenceModel", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.MealPlanning.PersistenceModel", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Meals.PersistenceModel", "FoodDiary.Modules.Notifications.Domain", "FoodDiary.Modules.Notifications.PersistenceModel", "FoodDiary.Modules.OpenFoodFacts.Domain", "FoodDiary.Modules.OpenFoodFacts.PersistenceModel", "FoodDiary.Modules.Products.PersistenceModel", "FoodDiary.Modules.RecentItems.Domain", "FoodDiary.Modules.RecentItems.PersistenceModel", "FoodDiary.Modules.RecipeCommunity.PersistenceModel", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Recipes.PersistenceModel", "FoodDiary.Modules.Usda.PersistenceModel", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Modules.Users.PersistenceModel", "FoodDiary.Modules.Wearables.PersistenceModel", "FoodDiary.Modules.WeeklyGoals.Domain", "FoodDiary.Modules.WeeklyGoals.PersistenceModel", "FoodDiary.Outbox.Abstractions"],
            ["FoodDiary.Initializer"] = [
                "FoodDiary.Modules.Admin.Infrastructure",

                "FoodDiary.Modules.Ai.Infrastructure",
                "FoodDiary.Modules.Admin.Application",
                "FoodDiary.Modules.Ai.Application",
                "FoodDiary.Application.BodyMetrics",
                "FoodDiary.Application.Exercises",
                "FoodDiary.Modules.Identity.Application",
                "FoodDiary.Modules.Identity.Infrastructure",
                "FoodDiary.Application.Images",
                "FoodDiary.Application.MealPlanning",
                "FoodDiary.Modules.Meals.Infrastructure",
                "FoodDiary.Application.Notifications",
                "FoodDiary.Modules.Products.Application",
                "FoodDiary.Modules.RecentItems.Infrastructure",
                "FoodDiary.Application.RecipeCommunity",
                "FoodDiary.Modules.Recipes.Application",
                "FoodDiary.Application.Runtime",
                "FoodDiary.Application.Usda",
                "FoodDiary.Modules.Users.Infrastructure",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Billing.Infrastructure",
                "FoodDiary.Modules.BodyMetrics.Infrastructure",
                "FoodDiary.Modules.ContentReports.Infrastructure",
                "FoodDiary.Modules.Cycles.Infrastructure",
                "FoodDiary.Modules.DailyAdvices.Infrastructure",
                "FoodDiary.Modules.Dashboard.Application",
                "FoodDiary.Modules.Dashboard.Infrastructure",
                "FoodDiary.Modules.Dietologist.Infrastructure",
                "FoodDiary.Modules.Exercises.Infrastructure",
                "FoodDiary.Modules.Export.Application",
                "FoodDiary.Modules.Export.Infrastructure",
                "FoodDiary.Modules.Fasting.Infrastructure",
                "FoodDiary.Modules.Favorites.Infrastructure",
                "FoodDiary.Modules.Gamification.Infrastructure",
                "FoodDiary.Modules.Hydration.Infrastructure",
                "FoodDiary.Modules.Images.Infrastructure",
                "FoodDiary.Modules.Lessons.Infrastructure",
                "FoodDiary.Modules.Marketing.Infrastructure",
                "FoodDiary.Modules.MealPlanning.Infrastructure",
                "FoodDiary.Modules.Notifications.Infrastructure",
                "FoodDiary.Modules.OpenFoodFacts.Infrastructure",
                "FoodDiary.Modules.RecipeCommunity.Infrastructure",
                "FoodDiary.Modules.Statistics.Application",
                "FoodDiary.Modules.Tdee.Application",
                "FoodDiary.Modules.Usda.Infrastructure",
                "FoodDiary.Modules.Wearables.Infrastructure",
                "FoodDiary.Modules.WeeklyCheckIn.Application",
                "FoodDiary.Modules.WeeklyGoals.Infrastructure",
                "FoodDiary.Modules.Recipes.Infrastructure",
                "FoodDiary.Modules.Products.Infrastructure",
            ],
            ["FoodDiary.Integrations"] = ["FoodDiary.Application.Abstractions", "FoodDiary.MailInbox.Client", "FoodDiary.MailRelay.Client", "FoodDiary.Modules.OpenFoodFacts.Application.Abstractions", "FoodDiary.Modules.OpenFoodFacts.Contracts", "FoodDiary.Modules.Usda.Application.Abstractions", "FoodDiary.Modules.Usda.Contracts", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Modules.Wearables.Application.Abstractions", "FoodDiary.Modules.Wearables.Domain"],
            ["FoodDiary.JobManager"] = [
                "FoodDiary.Modules.Admin.Infrastructure",

                "FoodDiary.Modules.Ai.Infrastructure",
                "FoodDiary.Modules.Admin.Application",
                "FoodDiary.Modules.Ai.Application",
                "FoodDiary.Application.BodyMetrics",
                "FoodDiary.Application.Exercises",
                "FoodDiary.Modules.Identity.Application",
                "FoodDiary.Modules.Identity.Infrastructure",
                "FoodDiary.Application.Images",
                "FoodDiary.Application.MealPlanning",
                "FoodDiary.Modules.Meals.Infrastructure",
                "FoodDiary.Application.Notifications",
                "FoodDiary.Modules.Products.Application",
                "FoodDiary.Modules.RecentItems.Infrastructure",
                "FoodDiary.Application.RecipeCommunity",
                "FoodDiary.Modules.Recipes.Application",
                "FoodDiary.Application.Runtime",
                "FoodDiary.Application.Usda",
                "FoodDiary.Modules.Users.Infrastructure",
                "FoodDiary.Infrastructure",
                "FoodDiary.Integrations",
                "FoodDiary.Modules.Billing.Infrastructure",
                "FoodDiary.Modules.DailyAdvices.Application",
                "FoodDiary.Modules.Dashboard.Application",
                "FoodDiary.Modules.Dashboard.Infrastructure",
                "FoodDiary.Modules.Dietologist.Infrastructure",
                "FoodDiary.Modules.Export.Application",
                "FoodDiary.Modules.Export.Infrastructure",
                "FoodDiary.Modules.Fasting.Contracts",
                "FoodDiary.Modules.Fasting.Infrastructure",
                "FoodDiary.Modules.Favorites.Infrastructure",
                "FoodDiary.Modules.Gamification.Infrastructure",
                "FoodDiary.Modules.Images.Infrastructure",
                "FoodDiary.Modules.Marketing.Infrastructure",
                "FoodDiary.Modules.Notifications.Infrastructure",
                "FoodDiary.Modules.OpenFoodFacts.Application",
                "FoodDiary.Modules.Statistics.Application",
                "FoodDiary.Modules.Tdee.Application",
                "FoodDiary.Modules.WeeklyGoals.Application",
                "FoodDiary.Modules.WeeklyGoals.Infrastructure",
                "FoodDiary.Resources",
                "FoodDiary.Modules.Recipes.Infrastructure",
                "FoodDiary.Modules.Products.Infrastructure",
            ],
            ["FoodDiary.MailInbox.Application"] = [
                "FoodDiary.MailInbox.Domain",
                "FoodDiary.Mediator",
                "FoodDiary.Results",
            ],
            ["FoodDiary.MailInbox.Client"] = [],
            ["FoodDiary.MailInbox.Domain"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.MailInbox.Infrastructure"] = ["FoodDiary.MailInbox.Application"],
            ["FoodDiary.MailInbox.Initializer"] = ["FoodDiary.MailInbox.Application", "FoodDiary.MailInbox.Infrastructure"],
            ["FoodDiary.MailInbox.Presentation"] = ["FoodDiary.MailInbox.Application"],
            ["FoodDiary.MailInbox.WebApi"] = [
                "FoodDiary.MailInbox.Application",
                "FoodDiary.MailInbox.Infrastructure",
                "FoodDiary.MailInbox.Presentation",
            ],
            ["FoodDiary.MailRelay.Application"] = [
                "FoodDiary.MailRelay.Domain",
                "FoodDiary.Mediator",
                "FoodDiary.Results",
            ],
            ["FoodDiary.MailRelay.Client"] = [],
            ["FoodDiary.MailRelay.Domain"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.MailRelay.Infrastructure"] = ["FoodDiary.MailRelay.Application"],
            ["FoodDiary.MailRelay.Initializer"] = ["FoodDiary.MailRelay.Application", "FoodDiary.MailRelay.Infrastructure"],
            ["FoodDiary.MailRelay.Presentation"] = ["FoodDiary.MailRelay.Application", "FoodDiary.MailRelay.Client"],
            ["FoodDiary.MailRelay.WebApi"] = [
                "FoodDiary.MailRelay.Application",
                "FoodDiary.MailRelay.Infrastructure",
                "FoodDiary.MailRelay.Presentation",
            ],
            ["FoodDiary.Mediator"] = [],
            ["FoodDiary.Presentation.Api"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Application.Billing", "FoodDiary.Application.BodyMetrics", "FoodDiary.Application.Cycles", "FoodDiary.Application.Exercises", "FoodDiary.Application.Favorites", "FoodDiary.Application.Images", "FoodDiary.Application.Marketing", "FoodDiary.Application.MealPlanning", "FoodDiary.Application.Notifications", "FoodDiary.Application.RecipeCommunity", "FoodDiary.Application.Usda", "FoodDiary.Application.Wearables", "FoodDiary.Domain.Primitives", "FoodDiary.Mediator", "FoodDiary.Modules.Admin.Application", "FoodDiary.Modules.Ai.Application", "FoodDiary.Modules.ContentReports.Application", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.DailyAdvices.Application", "FoodDiary.Modules.Dashboard.Application", "FoodDiary.Modules.Dietologist.Application", "FoodDiary.Modules.Export.Application", "FoodDiary.Modules.Fasting.Application", "FoodDiary.Modules.Fasting.Contracts", "FoodDiary.Modules.Gamification.Application", "FoodDiary.Modules.Hydration.Application", "FoodDiary.Modules.Identity.Application", "FoodDiary.Modules.Lessons.Application", "FoodDiary.Modules.Meals.Application", "FoodDiary.Modules.OpenFoodFacts.Application", "FoodDiary.Modules.Products.Application", "FoodDiary.Modules.RecentItems.Application.Abstractions", "FoodDiary.Modules.Recipes.Application", "FoodDiary.Modules.Statistics.Application", "FoodDiary.Modules.Tdee.Application", "FoodDiary.Modules.Usda.Contracts", "FoodDiary.Modules.Users.Application", "FoodDiary.Modules.WeeklyCheckIn.Application", "FoodDiary.Modules.WeeklyGoals.Application", "FoodDiary.Results"],
            ["FoodDiary.Domain.Primitives"] = [],
            ["FoodDiary.Resources"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Modules.Export.Application.Abstractions"],
            ["FoodDiary.Results"] = [],
            ["FoodDiary.Telegram.Bot"] = [],
            ["FoodDiary.Web.Api"] = [
                "FoodDiary.Modules.Admin.Infrastructure",

                "FoodDiary.Modules.Ai.Infrastructure",
                "FoodDiary.Modules.Admin.Application",
                "FoodDiary.Modules.Ai.Application",
                "FoodDiary.Application.BodyMetrics",
                "FoodDiary.Application.Exercises",
                "FoodDiary.Modules.Identity.Application",
                "FoodDiary.Modules.Identity.Infrastructure",
                "FoodDiary.Application.Images",
                "FoodDiary.Application.MealPlanning",
                "FoodDiary.Modules.Meals.Infrastructure",
                "FoodDiary.Application.Notifications",
                "FoodDiary.Modules.Products.Application",
                "FoodDiary.Application.RecipeCommunity",
                "FoodDiary.Modules.Recipes.Application",
                "FoodDiary.Application.Runtime",
                "FoodDiary.Application.Usda",
                "FoodDiary.Modules.Users.Infrastructure",
                "FoodDiary.Infrastructure",
                "FoodDiary.Integrations",
                "FoodDiary.Modules.Billing.Infrastructure",
                "FoodDiary.Modules.BodyMetrics.Infrastructure",
                "FoodDiary.Modules.ContentReports.Infrastructure",
                "FoodDiary.Modules.Cycles.Infrastructure",
                "FoodDiary.Modules.DailyAdvices.Infrastructure",
                "FoodDiary.Modules.Dashboard.Application",
                "FoodDiary.Modules.Dashboard.Infrastructure",
                "FoodDiary.Modules.Dietologist.Infrastructure",
                "FoodDiary.Modules.Exercises.Infrastructure",
                "FoodDiary.Modules.Export.Application",
                "FoodDiary.Modules.Export.Infrastructure",
                "FoodDiary.Modules.Fasting.Infrastructure",
                "FoodDiary.Modules.Favorites.Infrastructure",
                "FoodDiary.Modules.Gamification.Infrastructure",
                "FoodDiary.Modules.Hydration.Infrastructure",
                "FoodDiary.Modules.Images.Infrastructure",
                "FoodDiary.Modules.Lessons.Infrastructure",
                "FoodDiary.Modules.Marketing.Infrastructure",
                "FoodDiary.Modules.MealPlanning.Infrastructure",
                "FoodDiary.Modules.Notifications.Infrastructure",
                "FoodDiary.Modules.OpenFoodFacts.Infrastructure",
                "FoodDiary.Modules.RecipeCommunity.Infrastructure",
                "FoodDiary.Modules.Statistics.Application",
                "FoodDiary.Modules.Tdee.Application",
                "FoodDiary.Modules.Usda.Infrastructure",
                "FoodDiary.Modules.Wearables.Infrastructure",
                "FoodDiary.Modules.WeeklyCheckIn.Application",
                "FoodDiary.Modules.WeeklyGoals.Infrastructure",
                "FoodDiary.Presentation.Api",
                "FoodDiary.Resources",
                "FoodDiary.Modules.Recipes.Infrastructure",
                "FoodDiary.Modules.Products.Infrastructure",
                "FoodDiary.Modules.RecentItems.Infrastructure",
            ],
            ["FoodDiary.Modules.MealPlanning.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.MealPlanning.Application.Abstractions"] = ["FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.MealPlanning.PersistenceModel"] = ["FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.MealPlanning.Infrastructure"] = ["FoodDiary.Application.MealPlanning", "FoodDiary.Infrastructure", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.MealPlanning.PersistenceModel", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Exercises.Contracts"] = ["FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Exercises.Domain"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Exercises.Infrastructure"] = [
                "FoodDiary.Application.Exercises",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.Exercises.PersistenceModel",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.Exercises.Application.Abstractions"] = ["FoodDiary.Modules.Exercises.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Exercises.PersistenceModel"] = ["FoodDiary.Modules.Exercises.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.RecipeCommunity.Domain"] = ["FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.RecipeCommunity.Application.Abstractions"] = ["FoodDiary.Modules.RecipeCommunity.Domain", "FoodDiary.Results", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.RecipeCommunity.PersistenceModel"] = ["FoodDiary.Modules.RecipeCommunity.Domain", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.RecipeCommunity.Infrastructure"] = [
                "FoodDiary.Application.RecipeCommunity",
                "FoodDiary.Infrastructure",
                "FoodDiary.Modules.RecipeCommunity.PersistenceModel",
                "FoodDiary.Modules.Users.Domain",
            ],
        };

    private static readonly IReadOnlyDictionary<string, string[]> AllowedTestProjectReferences =
        new Dictionary<string, string[]>(StringComparer.Ordinal) {
            ["FoodDiary.Modules.Users.Domain.Tests"] = ["FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Dashboard.Application.Tests"] = ["FoodDiary.Application.BodyMetrics", "FoodDiary.Application.Exercises", "FoodDiary.Modules.Dashboard.Application", "FoodDiary.Modules.Hydration.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Dashboard.Infrastructure.Tests"] = ["FoodDiary.Modules.Dashboard.Infrastructure", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Analyzers.Tests"] = ["FoodDiary.Analyzers"],
            ["FoodDiary.Development.Mcp.Tests"] = ["FoodDiary.Development.Mcp"],
            ["FoodDiary.Application.Tests"] = ["FoodDiary.Application.BodyMetrics", "FoodDiary.Application.Exercises", "FoodDiary.Application.Favorites", "FoodDiary.Application.Notifications", "FoodDiary.Application.RecipeCommunity", "FoodDiary.Application.Runtime", "FoodDiary.Application.Usda", "FoodDiary.Domain.Primitives", "FoodDiary.Modules.Admin.Application", "FoodDiary.Modules.Ai.Application", "FoodDiary.Modules.ContentReports.Application", "FoodDiary.Modules.ContentReports.Application.Abstractions", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Dashboard.Application", "FoodDiary.Modules.Dietologist.Application", "FoodDiary.Modules.Export.Application", "FoodDiary.Modules.Fasting.Contracts", "FoodDiary.Modules.Hydration.Application", "FoodDiary.Modules.Hydration.Infrastructure", "FoodDiary.Modules.Identity.Application", "FoodDiary.Modules.Lessons.Application", "FoodDiary.Modules.Lessons.Application.Abstractions", "FoodDiary.Modules.Lessons.Contracts", "FoodDiary.Modules.OpenFoodFacts.Application", "FoodDiary.Modules.OpenFoodFacts.Application.Abstractions", "FoodDiary.Modules.Products.Application", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Recipes.Application", "FoodDiary.Modules.Statistics.Application", "FoodDiary.Modules.Users.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Billing.Application.Tests"] = ["FoodDiary.Application.Billing", "FoodDiary.Modules.Users.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Usda.Application.Tests"] = ["FoodDiary.Application.Usda", "FoodDiary.Modules.Meals.Application", "FoodDiary.Modules.Meals.Application.Abstractions", "FoodDiary.Modules.Products.Application", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Usda.Domain.Tests"] = ["FoodDiary.Modules.Usda.Domain"],
            ["FoodDiary.Modules.BodyMetrics.Application.Tests"] = [
                "FoodDiary.Application.Abstractions",
                "FoodDiary.Application.BodyMetrics",
                "FoodDiary.Results",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.BodyMetrics.Domain.Tests"] = ["FoodDiary.Modules.BodyMetrics.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Billing.Domain.Tests"] = ["FoodDiary.Modules.Billing.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Billing.Infrastructure.Tests"] = ["FoodDiary.Integrations", "FoodDiary.Modules.Billing.Infrastructure", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.ArchitectureTests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Infrastructure", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Usda.Domain", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Domain.Primitives.Tests"] = ["FoodDiary.Domain.Primitives"],
            ["FoodDiary.Domain.Tests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Ai.Domain", "FoodDiary.Modules.Billing.Domain", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.Dietologist.Domain", "FoodDiary.Modules.Fasting.Domain", "FoodDiary.Modules.Favorites.Domain", "FoodDiary.Modules.Gamification.Domain", "FoodDiary.Modules.Identity.Domain", "FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Notifications.Domain", "FoodDiary.Modules.OpenFoodFacts.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.RecipeCommunity.Domain", "FoodDiary.Modules.Usda.Domain", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Modules.Wearables.Domain"],
            ["FoodDiary.Modules.Favorites.Application.Tests"] = ["FoodDiary.Application.Favorites", "FoodDiary.Domain.Primitives", "FoodDiary.Modules.Meals.Contracts", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Recipes.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Favorites.Domain.Tests"] = ["FoodDiary.Modules.Favorites.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Gamification.Application.Tests"] = ["FoodDiary.Modules.Admin.Application", "FoodDiary.Modules.Gamification.Application", "FoodDiary.Modules.Gamification.Application.Abstractions", "FoodDiary.Modules.Meals.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Gamification.Domain.Tests"] = ["FoodDiary.Modules.Gamification.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Gamification.Infrastructure.Tests"] = ["FoodDiary.Modules.Gamification.Infrastructure", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.DailyAdvices.Application.Tests"] = ["FoodDiary.Modules.Users.Application", "FoodDiary.Modules.DailyAdvices.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Cycles.Application.Tests"] = ["FoodDiary.Modules.Cycles.Domain", "FoodDiary.Application.Cycles", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Cycles.Domain.Tests"] = ["FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Cycles.Infrastructure.Tests"] = ["FoodDiary.Modules.Cycles.Infrastructure"],
            ["FoodDiary.Modules.Cycles.Infrastructure.IntegrationTests"] = [
                "FoodDiary.Modules.Meals.Domain",
                "FoodDiary.Modules.Cycles.Domain",
                "FoodDiary.Initializer",
                "FoodDiary.Modules.Cycles.Infrastructure",
                "FoodDiary.Testing",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Dietologist.Application.Tests"] = [
                "FoodDiary.Modules.Users.Domain.Contracts",
                "FoodDiary.Application.Notifications",
                "FoodDiary.Modules.Users.Application",
                "FoodDiary.Modules.Dashboard.Application",
                "FoodDiary.Modules.Dietologist.Application",
                "FoodDiary.Modules.Hydration.Contracts",
                "FoodDiary.Modules.Meals.Contracts",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Dietologist.Domain.Tests"] = ["FoodDiary.Modules.Dietologist.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Dietologist.Infrastructure.Tests"] = ["FoodDiary.Modules.Dietologist.Infrastructure", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Export.Infrastructure.Tests"] = ["FoodDiary.Modules.Export.Infrastructure", "FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Export.Application.Tests"] = [
                "FoodDiary.Modules.Meals.Domain",
                "FoodDiary.Modules.Cycles.Domain",
                "FoodDiary.Application.Cycles",
                "FoodDiary.Modules.Export.Application",
                "FoodDiary.Modules.Meals.Application",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.DailyAdvices.Domain.Tests"] = ["FoodDiary.Modules.DailyAdvices.Domain"],
            ["FoodDiary.Modules.DailyAdvices.Infrastructure.Tests"] = ["FoodDiary.Modules.DailyAdvices.Infrastructure"],
            ["FoodDiary.Modules.Fasting.Application.Tests"] = ["FoodDiary.Application.Notifications", "FoodDiary.Modules.Fasting.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Fasting.Domain.Tests"] = ["FoodDiary.Modules.Fasting.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Fasting.Infrastructure.Tests"] = [
                "FoodDiary.Initializer",
                "FoodDiary.Modules.Fasting.Infrastructure",
                "FoodDiary.Testing",
            ],
            ["FoodDiary.Modules.Hydration.Application.Tests"] = ["FoodDiary.Modules.Hydration.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Hydration.Domain.Tests"] = ["FoodDiary.Modules.Hydration.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Hydration.Infrastructure.Tests"] = [
                "FoodDiary.Initializer",
                "FoodDiary.Modules.Hydration.Infrastructure",
                "FoodDiary.Testing",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Identity.Application.Tests"] = ["FoodDiary.Application.Notifications", "FoodDiary.Application.Runtime", "FoodDiary.Modules.Dietologist.Application", "FoodDiary.Modules.Identity.Application", "FoodDiary.Modules.Users.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Identity.Domain.Tests"] = ["FoodDiary.Modules.Identity.Domain"],
            ["FoodDiary.Modules.Identity.Infrastructure.Tests"] = ["FoodDiary.Modules.Identity.Infrastructure"],
            ["FoodDiary.Modules.Identity.Infrastructure.IntegrationTests"] = ["FoodDiary.Modules.Identity.Infrastructure", "FoodDiary.Testing", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Images.Application.Tests"] = ["FoodDiary.Application.Images", "FoodDiary.Modules.Users.Application", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Images.Domain.Tests"] = ["FoodDiary.Modules.Images.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Images.Infrastructure.IntegrationTests"] = ["FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Images.Infrastructure", "FoodDiary.Testing", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Lessons.Application.Tests"] = ["FoodDiary.Modules.Lessons.Application", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Lessons.Domain.Tests"] = ["FoodDiary.Modules.Lessons.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Lessons.Infrastructure.Tests"] = ["FoodDiary.Modules.Lessons.Infrastructure"],
            ["FoodDiary.Modules.Meals.Application.Tests"] = ["FoodDiary.Application.Favorites", "FoodDiary.Domain.Primitives", "FoodDiary.Modules.Meals.Application", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Recipes.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Meals.Domain.Tests"] = ["FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Meals.Infrastructure.IntegrationTests"] = ["FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Meals.Infrastructure", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain", "FoodDiary.Testing"],
            ["FoodDiary.Modules.OpenFoodFacts.Application.Tests"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Modules.OpenFoodFacts.Application"],
            ["FoodDiary.Modules.OpenFoodFacts.Domain.Tests"] = ["FoodDiary.Modules.OpenFoodFacts.Domain"],
            ["FoodDiary.Modules.OpenFoodFacts.Infrastructure.Tests"] = ["FoodDiary.Modules.OpenFoodFacts.Infrastructure"],
            ["FoodDiary.Modules.Marketing.Application.Tests"] = ["FoodDiary.Application.Marketing"],
            ["FoodDiary.Modules.Marketing.Domain.Tests"] = ["FoodDiary.Modules.Marketing.Domain"],
            ["FoodDiary.Modules.Marketing.Infrastructure.IntegrationTests"] = [
                "FoodDiary.Initializer",
                "FoodDiary.Modules.Marketing.Infrastructure",
                "FoodDiary.Testing",
            ],
            ["FoodDiary.Modules.ContentReports.Application.Tests"] = ["FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.ContentReports.Application", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.ContentReports.Domain.Tests"] = ["FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.ContentReports.Infrastructure.Tests"] = ["FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.ContentReports.Infrastructure", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Tdee.Application.Tests"] = [
                "FoodDiary.Application.BodyMetrics",
                "FoodDiary.Application.Exercises",
                "FoodDiary.Modules.Tdee.Application",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Statistics.Application.Tests"] = ["FoodDiary.Application.Abstractions", "FoodDiary.Modules.Statistics.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.WeeklyGoals.Application.Tests"] = [
                "FoodDiary.Modules.Users.Application",
                "FoodDiary.Modules.Meals.Contracts",
                "FoodDiary.Modules.WeeklyGoals.Application",
                "FoodDiary.Modules.Users.Domain.Contracts",
            ],
            ["FoodDiary.Modules.WeeklyGoals.Domain.Tests"] = ["FoodDiary.Modules.WeeklyGoals.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.WeeklyGoals.Infrastructure.Tests"] = [
                "FoodDiary.Initializer",
                "FoodDiary.Modules.WeeklyGoals.Infrastructure",
                "FoodDiary.Testing",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Modules.Wearables.Application.Tests"] = ["FoodDiary.Application.Wearables", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Wearables.Domain.Tests"] = ["FoodDiary.Modules.Wearables.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Wearables.Infrastructure.Tests"] = ["FoodDiary.Modules.Wearables.Infrastructure", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Wearables.Infrastructure.IntegrationTests"] = ["FoodDiary.Modules.Wearables.Infrastructure", "FoodDiary.Testing", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.WeeklyCheckIn.Application.Tests"] = [
                "FoodDiary.Modules.Users.Application",
                "FoodDiary.Modules.Meals.Contracts",
                "FoodDiary.Modules.WeeklyCheckIn.Application",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.Infrastructure.IntegrationTests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Infrastructure", "FoodDiary.Initializer", "FoodDiary.Integrations", "FoodDiary.Modules.Admin.Infrastructure", "FoodDiary.Modules.Ai.Infrastructure", "FoodDiary.Modules.Billing.Infrastructure", "FoodDiary.Modules.BodyMetrics.Infrastructure", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.ContentReports.Infrastructure", "FoodDiary.Modules.DailyAdvices.Infrastructure", "FoodDiary.Modules.Dashboard.Infrastructure", "FoodDiary.Modules.Dietologist.Infrastructure", "FoodDiary.Modules.Exercises.Infrastructure", "FoodDiary.Modules.Fasting.Infrastructure", "FoodDiary.Modules.Favorites.Infrastructure", "FoodDiary.Modules.Gamification.Infrastructure", "FoodDiary.Modules.Hydration.Infrastructure", "FoodDiary.Modules.Lessons.Application.Abstractions", "FoodDiary.Modules.Lessons.Contracts", "FoodDiary.Modules.Lessons.Infrastructure", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.MealPlanning.Infrastructure", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Notifications.Infrastructure", "FoodDiary.Modules.OpenFoodFacts.Infrastructure", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Products.Infrastructure", "FoodDiary.Modules.RecentItems.Infrastructure", "FoodDiary.Modules.RecipeCommunity.Infrastructure", "FoodDiary.Modules.Recipes.Infrastructure", "FoodDiary.Modules.Usda.Infrastructure", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Infrastructure", "FoodDiary.Modules.Wearables.Infrastructure", "FoodDiary.Modules.WeeklyGoals.Infrastructure", "FoodDiary.Testing"],
            ["FoodDiary.Infrastructure.Tests"] = ["FoodDiary.Application.BodyMetrics", "FoodDiary.Application.Exercises", "FoodDiary.Application.MealPlanning", "FoodDiary.Application.Notifications", "FoodDiary.Application.RecipeCommunity", "FoodDiary.Infrastructure", "FoodDiary.Initializer", "FoodDiary.Integrations", "FoodDiary.Modules.Admin.Infrastructure", "FoodDiary.Modules.Ai.Infrastructure", "FoodDiary.Modules.Billing.Infrastructure", "FoodDiary.Modules.BodyMetrics.Infrastructure", "FoodDiary.Modules.ContentReports.Infrastructure", "FoodDiary.Modules.Cycles.Infrastructure", "FoodDiary.Modules.Dashboard.Infrastructure", "FoodDiary.Modules.Dietologist.Infrastructure", "FoodDiary.Modules.Exercises.Infrastructure", "FoodDiary.Modules.Fasting.Infrastructure", "FoodDiary.Modules.Hydration.Infrastructure", "FoodDiary.Modules.Identity.Application", "FoodDiary.Modules.Lessons.Infrastructure", "FoodDiary.Modules.MealPlanning.Infrastructure", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Notifications.Infrastructure", "FoodDiary.Modules.OpenFoodFacts.Application.Abstractions", "FoodDiary.Modules.OpenFoodFacts.Contracts", "FoodDiary.Modules.OpenFoodFacts.Infrastructure", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Products.Infrastructure", "FoodDiary.Modules.RecentItems.Infrastructure", "FoodDiary.Modules.RecipeCommunity.Infrastructure", "FoodDiary.Modules.Recipes.Infrastructure", "FoodDiary.Modules.Tdee.Application", "FoodDiary.Modules.Usda.Infrastructure", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Infrastructure", "FoodDiary.Modules.Wearables.Infrastructure"],
            ["FoodDiary.JobManager.Tests"] = [
                "FoodDiary.Application.Billing",
                "FoodDiary.Application.BodyMetrics",
                "FoodDiary.Application.Exercises",
                "FoodDiary.Modules.Identity.Application",
                "FoodDiary.Application.Images",
                "FoodDiary.Application.MealPlanning",
                "FoodDiary.Application.Notifications",
                "FoodDiary.Application.RecipeCommunity",
                "FoodDiary.JobManager",
                "FoodDiary.Modules.Billing.Infrastructure",
                "FoodDiary.Modules.Dietologist.Infrastructure",
                "FoodDiary.Modules.Fasting.Application",
                "FoodDiary.Modules.Fasting.Contracts",
                "FoodDiary.Modules.Favorites.Infrastructure",
                "FoodDiary.Modules.OpenFoodFacts.Application",
                "FoodDiary.Modules.Tdee.Application",
                "FoodDiary.Modules.WeeklyGoals.Application",
                "FoodDiary.Modules.WeeklyGoals.Infrastructure",
                "FoodDiary.Modules.Products.Infrastructure",
                "FoodDiary.Modules.Users.Domain",
            ],
            ["FoodDiary.MailInbox.Application.Tests"] = ["FoodDiary.MailInbox.Application", "FoodDiary.MailInbox.Domain"],
            ["FoodDiary.MailInbox.Client.Tests"] = ["FoodDiary.MailInbox.Client"],
            ["FoodDiary.MailInbox.Domain.Tests"] = ["FoodDiary.MailInbox.Domain"],
            ["FoodDiary.MailInbox.Infrastructure.Tests"] = [
                "FoodDiary.MailInbox.Application",
                "FoodDiary.MailInbox.Domain",
                "FoodDiary.MailInbox.Infrastructure",
            ],
            ["FoodDiary.MailInbox.Initializer.Tests"] = ["FoodDiary.MailInbox.Initializer"],
            ["FoodDiary.MailInbox.IntegrationTests"] = [
                "FoodDiary.MailInbox.Application",
                "FoodDiary.MailInbox.Domain",
                "FoodDiary.MailInbox.Infrastructure",
                "FoodDiary.MailInbox.WebApi",
                "FoodDiary.Testing",
            ],
            ["FoodDiary.MailInbox.Presentation.Tests"] = [
                "FoodDiary.MailInbox.Application",
                "FoodDiary.MailInbox.Domain",
                "FoodDiary.MailInbox.Presentation",
            ],
            ["FoodDiary.MailRelay.Application.Tests"] = ["FoodDiary.MailRelay.Application", "FoodDiary.MailRelay.Domain"],
            ["FoodDiary.MailRelay.Client.Tests"] = ["FoodDiary.MailRelay.Client"],
            ["FoodDiary.MailRelay.Domain.Tests"] = ["FoodDiary.MailRelay.Domain"],
            ["FoodDiary.MailRelay.Infrastructure.Tests"] = [
                "FoodDiary.MailRelay.Application",
                "FoodDiary.MailRelay.Client",
                "FoodDiary.MailRelay.Domain",
                "FoodDiary.MailRelay.Infrastructure",
            ],
            ["FoodDiary.MailRelay.Initializer.Tests"] = ["FoodDiary.MailRelay.Initializer"],
            ["FoodDiary.MailRelay.IntegrationTests"] = [
                "FoodDiary.MailRelay.Application",
                "FoodDiary.MailRelay.Domain",
                "FoodDiary.MailRelay.Infrastructure",
                "FoodDiary.MailRelay.WebApi",
                "FoodDiary.Testing",
            ],
            ["FoodDiary.MailRelay.Presentation.Tests"] = [
                "FoodDiary.MailRelay.Application",
                "FoodDiary.MailRelay.Client",
                "FoodDiary.MailRelay.Domain",
                "FoodDiary.MailRelay.Presentation",
            ],
            ["FoodDiary.Mediator.Tests"] = ["FoodDiary.Mediator"],
            ["FoodDiary.Presentation.Api.Tests"] = ["FoodDiary.Application.Billing", "FoodDiary.Application.BodyMetrics", "FoodDiary.Application.Cycles", "FoodDiary.Application.Exercises", "FoodDiary.Application.Favorites", "FoodDiary.Application.Images", "FoodDiary.Application.MealPlanning", "FoodDiary.Application.Notifications", "FoodDiary.Application.RecipeCommunity", "FoodDiary.Application.Usda", "FoodDiary.Application.Wearables", "FoodDiary.Domain.Primitives", "FoodDiary.Modules.Admin.Application", "FoodDiary.Modules.Ai.Application", "FoodDiary.Modules.ContentReports.Application", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.DailyAdvices.Application", "FoodDiary.Modules.Dashboard.Application", "FoodDiary.Modules.Dietologist.Application", "FoodDiary.Modules.Export.Application", "FoodDiary.Modules.Fasting.Application", "FoodDiary.Modules.Fasting.Contracts", "FoodDiary.Modules.Gamification.Application", "FoodDiary.Modules.Hydration.Application", "FoodDiary.Modules.Identity.Application", "FoodDiary.Modules.Lessons.Application", "FoodDiary.Modules.Meals.Application", "FoodDiary.Modules.OpenFoodFacts.Application", "FoodDiary.Modules.Statistics.Application", "FoodDiary.Modules.Tdee.Application", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.WeeklyCheckIn.Application", "FoodDiary.Modules.WeeklyGoals.Application", "FoodDiary.Presentation.Api"],
            ["FoodDiary.Resources.Tests"] = ["FoodDiary.Modules.Export.Application.Abstractions", "FoodDiary.Resources"],
            ["FoodDiary.Modules.Notifications.Application.Tests"] = ["FoodDiary.Application.Notifications", "FoodDiary.Modules.Users.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Notifications.Domain.Tests"] = ["FoodDiary.Modules.Notifications.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Notifications.Infrastructure.Tests"] = ["FoodDiary.Application.Notifications", "FoodDiary.Modules.Notifications.Infrastructure", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Users.Application.Tests"] = ["FoodDiary.Application.BodyMetrics", "FoodDiary.Application.Notifications", "FoodDiary.Application.Runtime", "FoodDiary.Modules.Admin.Application", "FoodDiary.Modules.ContentReports.Application", "FoodDiary.Modules.ContentReports.Contracts", "FoodDiary.Modules.ContentReports.Domain", "FoodDiary.Modules.Dashboard.Application", "FoodDiary.Modules.Dietologist.Application", "FoodDiary.Modules.Hydration.Application", "FoodDiary.Modules.Identity.Application", "FoodDiary.Modules.Lessons.Application", "FoodDiary.Modules.Lessons.Contracts", "FoodDiary.Modules.Lessons.Domain", "FoodDiary.Modules.Users.Application", "FoodDiary.Modules.Users.Domain", "FoodDiary.Modules.Users.Domain.Contracts", "FoodDiary.Modules.Users.Infrastructure"],
            ["FoodDiary.Results.Tests"] = ["FoodDiary.Results"],
            ["FoodDiary.Telegram.Bot.Tests"] = ["FoodDiary.Telegram.Bot"],
            ["FoodDiary.Testing"] = [],
            ["FoodDiary.Web.Api.IntegrationTests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Infrastructure", "FoodDiary.Modules.Cycles.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain", "FoodDiary.Presentation.Api", "FoodDiary.Testing", "FoodDiary.Web.Api"],
            ["FoodDiary.Web.Api.Tests"] = [
                "FoodDiary.Integrations",
                "FoodDiary.Presentation.Api",
                "FoodDiary.Web.Api",
            ],
            ["FoodDiary.Modules.MealPlanning.Application.Tests"] = ["FoodDiary.Application.MealPlanning", "FoodDiary.Domain.Primitives", "FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.MealPlanning.Domain.Tests"] = ["FoodDiary.Modules.MealPlanning.Domain", "FoodDiary.Modules.Meals.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.MealPlanning.Infrastructure.IntegrationTests"] = ["FoodDiary.Infrastructure", "FoodDiary.Modules.MealPlanning.Infrastructure", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain", "FoodDiary.Testing"],
            ["FoodDiary.Modules.Admin.Application.Tests"] = ["FoodDiary.Modules.Admin.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Admin.Domain.Tests"] = ["FoodDiary.Modules.Admin.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Ai.Application.Tests"] = ["FoodDiary.Modules.Ai.Application", "FoodDiary.Application.Images", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Ai.Domain.Tests"] = ["FoodDiary.Modules.Ai.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Ai.Infrastructure.Tests"] = ["FoodDiary.Modules.Ai.Infrastructure", "FoodDiary.Integrations", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Exercises.Application.Tests"] = ["FoodDiary.Application.Exercises", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Exercises.Domain.Tests"] = ["FoodDiary.Modules.Exercises.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Products.Application.Tests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Products.Application", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Products.Domain.Tests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Products.Infrastructure.IntegrationTests"] = ["FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Products.Infrastructure", "FoodDiary.Modules.Users.Domain", "FoodDiary.Testing"],
            ["FoodDiary.Modules.RecentItems.Domain.Tests"] = ["FoodDiary.Modules.RecentItems.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.RecentItems.Infrastructure.IntegrationTests"] = ["FoodDiary.Modules.RecentItems.Infrastructure", "FoodDiary.Testing", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.RecentItems.Infrastructure.Tests"] = ["FoodDiary.Modules.RecentItems.Infrastructure", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.Recipes.Application.Tests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Products.Domain", "FoodDiary.Modules.Products.Domain.Contracts", "FoodDiary.Modules.Recipes.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.Recipes.Domain.Tests"] = ["FoodDiary.Domain.Primitives", "FoodDiary.Modules.Recipes.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
            ["FoodDiary.Modules.RecipeCommunity.Application.Tests"] = ["FoodDiary.Application.RecipeCommunity", "FoodDiary.Domain.Primitives", "FoodDiary.Modules.Recipes.Application", "FoodDiary.Modules.Users.Domain"],
            ["FoodDiary.Modules.RecipeCommunity.Domain.Tests"] = ["FoodDiary.Modules.RecipeCommunity.Domain", "FoodDiary.Modules.Users.Domain.Contracts"],
        };

    [Fact]
    public void AllProductionProjects_AreCoveredByDependencyMatrix() {
        IReadOnlyList<string> actualProjects = ProjectReferenceReader.ReadProductionProjectNames();
        string[] expectedProjects = [.. AllowedProductionProjectReferences.Keys.Order(StringComparer.Ordinal)];

        Assert.Equal(expectedProjects, actualProjects);
    }

    [Fact]
    public void ProductionProjectReferences_MatchDependencyMatrix() {
        IReadOnlyDictionary<string, string[]> actualReferencesByProject = ProjectReferenceReader.ReadProductionProjectReferences();

        foreach ((string? projectName, string[]? expectedReferences) in AllowedProductionProjectReferences) {
            Assert.True(
                actualReferencesByProject.TryGetValue(projectName, out string[]? actualReferences),
                $"Project '{projectName}' is missing from discovered production projects.");

            Assert.Equal(
                expectedReferences.Order(StringComparer.Ordinal).ToArray(),
                actualReferences);
        }
    }

    [Fact]
    public void AllTestProjects_AreCoveredByDependencyMatrix() {
        IReadOnlyList<string> actualProjects = ProjectReferenceReader.ReadTestProjectNames();
        string[] expectedProjects = [.. AllowedTestProjectReferences.Keys.Order(StringComparer.Ordinal)];

        Assert.Equal(expectedProjects, actualProjects);
    }

    [Fact]
    public void TestProjectReferences_MatchDependencyMatrix() {
        IReadOnlyDictionary<string, string[]> actualReferencesByProject = ProjectReferenceReader.ReadTestProjectReferences();

        foreach ((string? projectName, string[]? expectedReferences) in AllowedTestProjectReferences) {
            Assert.True(
                actualReferencesByProject.TryGetValue(projectName, out string[]? actualReferences),
                $"Test project '{projectName}' is missing from discovered test projects.");

            Assert.Equal(
                expectedReferences.Order(StringComparer.Ordinal).ToArray(),
                actualReferences);
        }
    }

    [Fact]
    public void CoreProjects_ReferenceMailBoundedContextsOnlyThroughAllowedClientProjects() {
        IReadOnlyDictionary<string, string[]> actualReferencesByProject = ProjectReferenceReader.ReadProductionProjectReferences();
        string[] coreProjects = [.. actualReferencesByProject.Keys
            .Where(static projectName => !projectName.StartsWith("FoodDiary.MailRelay.", StringComparison.Ordinal))
            .Where(static projectName => !projectName.StartsWith("FoodDiary.MailInbox.", StringComparison.Ordinal))];

        var allowedMailClientReferences = new HashSet<string>(StringComparer.Ordinal) {
            "FoodDiary.MailInbox.Client",
            "FoodDiary.MailRelay.Client",
        };

        string[] violations = [.. coreProjects
            .SelectMany(projectName => actualReferencesByProject[projectName]
                .Where(static reference => reference.StartsWith("FoodDiary.MailRelay.", StringComparison.Ordinal) ||
                                           reference.StartsWith("FoodDiary.MailInbox.", StringComparison.Ordinal))
                .Where(reference => !allowedMailClientReferences.Contains(reference) ||
                                    !string.Equals(projectName, "FoodDiary.Integrations", StringComparison.Ordinal))
                .Select(reference => $"{projectName} -> {reference}"))
            .Order(StringComparer.Ordinal)];

        Assert.Empty(violations);
    }

    [Fact]
    public void CoreProjectSource_ReferencesMailBoundedContextsOnlyFromIntegrations() {
        string[] coreSourceRoots = [.. ProjectReferenceReader.ReadProductionProjectNames()
            .Where(static projectName => !projectName.StartsWith("FoodDiary.MailRelay.", StringComparison.Ordinal))
            .Where(static projectName => !projectName.StartsWith("FoodDiary.MailInbox.", StringComparison.Ordinal))
            .Where(static projectName => !string.Equals(projectName, "FoodDiary.Integrations", StringComparison.Ordinal))
            .Select(projectName => ArchitectureTestPaths.FromRoot(ProjectFolderFromProjectName(projectName)))];

        string[] violations = SourceScanner.FindLinePatternViolations(coreSourceRoots, [
            "FoodDiary.MailInbox",
            "FoodDiary.MailRelay",
        ]);

        Assert.Empty(violations);
    }

    private static string ProjectFolderFromProjectName(string projectName) =>
        projectName switch {
            "FoodDiary.Mediator" => Path.Combine("Shared", "FoodDiary.Mediator"),
            "FoodDiary.Results" => Path.Combine("Shared", "FoodDiary.Results"),
            "FoodDiary.Domain.Primitives" => Path.Combine("Shared", "FoodDiary.Domain.Primitives"),
            _ => projectName,
        };
}
