export const RECENT_MEASUREMENT_LIMIT = 5;
export const RECENT_MEASUREMENT_FETCH_LIMIT = RECENT_MEASUREMENT_LIMIT + 1;
export const MEASUREMENT_HISTORY_PAGE_SIZE = 20;
export const MEASUREMENT_HISTORY_FETCH_LIMIT = MEASUREMENT_HISTORY_PAGE_SIZE + 1;
