<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Modules\Notifications\Application\Abstractions\FoodDiary.Modules.Notifications.Application.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Usda\Application\Abstractions\FoodDiary.Modules.Usda.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\BodyMetrics\Application\Abstractions\FoodDiary.Modules.BodyMetrics.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Billing\Application\Abstractions\FoodDiary.Modules.Billing.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Marketing\Application\Abstractions\FoodDiary.Modules.Marketing.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Wearables\Application\Abstractions\FoodDiary.Modules.Wearables.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Favorites\Domain\FoodDiary.Modules.Favorites.Domain.csproj" />
    <ProjectReference Include="..\Modules\Cycles\Application\Abstractions\FoodDiary.Modules.Cycles.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Images\Application\Abstractions\FoodDiary.Modules.Images.Application.Abstractions.csproj" />
    <ProjectReference Include="..\FoodDiary.Domain\FoodDiary.Domain.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Domain.Primitives\FoodDiary.Domain.Primitives.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Mediator\FoodDiary.Mediator.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Results\FoodDiary.Results.csproj" />
  </ItemGroup>

</Project>
