<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Modules/Products/Domain.Contracts/FoodDiary.Modules.Products.Domain.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Identity\Domain\FoodDiary.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\Modules\Notifications\Application\Abstractions\FoodDiary.Modules.Notifications.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Usda\Application\Abstractions\FoodDiary.Modules.Usda.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\BodyMetrics\Application\Abstractions\FoodDiary.Modules.BodyMetrics.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Billing\Application\Abstractions\FoodDiary.Modules.Billing.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Marketing\Application\Abstractions\FoodDiary.Modules.Marketing.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Wearables\Application\Abstractions\FoodDiary.Modules.Wearables.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Favorites\Domain\FoodDiary.Modules.Favorites.Domain.csproj" />
    <ProjectReference Include="..\Modules\Cycles\Application\Abstractions\FoodDiary.Modules.Cycles.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Images\Application\Abstractions\FoodDiary.Modules.Images.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Domain.Primitives\FoodDiary.Domain.Primitives.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Mediator\FoodDiary.Mediator.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Results\FoodDiary.Results.csproj" />
    <ProjectReference Include="..\Modules\MealPlanning\Application\Abstractions\FoodDiary.Modules.MealPlanning.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\Exercises\Application\Abstractions\FoodDiary.Modules.Exercises.Application.Abstractions.csproj" />
    <ProjectReference Include="../Modules/RecipeCommunity/Application/Abstractions/FoodDiary.Modules.RecipeCommunity.Application.Abstractions.csproj" />
    <ProjectReference Include="../Modules/Ai/Application/Abstractions/FoodDiary.Modules.Ai.Application.Abstractions.csproj" />
    <ProjectReference Include="../Modules/Dashboard/Contracts/FoodDiary.Modules.Dashboard.Contracts.csproj" />
    <ProjectReference Include="../Modules/Recipes/Application/Abstractions/FoodDiary.Modules.Recipes.Application.Abstractions.csproj" />
    <ProjectReference Include="../Modules/Recipes/Contracts/FoodDiary.Modules.Recipes.Contracts.csproj" />
    <ProjectReference Include="../Modules/Admin/Application/Abstractions/FoodDiary.Modules.Admin.Application.Abstractions.csproj" />
    <ProjectReference Include="../Modules/Products/Application/Abstractions/FoodDiary.Modules.Products.Application.Abstractions.csproj" />
    <ProjectReference Include="../Modules/Products/Contracts/FoodDiary.Modules.Products.Contracts.csproj" />
    <ProjectReference Include="../Modules/Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>


</Project>
