namespace FoodDiary.Application.Abstractions.WeightEntries.Common;

public interface IWeightEntryRepository : IWeightEntryReadRepository, IWeightEntryReadModelRepository, IWeightEntryWriteRepository;
