<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Application.Tdee</RootNamespace><NoWarn>$(NoWarn);IDE0130</NoWarn></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Shared/FoodDiary.Results/FoodDiary.Results.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
