namespace FoodDiary.Modules.Identity.Application.Abstractions.Authentication.Common;

public interface IRefreshTokenSessionRepository : IRefreshTokenSessionReadRepository, IRefreshTokenSessionWriteRepository;
