namespace FoodDiary.Application.Abstractions.Marketing.Common;

public interface IMarketingAttributionEventRepository : IMarketingAttributionEventReadRepository, IMarketingAttributionEventWriteRepository;
