namespace FoodDiary.Modules.Lessons.Application.Abstractions.Common;

public interface INutritionLessonRepository : INutritionLessonReadRepository, INutritionLessonReadModelRepository, INutritionLessonWriteRepository;
