<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>FoodDiary.Application.Tests</AssemblyName><RootNamespace>FoodDiary.Application.Tests</RootNamespace></PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="NSubstitute" />
    <Using Include="FoodDiary.Application.Tests.Support" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Domain.Primitives\FoodDiary.Domain.Primitives.csproj" />
    <ProjectReference Include="..\..\..\Products\Domain\FoodDiary.Modules.Products.Domain.csproj" />
    <ProjectReference Include="../../../Products/Domain.Contracts/FoodDiary.Modules.Products.Domain.Contracts.csproj" />
    <ProjectReference Include="../../Domain/FoodDiary.Modules.Meals.Domain.csproj" />
    <ProjectReference Include="../../Application/FoodDiary.Modules.Meals.Application.csproj" />
    <ProjectReference Include="../../../Favorites/Application/FoodDiary.Application.Favorites.csproj" />
    <ProjectReference Include="../../../Recipes/Application/FoodDiary.Modules.Recipes.Application.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../../../Products/Contracts/FoodDiary.Modules.Products.Contracts.csproj" />
    <ProjectReference Include="../../../Recipes/Contracts/FoodDiary.Modules.Recipes.Contracts.csproj" />
    <ProjectReference Include="../../../Favorites/Application/Abstractions/FoodDiary.Modules.Favorites.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Images/Application/Abstractions/FoodDiary.Modules.Images.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Application/Abstractions/FoodDiary.Modules.Meals.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Nutrition.Contracts\FoodDiary.Nutrition.Contracts.csproj" />
  </ItemGroup>
</Project>
