<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>FoodDiary.Application.Tests</AssemblyName><RootNamespace>FoodDiary.Application.Tests</RootNamespace><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup><PackageReference Include="coverlet.collector" /><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="NSubstitute" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" /></ItemGroup>
  <ItemGroup><Using Include="System.Diagnostics.CodeAnalysis" /><Using Include="FoodDiary.Application.Tests.Support" /><Using Include="NSubstitute" /><Using Include="Xunit" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Application\FoodDiary.Modules.Dietologist.Application.csproj" />
    <ProjectReference Include="..\..\..\..\Modules\Users\Application\FoodDiary.Modules.Users.Application.csproj" />
    <ProjectReference Include="../../../Dashboard/Application/FoodDiary.Modules.Dashboard.Application.csproj" />
    <ProjectReference Include="../../../Meals/Contracts/FoodDiary.Modules.Meals.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Modules\Notifications\Application\FoodDiary.Application.Notifications.csproj" />
    <ProjectReference Include="..\..\..\Hydration\Contracts\FoodDiary.Modules.Hydration.Contracts.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>
</Project>
