namespace FoodDiary.Application.Abstractions.ShoppingLists.Common;

public interface IShoppingListRepository : IShoppingListReadRepository, IShoppingListReadModelRepository, IShoppingListWriteRepository;
