<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FoodDiary.Application.Abstractions\FoodDiary.Application.Abstractions.csproj" />
    <ProjectReference Include="..\FoodDiary.Domain\FoodDiary.Domain.csproj" />
    <ProjectReference Include="..\Modules\Fasting\Domain\FoodDiary.Modules.Fasting.Domain.csproj" />
    <ProjectReference Include="..\Modules\Fasting\Infrastructure\Model\FoodDiary.Modules.Fasting.PersistenceModel.csproj" />
    <ProjectReference Include="..\Modules\Hydration\Infrastructure\Model\FoodDiary.Modules.Hydration.PersistenceModel.csproj" />
    <ProjectReference Include="..\Modules\DailyAdvices\Domain\FoodDiary.Modules.DailyAdvices.Domain.csproj" />
    <ProjectReference Include="..\Modules\DailyAdvices\Infrastructure\Model\FoodDiary.Modules.DailyAdvices.PersistenceModel.csproj" />
    <ProjectReference Include="..\Modules\Lessons\Domain\FoodDiary.Modules.Lessons.Domain.csproj" />
    <ProjectReference Include="..\Modules\ContentReports\Domain\FoodDiary.Modules.ContentReports.Domain.csproj" />
    <ProjectReference Include="..\Modules\ContentReports\Infrastructure\Model\FoodDiary.Modules.ContentReports.PersistenceModel.csproj" />
    <ProjectReference Include="..\Modules\Lessons\Infrastructure\Model\FoodDiary.Modules.Lessons.PersistenceModel.csproj" />
    <ProjectReference Include="..\Modules\WeeklyGoals\Domain\FoodDiary.Modules.WeeklyGoals.Domain.csproj" />
    <ProjectReference Include="..\Modules\WeeklyGoals\Infrastructure\Model\FoodDiary.Modules.WeeklyGoals.PersistenceModel.csproj" />
    <ProjectReference Include="..\Modules\Images\Infrastructure\Model\FoodDiary.Modules.Images.PersistenceModel.csproj" />
    <ProjectReference Include="..\Modules\Dietologist\Domain\FoodDiary.Modules.Dietologist.Domain.csproj" />
    <ProjectReference Include="..\Modules\Dietologist\Infrastructure\Model\FoodDiary.Modules.Dietologist.PersistenceModel.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Mediator\FoodDiary.Mediator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" VersionOverride="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" VersionOverride="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" VersionOverride="5.9.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

</Project>
