using System.Diagnostics.CodeAnalysis;

namespace FoodDiary.Development.Mcp.Wiki;

[ExcludeFromCodeCoverage]
public sealed record ContextRoutingHealth(
    int SampleCount,
    int SqlitePrimaryCount,
    int SqliteUnavailableCount,
    double SqliteUnavailableRate,
    int JsonFallbackCount,
    double JsonFallbackRate,
    int SqliteNoCandidateFallbackCount,
    double P50Milliseconds,
    double P95Milliseconds,
    DateTimeOffset? OldestSampleAtUtc,
    DateTimeOffset? LatestSampleAtUtc,
    IReadOnlyDictionary<string, int> FallbackReasonCounts,
    int RefreshAttemptCount,
    int RefreshSuccessCount,
    int RefreshFailureCount,
    int ConsecutiveSqlitePrimaryCount,
    int RetentionLimit,
    int MinimumRetirementSamples,
    double MaximumRetirementJsonFallbackRate,
    int RequiredRetirementSampleCount,
    int MinimumAdditionalSqlitePrimarySamplesRequired,
    bool JsonFallbackRetirementReady,
    bool PersistenceHealthy,
    long PersistenceFailures,
    DateTimeOffset? LastPersistenceFailureAtUtc) {
    public static ContextRoutingHealth Empty { get; } = new(
        SampleCount: 0,
        SqlitePrimaryCount: 0,
        SqliteUnavailableCount: 0,
        SqliteUnavailableRate: 0,
        JsonFallbackCount: 0,
        JsonFallbackRate: 0,
        SqliteNoCandidateFallbackCount: 0,
        P50Milliseconds: 0,
        P95Milliseconds: 0,
        OldestSampleAtUtc: null,
        LatestSampleAtUtc: null,
        FallbackReasonCounts: new Dictionary<string, int>(StringComparer.Ordinal),
        RefreshAttemptCount: 0,
        RefreshSuccessCount: 0,
        RefreshFailureCount: 0,
        ConsecutiveSqlitePrimaryCount: 0,
        RetentionLimit: 0,
        MinimumRetirementSamples: 100,
        MaximumRetirementJsonFallbackRate: 0.01,
        RequiredRetirementSampleCount: 100,
        MinimumAdditionalSqlitePrimarySamplesRequired: 100,
        JsonFallbackRetirementReady: false,
        PersistenceHealthy: true,
        PersistenceFailures: 0,
        LastPersistenceFailureAtUtc: null);
}
