<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\ContentReports\Domain\FoodDiary.Modules.ContentReports.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Gamification\Domain\FoodDiary.Modules.Gamification.Domain.csproj" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FoodDiary.Domain\FoodDiary.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Favorites\Domain\FoodDiary.Modules.Favorites.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Dietologist\Domain\FoodDiary.Modules.Dietologist.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Fasting\Domain\FoodDiary.Modules.Fasting.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Cycles\Domain\FoodDiary.Modules.Cycles.Domain.csproj" />
  </ItemGroup>

</Project>
