<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoodDiary.Application.Fasting</AssemblyName>
    <RootNamespace>FoodDiary.Modules.Fasting.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Abstractions\FoodDiary.Modules.Fasting.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Contracts\FoodDiary.Modules.Fasting.Contracts.csproj" />
    <ProjectReference Include="..\Domain\FoodDiary.Modules.Fasting.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\FoodDiary.Mediator\FoodDiary.Mediator.csproj" />
    <ProjectReference Include="../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../../Notifications/Application/Abstractions/FoodDiary.Modules.Notifications.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
