namespace FoodDiary.Application.Abstractions.Billing.Common;

public interface IBillingSubscriptionRepository : IBillingSubscriptionReadRepository, IBillingSubscriptionReadModelRepository, IBillingSubscriptionWriteRepository;
