<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Application.Abstractions/FoodDiary.Modules.Lessons.Application.Abstractions.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.Lessons.Application.csproj" />
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Lessons.Contracts.csproj" />
    <ProjectReference Include="../Domain.Contracts/FoodDiary.Modules.Lessons.Domain.Contracts.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Lessons.Domain.csproj" />
    <ProjectReference Include="../PersistenceModel/FoodDiary.Modules.Lessons.PersistenceModel.csproj" />
    <ProjectReference Include="../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
  </ItemGroup>
</Project>
