namespace FoodDiary.Application.Abstractions.FavoriteProducts.Common;

public interface IFavoriteProductRepository : IFavoriteProductReadRepository, IFavoriteProductReadModelRepository, IFavoriteProductWriteRepository;
