namespace FoodDiary.Application.Abstractions.Hydration.Common;

public interface IHydrationEntryRepository : IHydrationEntryReadRepository, IHydrationEntryReadModelRepository, IHydrationEntryWriteRepository;