<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>FoodDiary.Modules.Cycles.Infrastructure.IntegrationTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Domain/FoodDiary.Modules.Cycles.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\FoodDiary.Modules.Cycles.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\FoodDiary.Initializer\FoodDiary.Initializer.csproj" />
    <ProjectReference Include="..\..\..\..\tests\FoodDiary.Testing\FoodDiary.Testing.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\..\tests\FoodDiary.Infrastructure.IntegrationTests\Integration\PostgresDatabaseCollection.cs" Link="Support\PostgresDatabaseCollection.cs" />
    <Compile Include="..\..\..\..\tests\FoodDiary.Infrastructure.IntegrationTests\Integration\PostgresDatabaseFixture.cs" Link="Support\PostgresDatabaseFixture.cs" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="FoodDiary.Testing" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
