<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.WeeklyGoals.Contracts</AssemblyName>
    <RootNamespace>FoodDiary.Modules.WeeklyGoals.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FoodDiary.Domain\FoodDiary.Domain.csproj" />
  </ItemGroup>

</Project>
