<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Modules/Admin/Application/Abstractions/FoodDiary.Modules.Admin.Application.Abstractions.csproj" />
    <ProjectReference Include="../Modules/Billing/Application/Abstractions/FoodDiary.Modules.Billing.Application.Abstractions.csproj" />
    <ProjectReference Include="..\MailInbox\FoodDiary.MailInbox.Client\FoodDiary.MailInbox.Client.csproj" />
    <ProjectReference Include="..\MailRelay\FoodDiary.MailRelay.Client\FoodDiary.MailRelay.Client.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="..\Shared\FoodDiary.Email.Contracts\FoodDiary.Email.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Stripe.net" />
  </ItemGroup>

</Project>
