<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FoodDiary.Presentation.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Favorites/Domain.Contracts/FoodDiary.Modules.Favorites.Domain.Contracts.csproj" />
    <ProjectReference Include="../../Favorites/Presentation/FoodDiary.Modules.Favorites.Presentation.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../FoodDiary.Presentation.Api/FoodDiary.Presentation.Api.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.Recipes.Application.csproj" />
    <ProjectReference Include="../Application/Abstractions/FoodDiary.Modules.Recipes.Application.Abstractions.csproj" />
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Recipes.Contracts.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Recipes.Domain.csproj" />
    <ProjectReference Include="../Domain.Contracts/FoodDiary.Modules.Recipes.Domain.Contracts.csproj" />
  </ItemGroup>

</Project>
