<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Application.Abstractions/FoodDiary.Modules.Users.Application.Abstractions.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.Users.Application.csproj" />
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="../Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../PersistenceModel/FoodDiary.Modules.Users.PersistenceModel.csproj" />
    <ProjectReference Include="../../Images/Contracts/FoodDiary.Modules.Images.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Authentication.Contracts/FoodDiary.Authentication.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
