namespace FoodDiary.Presentation.Api.Features.Recipes.Requests;

public sealed record UpdateRecipeHttpRequest(
    string? Name,
    string? Description,
    bool ClearDescription,
    string? Comment,
    bool ClearComment,
    string? Category,
    bool ClearCategory,
    string? ImageUrl,
    bool ClearImageUrl,
    Guid? ImageAssetId,
    bool ClearImageAssetId,
    int? PrepTime,
    int? CookTime,
    int? Servings,
    string? Visibility,
    bool CalculateNutritionAutomatically,
    double? ManualCalories,
    double? ManualProteins,
    double? ManualFats,
    double? ManualCarbs,
    double? ManualFiber,
    double? ManualAlcohol,
    IReadOnlyList<RecipeStepHttpRequest>? Steps);
