<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>FoodDiary.Modules.ContentReports.Domain</AssemblyName><RootNamespace>FoodDiary.Domain</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\FoodDiary.Domain\FoodDiary.Domain.csproj" />
    <ProjectReference Include="../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>
</Project>
