<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FoodDiary.Application.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Application/FoodDiary.Application.RecipeCommunity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /><Using Include="NSubstitute" /></ItemGroup>
  <ItemGroup><Using Include="FoodDiary.Application.Tests.Support" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../../../Recipes/Application/FoodDiary.Modules.Recipes.Application.csproj" /></ItemGroup>
</Project>
