<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>FoodDiary.Application.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Application/Abstractions/FoodDiary.Modules.Gamification.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Application/FoodDiary.Modules.Gamification.Application.csproj" />
    <ProjectReference Include="../../Contracts/FoodDiary.Modules.Gamification.Contracts.csproj" />
    <ProjectReference Include="../../Domain.Contracts/FoodDiary.Modules.Gamification.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../../Shared/FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../../Admin/Application/FoodDiary.Modules.Admin.Application.csproj" />
    <ProjectReference Include="../../../Dashboard/Contracts/FoodDiary.Modules.Dashboard.Contracts.csproj" />
    <ProjectReference Include="../../../Meals/Application/Abstractions/FoodDiary.Modules.Meals.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Meals/Application/FoodDiary.Modules.Meals.Application.csproj" />
    <ProjectReference Include="../../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FoodDiary.Application.Tests.Support" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="NSubstitute" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
