<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>FoodDiary.Application.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Application\FoodDiary.Modules.Gamification.Application.csproj" />
    <ProjectReference Include="..\..\Application\Abstractions\FoodDiary.Modules.Gamification.Application.Abstractions.csproj" />
    <ProjectReference Include="../../../Meals/Application/FoodDiary.Modules.Meals.Application.csproj" />
    <ProjectReference Include="../../../Admin/Application/FoodDiary.Modules.Admin.Application.csproj" />
    <ProjectReference Include="..\..\..\..\FoodDiary.Domain\FoodDiary.Domain.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="FoodDiary.Application.Tests.Support" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="NSubstitute" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
