export const MEAL_DETAIL_MACRO_SUMMARY_LIMIT = 3;
export const MEAL_DETAIL_ITEM_PREVIEW_MAX_ITEMS = 2;
export const MEAL_DETAIL_MIN_MACRO_BAR_PERCENT = 4;
export const MEAL_DETAIL_DEFAULT_QUALITY_GRADE = 'yellow';
export const MEAL_DETAIL_DEFAULT_SATIETY_EMOJI = '\u{1F610}';
