<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Application.Abstractions/FoodDiary.Modules.BodyMetrics.Application.Abstractions.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.BodyMetrics.Application.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.BodyMetrics.Domain.csproj" />
    <ProjectReference Include="../PersistenceModel/FoodDiary.Modules.BodyMetrics.PersistenceModel.csproj" />
    <ProjectReference Include="../../Users/Contracts/FoodDiary.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

</Project>
