<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);IDE0130;MA0003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Application.Abstractions/FoodDiary.Modules.Wearables.Application.Abstractions.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Modules.Wearables.Application.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Wearables.Domain.csproj" />
    <ProjectReference Include="../PersistenceModel/FoodDiary.Modules.Wearables.PersistenceModel.csproj" />
    <ProjectReference Include="../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Application.Contracts/FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Integrations.Http/FoodDiary.Integrations.Http.csproj" />
    <ProjectReference Include="../../../Shared/FoodDiary.Persistence.Abstractions/FoodDiary.Persistence.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

</Project>
