<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FoodDiary.Modules.Marketing.Infrastructure</AssemblyName>
    <RootNamespace>FoodDiary.Modules.Marketing.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Model/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/Abstractions/FoodDiary.Modules.Marketing.Application.Abstractions.csproj" />
    <ProjectReference Include="../Application/FoodDiary.Application.Marketing.csproj" />
    <ProjectReference Include="../Domain/FoodDiary.Modules.Marketing.Domain.csproj" />
    <ProjectReference Include="Model/FoodDiary.Modules.Marketing.PersistenceModel.csproj" />
    <ProjectReference Include="../../../FoodDiary.Infrastructure/FoodDiary.Infrastructure.csproj" />
    <ProjectReference Include="../../Users/Domain.Contracts/FoodDiary.Modules.Users.Domain.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
