<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FoodDiary.Domain</RootNamespace>
    <NoWarn>$(NoWarn);RCS1170</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Shared/FoodDiary.Nutrition.Domain/FoodDiary.Nutrition.Domain.csproj" />
    <ProjectReference Include="../Domain.Contracts/FoodDiary.Modules.Products.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../FoodDiary.Domain/FoodDiary.Domain.csproj" />
    <ProjectReference Include="../../Images/Contracts/FoodDiary.Modules.Images.Contracts.csproj" />
    <ProjectReference Include="../../Usda/Domain/FoodDiary.Modules.Usda.Domain.csproj" />
    <ProjectReference Include="../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>
</Project>
