<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FoodDiary.Email.MailRelay</AssemblyName>
    <RootNamespace>FoodDiary.Integrations</RootNamespace>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FoodDiary.Email.Contracts/FoodDiary.Email.Contracts.csproj" />
    <ProjectReference Include="../../Services/MailRelay/FoodDiary.MailRelay.Client/FoodDiary.MailRelay.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
</Project>
