namespace FoodDiary.Application.Abstractions.Ai.Common;

public interface IAiPromptTemplateRepository : IAiPromptTemplateReadRepository, IAiPromptTemplateReadModelRepository, IAiPromptTemplateWriteRepository;