<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FoodDiary.Domain</RootNamespace></PropertyGroup>
  <PropertyGroup><NoWarn>$(NoWarn);RCS1170</NoWarn></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Images.Contracts.csproj" />
    <ProjectReference Include="../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
  </ItemGroup>
</Project>
