<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Contracts/FoodDiary.Modules.Cycles.Contracts.csproj" />
    <ProjectReference Include="../Domain.Contracts/FoodDiary.Modules.Cycles.Domain.Contracts.csproj" />
    <ProjectReference Include="../Presentation.Contracts/FoodDiary.Modules.Cycles.Presentation.Contracts.csproj" />
  </ItemGroup>

</Project>
