<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>FoodDiary.Infrastructure.Tests</AssemblyName><RootNamespace>FoodDiary.Infrastructure.Tests</RootNamespace><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup><PackageReference Include="coverlet.collector" /><PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" /><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="NSubstitute" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" /></ItemGroup>
  <ItemGroup><Using Include="System.Diagnostics.CodeAnalysis" /><Using Include="NSubstitute" /><Using Include="Xunit" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\FoodDiary.Modules.Dietologist.Infrastructure.csproj" />
    <ProjectReference Include="../../../Users/Domain/FoodDiary.Modules.Users.Domain.csproj" />
    <ProjectReference Include="../../../Identity/Application/Abstractions/FoodDiary.Modules.Identity.Application.Abstractions.csproj" />
    <ProjectReference Include="../../Application/Abstractions/FoodDiary.Modules.Dietologist.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Application.Contracts\FoodDiary.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\FoodDiary.Email.Contracts\FoodDiary.Email.Contracts.csproj" />
  </ItemGroup>
</Project>
