using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("FoodDiary.Infrastructure")]
[assembly: InternalsVisibleTo("FoodDiary.Web.Api")]
[assembly: InternalsVisibleTo("FoodDiary.Domain.Tests")]
[assembly: InternalsVisibleTo("FoodDiary.Application.Tests")]
[assembly: InternalsVisibleTo("FoodDiary.Infrastructure.IntegrationTests")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Dietologist.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Cycles.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Wearables.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Billing.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Notifications.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.MealPlanning.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.MealPlanning.Domain.Tests")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Exercises.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.RecentItems.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Recipes.Domain")]
[assembly: InternalsVisibleTo("FoodDiary.Modules.Hydration.Domain")]
