namespace FoodDiary.Application.Abstractions.Lessons.Common;

public interface INutritionLessonRepository : INutritionLessonReadRepository, INutritionLessonReadModelRepository, INutritionLessonWriteRepository;