<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FoodDiary.Domain</RootNamespace>
    <NoWarn>$(NoWarn);RCS1170</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Domain.Contracts/FoodDiary.Modules.Recipes.Domain.Contracts.csproj" />
    <ProjectReference Include="../../../FoodDiary.Domain/FoodDiary.Domain.csproj" />
  </ItemGroup>
</Project>
