namespace FoodDiary.Application.Abstractions.Exercises.Common;

public interface IExerciseEntryRepository : IExerciseEntryReadRepository, IExerciseEntryReadModelRepository, IExerciseEntryWriteRepository;