name: CI Tests

on:
  pull_request:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  dotnet-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore FoodDiary.slnx

      - name: Build
        run: dotnet build FoodDiary.slnx --configuration Release --no-restore

      - name: Run architecture tests
        run: dotnet test tests/FoodDiary.ArchitectureTests/FoodDiary.ArchitectureTests.csproj --configuration Release --no-restore

      - name: Run application tests
        run: dotnet test tests/FoodDiary.Application.Tests/FoodDiary.Application.Tests.csproj --configuration Release --no-restore

      - name: Run web api integration tests
        run: dotnet test tests/FoodDiary.Web.Api.IntegrationTests/FoodDiary.Web.Api.IntegrationTests.csproj --configuration Release --no-restore
