<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FoodDiary.Persistence.Runtime/FoodDiary.Persistence.Runtime.csproj" />
    <ProjectReference Include="../FoodDiary.Email.Contracts/FoodDiary.Email.Contracts.csproj" />
    <ProjectReference Include="../FoodDiary.Email.PersistenceModel/FoodDiary.Email.PersistenceModel.csproj" />
    <ProjectReference Include="../FoodDiary.Outbox.Infrastructure/FoodDiary.Outbox.Infrastructure.csproj" />
    <ProjectReference Include="../FoodDiary.Outbox.Management.Contracts/FoodDiary.Outbox.Management.Contracts.csproj" />
  </ItemGroup>

</Project>
